// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   @aws-sdk/types
//   @aws-sdk/smithy-client
//   @aws-sdk/config-resolver
//   @aws-sdk/middleware-host-header
//   @aws-sdk/middleware-retry
//   @aws-sdk/middleware-signing
//   @aws-sdk/middleware-user-agent
//   @aws-sdk/protocol-http

declare module '@aws-sdk/client-dynamodb-streams' {
    import { HttpHandlerOptions as __HttpHandlerOptions } from "@aws-sdk/types";
    import { DescribeStreamCommandInput, DescribeStreamCommandOutput } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/commands/DescribeStreamCommand";
    import { GetRecordsCommandInput, GetRecordsCommandOutput } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/commands/GetRecordsCommand";
    import { GetShardIteratorCommandInput, GetShardIteratorCommandOutput } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/commands/GetShardIteratorCommand";
    import { ListStreamsCommandInput, ListStreamsCommandOutput } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/commands/ListStreamsCommand";
    import { DynamoDBStreamsClient } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/DynamoDBStreamsClient";
    /**
        * <fullname>Amazon DynamoDB</fullname>
        *
        *          <p>Amazon DynamoDB Streams provides API actions for accessing streams and processing
        *          stream records. To learn more about application development with Streams, see <a href="https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html">Capturing
        *             Table Activity with DynamoDB Streams</a> in the Amazon DynamoDB Developer
        *          Guide.</p>
        */
    export class DynamoDBStreams extends DynamoDBStreamsClient {
            /**
                * <p>Returns information about a stream, including the current status of the stream, its Amazon Resource Name (ARN), the composition of its shards, and its corresponding DynamoDB table.</p>
                *          <note>
                *             <p>You can call <code>DescribeStream</code> at a maximum rate of 10 times per second.</p>
                *          </note>
                *          <p>Each shard in the stream has a <code>SequenceNumberRange</code> associated with it. If the
                *         <code>SequenceNumberRange</code> has a <code>StartingSequenceNumber</code> but no
                *         <code>EndingSequenceNumber</code>, then the shard is still open (able to receive more stream
                *       records). If both <code>StartingSequenceNumber</code> and <code>EndingSequenceNumber</code>
                *       are present, then that shard is closed and can no longer receive more data.</p>
                */
            describeStream(args: DescribeStreamCommandInput, options?: __HttpHandlerOptions): Promise<DescribeStreamCommandOutput>;
            describeStream(args: DescribeStreamCommandInput, cb: (err: any, data?: DescribeStreamCommandOutput) => void): void;
            describeStream(args: DescribeStreamCommandInput, options: __HttpHandlerOptions, cb: (err: any, data?: DescribeStreamCommandOutput) => void): void;
            /**
                * <p>Retrieves the stream records from a given shard.</p>
                *          <p>Specify a shard iterator using the <code>ShardIterator</code> parameter. The shard iterator
                *       specifies the position in the shard from which you want to start reading stream records
                *       sequentially. If there are no stream records available in the portion of the shard that the
                *       iterator points to, <code>GetRecords</code> returns an empty list. Note that it might take
                *       multiple calls to get to a portion of the shard that contains stream records.</p>
                *          <note>
                *             <p>
                *                <code>GetRecords</code> can retrieve a maximum of 1 MB of data or 1000 stream records,
                *         whichever comes first.</p>
                *          </note>
                */
            getRecords(args: GetRecordsCommandInput, options?: __HttpHandlerOptions): Promise<GetRecordsCommandOutput>;
            getRecords(args: GetRecordsCommandInput, cb: (err: any, data?: GetRecordsCommandOutput) => void): void;
            getRecords(args: GetRecordsCommandInput, options: __HttpHandlerOptions, cb: (err: any, data?: GetRecordsCommandOutput) => void): void;
            /**
                * <p>Returns a shard iterator. A shard iterator provides information
                *       about how to retrieve the stream records from within a shard.  Use
                *       the shard iterator in a subsequent
                *       <code>GetRecords</code> request to read the stream records
                *       from the shard.</p>
                *          <note>
                *             <p>A shard iterator expires 15 minutes after it is returned to the requester.</p>
                *          </note>
                */
            getShardIterator(args: GetShardIteratorCommandInput, options?: __HttpHandlerOptions): Promise<GetShardIteratorCommandOutput>;
            getShardIterator(args: GetShardIteratorCommandInput, cb: (err: any, data?: GetShardIteratorCommandOutput) => void): void;
            getShardIterator(args: GetShardIteratorCommandInput, options: __HttpHandlerOptions, cb: (err: any, data?: GetShardIteratorCommandOutput) => void): void;
            /**
                * <p>Returns an array of stream ARNs associated with the current account and endpoint. If the
                *         <code>TableName</code> parameter is present, then <code>ListStreams</code> will return only the
                *       streams ARNs for that table.</p>
                *          <note>
                *             <p>You can call <code>ListStreams</code> at a maximum rate of 5 times per second.</p>
                *          </note>
                */
            listStreams(args: ListStreamsCommandInput, options?: __HttpHandlerOptions): Promise<ListStreamsCommandOutput>;
            listStreams(args: ListStreamsCommandInput, cb: (err: any, data?: ListStreamsCommandOutput) => void): void;
            listStreams(args: ListStreamsCommandInput, options: __HttpHandlerOptions, cb: (err: any, data?: ListStreamsCommandOutput) => void): void;
    }
}

declare module '@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/commands/DescribeStreamCommand' {
    import { Command as $Command } from "@aws-sdk/smithy-client";
    import { Handler, HttpHandlerOptions as __HttpHandlerOptions, MetadataBearer as __MetadataBearer, MiddlewareStack } from "@aws-sdk/types";
    import { DynamoDBStreamsClientResolvedConfig, ServiceInputTypes, ServiceOutputTypes } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/DynamoDBStreamsClient";
    import { DescribeStreamInput, DescribeStreamOutput } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/models/models_0";
    export interface DescribeStreamCommandInput extends DescribeStreamInput {
    }
    export interface DescribeStreamCommandOutput extends DescribeStreamOutput, __MetadataBearer {
    }
    /**
        * <p>Returns information about a stream, including the current status of the stream, its Amazon Resource Name (ARN), the composition of its shards, and its corresponding DynamoDB table.</p>
        *          <note>
        *             <p>You can call <code>DescribeStream</code> at a maximum rate of 10 times per second.</p>
        *          </note>
        *          <p>Each shard in the stream has a <code>SequenceNumberRange</code> associated with it. If the
        *         <code>SequenceNumberRange</code> has a <code>StartingSequenceNumber</code> but no
        *         <code>EndingSequenceNumber</code>, then the shard is still open (able to receive more stream
        *       records). If both <code>StartingSequenceNumber</code> and <code>EndingSequenceNumber</code>
        *       are present, then that shard is closed and can no longer receive more data.</p>
        * @example
        * Use a bare-bones client and the command you need to make an API call.
        * ```javascript
        * import { DynamoDBStreamsClient, DescribeStreamCommand } from "@aws-sdk/client-dynamodb-streams"; // ES Modules import
        * // const { DynamoDBStreamsClient, DescribeStreamCommand } = require("@aws-sdk/client-dynamodb-streams"); // CommonJS import
        * const client = new DynamoDBStreamsClient(config);
        * const command = new DescribeStreamCommand(input);
        * const response = await client.send(command);
        * ```
        *
        * @see {@link DescribeStreamCommandInput} for command's `input` shape.
        * @see {@link DescribeStreamCommandOutput} for command's `response` shape.
        * @see {@link DynamoDBStreamsClientResolvedConfig | config} for DynamoDBStreamsClient's `config` shape.
        *
        */
    export class DescribeStreamCommand extends $Command<DescribeStreamCommandInput, DescribeStreamCommandOutput, DynamoDBStreamsClientResolvedConfig> {
            readonly input: DescribeStreamCommandInput;
            constructor(input: DescribeStreamCommandInput);
            /**
                * @internal
                */
            resolveMiddleware(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: DynamoDBStreamsClientResolvedConfig, options?: __HttpHandlerOptions): Handler<DescribeStreamCommandInput, DescribeStreamCommandOutput>;
    }
}

declare module '@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/commands/GetRecordsCommand' {
    import { Command as $Command } from "@aws-sdk/smithy-client";
    import { Handler, HttpHandlerOptions as __HttpHandlerOptions, MetadataBearer as __MetadataBearer, MiddlewareStack } from "@aws-sdk/types";
    import { DynamoDBStreamsClientResolvedConfig, ServiceInputTypes, ServiceOutputTypes } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/DynamoDBStreamsClient";
    import { GetRecordsInput, GetRecordsOutput } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/models/models_0";
    export interface GetRecordsCommandInput extends GetRecordsInput {
    }
    export interface GetRecordsCommandOutput extends GetRecordsOutput, __MetadataBearer {
    }
    /**
        * <p>Retrieves the stream records from a given shard.</p>
        *          <p>Specify a shard iterator using the <code>ShardIterator</code> parameter. The shard iterator
        *       specifies the position in the shard from which you want to start reading stream records
        *       sequentially. If there are no stream records available in the portion of the shard that the
        *       iterator points to, <code>GetRecords</code> returns an empty list. Note that it might take
        *       multiple calls to get to a portion of the shard that contains stream records.</p>
        *          <note>
        *             <p>
        *                <code>GetRecords</code> can retrieve a maximum of 1 MB of data or 1000 stream records,
        *         whichever comes first.</p>
        *          </note>
        * @example
        * Use a bare-bones client and the command you need to make an API call.
        * ```javascript
        * import { DynamoDBStreamsClient, GetRecordsCommand } from "@aws-sdk/client-dynamodb-streams"; // ES Modules import
        * // const { DynamoDBStreamsClient, GetRecordsCommand } = require("@aws-sdk/client-dynamodb-streams"); // CommonJS import
        * const client = new DynamoDBStreamsClient(config);
        * const command = new GetRecordsCommand(input);
        * const response = await client.send(command);
        * ```
        *
        * @see {@link GetRecordsCommandInput} for command's `input` shape.
        * @see {@link GetRecordsCommandOutput} for command's `response` shape.
        * @see {@link DynamoDBStreamsClientResolvedConfig | config} for DynamoDBStreamsClient's `config` shape.
        *
        */
    export class GetRecordsCommand extends $Command<GetRecordsCommandInput, GetRecordsCommandOutput, DynamoDBStreamsClientResolvedConfig> {
            readonly input: GetRecordsCommandInput;
            constructor(input: GetRecordsCommandInput);
            /**
                * @internal
                */
            resolveMiddleware(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: DynamoDBStreamsClientResolvedConfig, options?: __HttpHandlerOptions): Handler<GetRecordsCommandInput, GetRecordsCommandOutput>;
    }
}

declare module '@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/commands/GetShardIteratorCommand' {
    import { Command as $Command } from "@aws-sdk/smithy-client";
    import { Handler, HttpHandlerOptions as __HttpHandlerOptions, MetadataBearer as __MetadataBearer, MiddlewareStack } from "@aws-sdk/types";
    import { DynamoDBStreamsClientResolvedConfig, ServiceInputTypes, ServiceOutputTypes } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/DynamoDBStreamsClient";
    import { GetShardIteratorInput, GetShardIteratorOutput } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/models/models_0";
    export interface GetShardIteratorCommandInput extends GetShardIteratorInput {
    }
    export interface GetShardIteratorCommandOutput extends GetShardIteratorOutput, __MetadataBearer {
    }
    /**
        * <p>Returns a shard iterator. A shard iterator provides information
        *       about how to retrieve the stream records from within a shard.  Use
        *       the shard iterator in a subsequent
        *       <code>GetRecords</code> request to read the stream records
        *       from the shard.</p>
        *          <note>
        *             <p>A shard iterator expires 15 minutes after it is returned to the requester.</p>
        *          </note>
        * @example
        * Use a bare-bones client and the command you need to make an API call.
        * ```javascript
        * import { DynamoDBStreamsClient, GetShardIteratorCommand } from "@aws-sdk/client-dynamodb-streams"; // ES Modules import
        * // const { DynamoDBStreamsClient, GetShardIteratorCommand } = require("@aws-sdk/client-dynamodb-streams"); // CommonJS import
        * const client = new DynamoDBStreamsClient(config);
        * const command = new GetShardIteratorCommand(input);
        * const response = await client.send(command);
        * ```
        *
        * @see {@link GetShardIteratorCommandInput} for command's `input` shape.
        * @see {@link GetShardIteratorCommandOutput} for command's `response` shape.
        * @see {@link DynamoDBStreamsClientResolvedConfig | config} for DynamoDBStreamsClient's `config` shape.
        *
        */
    export class GetShardIteratorCommand extends $Command<GetShardIteratorCommandInput, GetShardIteratorCommandOutput, DynamoDBStreamsClientResolvedConfig> {
            readonly input: GetShardIteratorCommandInput;
            constructor(input: GetShardIteratorCommandInput);
            /**
                * @internal
                */
            resolveMiddleware(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: DynamoDBStreamsClientResolvedConfig, options?: __HttpHandlerOptions): Handler<GetShardIteratorCommandInput, GetShardIteratorCommandOutput>;
    }
}

declare module '@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/commands/ListStreamsCommand' {
    import { Command as $Command } from "@aws-sdk/smithy-client";
    import { Handler, HttpHandlerOptions as __HttpHandlerOptions, MetadataBearer as __MetadataBearer, MiddlewareStack } from "@aws-sdk/types";
    import { DynamoDBStreamsClientResolvedConfig, ServiceInputTypes, ServiceOutputTypes } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/DynamoDBStreamsClient";
    import { ListStreamsInput, ListStreamsOutput } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/models/models_0";
    export interface ListStreamsCommandInput extends ListStreamsInput {
    }
    export interface ListStreamsCommandOutput extends ListStreamsOutput, __MetadataBearer {
    }
    /**
        * <p>Returns an array of stream ARNs associated with the current account and endpoint. If the
        *         <code>TableName</code> parameter is present, then <code>ListStreams</code> will return only the
        *       streams ARNs for that table.</p>
        *          <note>
        *             <p>You can call <code>ListStreams</code> at a maximum rate of 5 times per second.</p>
        *          </note>
        * @example
        * Use a bare-bones client and the command you need to make an API call.
        * ```javascript
        * import { DynamoDBStreamsClient, ListStreamsCommand } from "@aws-sdk/client-dynamodb-streams"; // ES Modules import
        * // const { DynamoDBStreamsClient, ListStreamsCommand } = require("@aws-sdk/client-dynamodb-streams"); // CommonJS import
        * const client = new DynamoDBStreamsClient(config);
        * const command = new ListStreamsCommand(input);
        * const response = await client.send(command);
        * ```
        *
        * @see {@link ListStreamsCommandInput} for command's `input` shape.
        * @see {@link ListStreamsCommandOutput} for command's `response` shape.
        * @see {@link DynamoDBStreamsClientResolvedConfig | config} for DynamoDBStreamsClient's `config` shape.
        *
        */
    export class ListStreamsCommand extends $Command<ListStreamsCommandInput, ListStreamsCommandOutput, DynamoDBStreamsClientResolvedConfig> {
            readonly input: ListStreamsCommandInput;
            constructor(input: ListStreamsCommandInput);
            /**
                * @internal
                */
            resolveMiddleware(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: DynamoDBStreamsClientResolvedConfig, options?: __HttpHandlerOptions): Handler<ListStreamsCommandInput, ListStreamsCommandOutput>;
    }
}

declare module '@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/DynamoDBStreamsClient' {
    import { EndpointsInputConfig, EndpointsResolvedConfig, RegionInputConfig, RegionResolvedConfig } from "@aws-sdk/config-resolver";
    import { HostHeaderInputConfig, HostHeaderResolvedConfig } from "@aws-sdk/middleware-host-header";
    import { RetryInputConfig, RetryResolvedConfig } from "@aws-sdk/middleware-retry";
    import { AwsAuthInputConfig, AwsAuthResolvedConfig } from "@aws-sdk/middleware-signing";
    import { UserAgentInputConfig, UserAgentResolvedConfig } from "@aws-sdk/middleware-user-agent";
    import { HttpHandler as __HttpHandler } from "@aws-sdk/protocol-http";
    import { Client as __Client, DefaultsMode, SmithyConfiguration as __SmithyConfiguration, SmithyResolvedConfiguration as __SmithyResolvedConfiguration } from "@aws-sdk/smithy-client";
    import { BodyLengthCalculator as __BodyLengthCalculator, Credentials as __Credentials, Decoder as __Decoder, Encoder as __Encoder, HashConstructor as __HashConstructor, HttpHandlerOptions as __HttpHandlerOptions, Logger as __Logger, Provider as __Provider, Provider, RegionInfoProvider, StreamCollector as __StreamCollector, UrlParser as __UrlParser, UserAgent as __UserAgent } from "@aws-sdk/types";
    import { DescribeStreamCommandInput, DescribeStreamCommandOutput } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/commands/DescribeStreamCommand";
    import { GetRecordsCommandInput, GetRecordsCommandOutput } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/commands/GetRecordsCommand";
    import { GetShardIteratorCommandInput, GetShardIteratorCommandOutput } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/commands/GetShardIteratorCommand";
    import { ListStreamsCommandInput, ListStreamsCommandOutput } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/commands/ListStreamsCommand";
    export type ServiceInputTypes = DescribeStreamCommandInput | GetRecordsCommandInput | GetShardIteratorCommandInput | ListStreamsCommandInput;
    export type ServiceOutputTypes = DescribeStreamCommandOutput | GetRecordsCommandOutput | GetShardIteratorCommandOutput | ListStreamsCommandOutput;
    export interface ClientDefaults extends Partial<__SmithyResolvedConfiguration<__HttpHandlerOptions>> {
            /**
                * The HTTP handler to use. Fetch in browser and Https in Nodejs.
                */
            requestHandler?: __HttpHandler;
            /**
                * A constructor for a class implementing the {@link __Hash} interface
                * that computes the SHA-256 HMAC or checksum of a string or binary buffer.
                * @internal
                */
            sha256?: __HashConstructor;
            /**
                * The function that will be used to convert strings into HTTP endpoints.
                * @internal
                */
            urlParser?: __UrlParser;
            /**
                * A function that can calculate the length of a request body.
                * @internal
                */
            bodyLengthChecker?: __BodyLengthCalculator;
            /**
                * A function that converts a stream into an array of bytes.
                * @internal
                */
            streamCollector?: __StreamCollector;
            /**
                * The function that will be used to convert a base64-encoded string to a byte array.
                * @internal
                */
            base64Decoder?: __Decoder;
            /**
                * The function that will be used to convert binary data to a base64-encoded string.
                * @internal
                */
            base64Encoder?: __Encoder;
            /**
                * The function that will be used to convert a UTF8-encoded string to a byte array.
                * @internal
                */
            utf8Decoder?: __Decoder;
            /**
                * The function that will be used to convert binary data to a UTF-8 encoded string.
                * @internal
                */
            utf8Encoder?: __Encoder;
            /**
                * The runtime environment.
                * @internal
                */
            runtime?: string;
            /**
                * Disable dyanamically changing the endpoint of the client based on the hostPrefix
                * trait of an operation.
                */
            disableHostPrefix?: boolean;
            /**
                * Value for how many times a request will be made at most in case of retry.
                */
            maxAttempts?: number | __Provider<number>;
            /**
                * Specifies which retry algorithm to use.
                */
            retryMode?: string | __Provider<string>;
            /**
                * Optional logger for logging debug/info/warn/error.
                */
            logger?: __Logger;
            /**
                * Enables IPv6/IPv4 dualstack endpoint.
                */
            useDualstackEndpoint?: boolean | __Provider<boolean>;
            /**
                * Enables FIPS compatible endpoints.
                */
            useFipsEndpoint?: boolean | __Provider<boolean>;
            /**
                * Unique service identifier.
                * @internal
                */
            serviceId?: string;
            /**
                * The AWS region to which this client will send requests
                */
            region?: string | __Provider<string>;
            /**
                * Default credentials provider; Not available in browser runtime.
                * @internal
                */
            credentialDefaultProvider?: (input: any) => __Provider<__Credentials>;
            /**
                * Fetch related hostname, signing name or signing region with given region.
                * @internal
                */
            regionInfoProvider?: RegionInfoProvider;
            /**
                * The provider populating default tracking information to be sent with `user-agent`, `x-amz-user-agent` header
                * @internal
                */
            defaultUserAgentProvider?: Provider<__UserAgent>;
            /**
                * The {@link DefaultsMode} that will be used to determine how certain default configuration options are resolved in the SDK.
                */
            defaultsMode?: DefaultsMode | Provider<DefaultsMode>;
    }
    type DynamoDBStreamsClientConfigType = Partial<__SmithyConfiguration<__HttpHandlerOptions>> & ClientDefaults & RegionInputConfig & EndpointsInputConfig & RetryInputConfig & HostHeaderInputConfig & AwsAuthInputConfig & UserAgentInputConfig;
    /**
        * The configuration interface of DynamoDBStreamsClient class constructor that set the region, credentials and other options.
        */
    export interface DynamoDBStreamsClientConfig extends DynamoDBStreamsClientConfigType {
    }
    type DynamoDBStreamsClientResolvedConfigType = __SmithyResolvedConfiguration<__HttpHandlerOptions> & Required<ClientDefaults> & RegionResolvedConfig & EndpointsResolvedConfig & RetryResolvedConfig & HostHeaderResolvedConfig & AwsAuthResolvedConfig & UserAgentResolvedConfig;
    /**
        * The resolved configuration interface of DynamoDBStreamsClient class. This is resolved and normalized from the {@link DynamoDBStreamsClientConfig | constructor configuration interface}.
        */
    export interface DynamoDBStreamsClientResolvedConfig extends DynamoDBStreamsClientResolvedConfigType {
    }
    /**
        * <fullname>Amazon DynamoDB</fullname>
        *
        *          <p>Amazon DynamoDB Streams provides API actions for accessing streams and processing
        *          stream records. To learn more about application development with Streams, see <a href="https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html">Capturing
        *             Table Activity with DynamoDB Streams</a> in the Amazon DynamoDB Developer
        *          Guide.</p>
        */
    export class DynamoDBStreamsClient extends __Client<__HttpHandlerOptions, ServiceInputTypes, ServiceOutputTypes, DynamoDBStreamsClientResolvedConfig> {
            /**
                * The resolved configuration of DynamoDBStreamsClient class. This is resolved and normalized from the {@link DynamoDBStreamsClientConfig | constructor configuration interface}.
                */
            readonly config: DynamoDBStreamsClientResolvedConfig;
            constructor(configuration: DynamoDBStreamsClientConfig);
            /**
                * Destroy underlying resources, like sockets. It's usually not necessary to do this.
                * However in Node.js, it's best to explicitly shut down the client's agent when it is no longer needed.
                * Otherwise, sockets might stay open for quite a long time before the server terminates them.
                */
            destroy(): void;
    }
    export {};
}

declare module '@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/models/models_0' {
    import { ExceptionOptionType as __ExceptionOptionType } from "@aws-sdk/smithy-client";
    import { DynamoDBStreamsServiceException as __BaseException } from "@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/models/DynamoDBStreamsServiceException";
    /**
        * <p>Represents the input of a <code>DescribeStream</code> operation.</p>
        */
    export interface DescribeStreamInput {
            /**
                * <p>The Amazon Resource Name (ARN) for the stream.</p>
                */
            StreamArn: string | undefined;
            /**
                * <p>The maximum number of shard objects to return. The upper limit is 100.</p>
                */
            Limit?: number;
            /**
                * <p>The shard ID of the first item that this operation will evaluate. Use the value that was
                *       returned for <code>LastEvaluatedShardId</code> in the previous operation. </p>
                */
            ExclusiveStartShardId?: string;
    }
    export namespace DescribeStreamInput {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: DescribeStreamInput) => any;
    }
    export type KeyType = "HASH" | "RANGE";
    /**
        * <p>Represents <i>a single element</i> of a key schema. A key schema specifies
        *             the attributes that make up the primary key of a table, or the key attributes of an
        *             index.</p>
        *          <p>A <code>KeySchemaElement</code> represents exactly one attribute of the primary key. For
        *             example, a simple primary key would be represented by one <code>KeySchemaElement</code>
        *             (for the partition key). A composite primary key would require one
        *                 <code>KeySchemaElement</code> for the partition key, and another
        *                 <code>KeySchemaElement</code> for the sort key.</p>
        *          <p>A <code>KeySchemaElement</code> must be a scalar, top-level attribute (not a nested
        *             attribute). The data type must be one of String, Number, or Binary. The attribute cannot
        *             be nested within a List or a Map.</p>
        */
    export interface KeySchemaElement {
            /**
                * <p>The name of a key attribute.</p>
                */
            AttributeName: string | undefined;
            /**
                * <p>The role that this key attribute will assume:</p>
                *          <ul>
                *             <li>
                *               <p>
                *                   <code>HASH</code> - partition key</p>
                *             </li>
                *             <li>
                *               <p>
                *                   <code>RANGE</code> - sort key</p>
                *             </li>
                *          </ul>
                *          <note>
                *             <p>The partition key of an item is also known as its <i>hash
                *                     attribute</i>. The term "hash attribute" derives from DynamoDB's usage of
                *                 an internal hash function to evenly distribute data items across partitions, based
                *                 on their partition key values.</p>
                *             <p>The sort key of an item is also known as its <i>range
                *                 attribute</i>. The term "range attribute" derives from the way DynamoDB
                *                 stores items with the same partition key physically close together, in sorted order
                *                 by the sort key value.</p>
                *          </note>
                */
            KeyType: KeyType | string | undefined;
    }
    export namespace KeySchemaElement {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: KeySchemaElement) => any;
    }
    /**
        * <p>The beginning and ending sequence numbers for the stream records contained within a shard.</p>
        */
    export interface SequenceNumberRange {
            /**
                * <p>The first sequence number for the stream records contained within a shard. String contains numeric characters only.</p>
                */
            StartingSequenceNumber?: string;
            /**
                * <p>The last sequence number for the stream records contained within a shard. String contains numeric characters only.</p>
                */
            EndingSequenceNumber?: string;
    }
    export namespace SequenceNumberRange {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: SequenceNumberRange) => any;
    }
    /**
        * <p>A uniquely identified group of stream records within a stream.</p>
        */
    export interface Shard {
            /**
                * <p>The system-generated identifier for this shard.</p>
                */
            ShardId?: string;
            /**
                * <p>The range of possible sequence numbers for the shard.</p>
                */
            SequenceNumberRange?: SequenceNumberRange;
            /**
                * <p>The shard ID of the current shard's parent.</p>
                */
            ParentShardId?: string;
    }
    export namespace Shard {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: Shard) => any;
    }
    export type StreamStatus = "DISABLED" | "DISABLING" | "ENABLED" | "ENABLING";
    export type StreamViewType = "KEYS_ONLY" | "NEW_AND_OLD_IMAGES" | "NEW_IMAGE" | "OLD_IMAGE";
    /**
        * <p>Represents all of the data describing a particular stream.</p>
        */
    export interface StreamDescription {
            /**
                * <p>The Amazon Resource Name (ARN) for the stream.</p>
                */
            StreamArn?: string;
            /**
                * <p>A timestamp, in ISO 8601 format, for this stream.</p>
                *          <p>Note that <code>LatestStreamLabel</code> is not a unique identifier for the stream, because it is
                *       possible that a stream from another table might have the same timestamp. However, the
                *       combination of the following three elements is guaranteed to be unique:</p>
                *          <ul>
                *             <li>
                *                <p>the AWS customer ID.</p>
                *             </li>
                *             <li>
                *                <p>the table name</p>
                *             </li>
                *             <li>
                *                <p>the <code>StreamLabel</code>
                *                </p>
                *             </li>
                *          </ul>
                */
            StreamLabel?: string;
            /**
                * <p>Indicates the current status of the stream:</p>
                *          <ul>
                *             <li>
                *                <p>
                *                   <code>ENABLING</code> - Streams is currently being enabled on the DynamoDB table.</p>
                *             </li>
                *             <li>
                *                <p>
                *                   <code>ENABLED</code> - the stream is enabled.</p>
                *             </li>
                *             <li>
                *                <p>
                *                   <code>DISABLING</code> - Streams is currently being disabled on the DynamoDB table.</p>
                *             </li>
                *             <li>
                *                <p>
                *                   <code>DISABLED</code> - the stream is disabled.</p>
                *             </li>
                *          </ul>
                */
            StreamStatus?: StreamStatus | string;
            /**
                * <p>Indicates the format of the records within this stream:</p>
                *          <ul>
                *             <li>
                *                <p>
                *                   <code>KEYS_ONLY</code> - only the key attributes of items that were modified in the DynamoDB table.</p>
                *             </li>
                *             <li>
                *                <p>
                *                   <code>NEW_IMAGE</code> - entire items from the table, as they appeared after they were modified.</p>
                *             </li>
                *             <li>
                *                <p>
                *                   <code>OLD_IMAGE</code> - entire items from the table, as they appeared before they were modified.</p>
                *             </li>
                *             <li>
                *                <p>
                *                   <code>NEW_AND_OLD_IMAGES</code> - both the new and the old images of the items from the table.</p>
                *             </li>
                *          </ul>
                */
            StreamViewType?: StreamViewType | string;
            /**
                * <p>The date and time when the request to create this stream was issued.</p>
                */
            CreationRequestDateTime?: Date;
            /**
                * <p>The DynamoDB table with which the stream is associated.</p>
                */
            TableName?: string;
            /**
                * <p>The key attribute(s) of the stream's DynamoDB table.</p>
                */
            KeySchema?: KeySchemaElement[];
            /**
                * <p>The shards that comprise the stream.</p>
                */
            Shards?: Shard[];
            /**
                * <p>The shard ID of the item where the operation stopped, inclusive of the previous result set. Use this value to start a new operation, excluding this value in the new request.</p>
                *          <p>If <code>LastEvaluatedShardId</code> is empty, then the "last page" of results has been
                *       processed and there is currently no more data to be retrieved.</p>
                *          <p>If <code>LastEvaluatedShardId</code> is not empty, it does not necessarily mean that there is
                *       more data in the result set. The only way to know when you have reached the end of the result
                *       set is when <code>LastEvaluatedShardId</code> is empty.</p>
                */
            LastEvaluatedShardId?: string;
    }
    export namespace StreamDescription {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: StreamDescription) => any;
    }
    /**
        * <p>Represents the output of a <code>DescribeStream</code> operation.</p>
        */
    export interface DescribeStreamOutput {
            /**
                * <p>A complete description of the stream, including its creation date and time, the DynamoDB table associated with the stream, the shard IDs within the stream, and the beginning and ending sequence numbers of stream records within the shards.</p>
                */
            StreamDescription?: StreamDescription;
    }
    export namespace DescribeStreamOutput {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: DescribeStreamOutput) => any;
    }
    /**
        * <p>An error occurred on the server side.</p>
        */
    export class InternalServerError extends __BaseException {
            readonly name: "InternalServerError";
            readonly $fault: "server";
            /**
                * @internal
                */
            constructor(opts: __ExceptionOptionType<InternalServerError, __BaseException>);
    }
    /**
        * <p>The operation tried to access a nonexistent table or index. The resource
        *             might not be specified correctly, or its status might not be
        *             <code>ACTIVE</code>.</p>
        */
    export class ResourceNotFoundException extends __BaseException {
            readonly name: "ResourceNotFoundException";
            readonly $fault: "client";
            /**
                * @internal
                */
            constructor(opts: __ExceptionOptionType<ResourceNotFoundException, __BaseException>);
    }
    /**
        * <p>The shard iterator has expired and can no longer be used to retrieve stream records. A shard
        *       iterator expires 15 minutes after it is retrieved using the <code>GetShardIterator</code>
        *       action.</p>
        */
    export class ExpiredIteratorException extends __BaseException {
            readonly name: "ExpiredIteratorException";
            readonly $fault: "client";
            /**
                * @internal
                */
            constructor(opts: __ExceptionOptionType<ExpiredIteratorException, __BaseException>);
    }
    /**
        * <p>Represents the input of a <code>GetRecords</code> operation.</p>
        */
    export interface GetRecordsInput {
            /**
                * <p>A shard iterator that was retrieved from a previous GetShardIterator operation. This iterator can be used to access the stream records in this shard.</p>
                */
            ShardIterator: string | undefined;
            /**
                * <p>The maximum number of records to return from the shard. The upper limit is 1000.</p>
                */
            Limit?: number;
    }
    export namespace GetRecordsInput {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: GetRecordsInput) => any;
    }
    export type OperationType = "INSERT" | "MODIFY" | "REMOVE";
    /**
        * <p>Contains details about the type of identity that made the request.</p>
        */
    export interface Identity {
            /**
                * <p>A unique identifier for the entity that made the call. For Time To Live, the
                *       principalId is "dynamodb.amazonaws.com".</p>
                */
            PrincipalId?: string;
            /**
                * <p>The type of the identity. For Time To Live, the type is "Service".</p>
                */
            Type?: string;
    }
    export namespace Identity {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: Identity) => any;
    }
    /**
        * <p>There is no limit to the number of daily on-demand backups that can be taken. </p>
        *          <p>Up to 500 simultaneous table operations are allowed per account. These operations
        *           include <code>CreateTable</code>, <code>UpdateTable</code>,
        *           <code>DeleteTable</code>,<code>UpdateTimeToLive</code>,
        *           <code>RestoreTableFromBackup</code>, and <code>RestoreTableToPointInTime</code>. </p>
        *          <p>The only exception is when you are creating a table with one or more secondary
        *           indexes. You can have up to 250 such requests running at a time; however, if the table or
        *           index specifications are complex, DynamoDB might temporarily reduce the number
        *           of concurrent operations.</p>
        *          <p>There is a soft account quota of 2,500 tables.</p>
        */
    export class LimitExceededException extends __BaseException {
            readonly name: "LimitExceededException";
            readonly $fault: "client";
            /**
                * @internal
                */
            constructor(opts: __ExceptionOptionType<LimitExceededException, __BaseException>);
    }
    /**
        * <p>The operation attempted to read past the oldest stream record in a shard.</p>
        *          <p>In DynamoDB Streams, there is a 24 hour limit on data retention. Stream records whose age exceeds this limit are subject to removal (trimming) from the stream. You might receive a TrimmedDataAccessException if:</p>
        *          <ul>
        *             <li>
        *                <p>You request a shard iterator with a sequence number older than the trim point (24 hours).</p>
        *             </li>
        *             <li>
        *                <p>You obtain a shard iterator, but before you use the iterator in a <code>GetRecords</code>
        *         request, a stream record in the shard exceeds the 24 hour period and is trimmed. This causes
        *         the iterator to access a record that no longer exists.</p>
        *             </li>
        *          </ul>
        */
    export class TrimmedDataAccessException extends __BaseException {
            readonly name: "TrimmedDataAccessException";
            readonly $fault: "client";
            /**
                * @internal
                */
            constructor(opts: __ExceptionOptionType<TrimmedDataAccessException, __BaseException>);
    }
    export type ShardIteratorType = "AFTER_SEQUENCE_NUMBER" | "AT_SEQUENCE_NUMBER" | "LATEST" | "TRIM_HORIZON";
    /**
        * <p>Represents the input of a <code>GetShardIterator</code> operation.</p>
        */
    export interface GetShardIteratorInput {
            /**
                * <p>The Amazon Resource Name (ARN) for the stream.</p>
                */
            StreamArn: string | undefined;
            /**
                * <p>The identifier of the shard. The iterator will be returned for this shard ID.</p>
                */
            ShardId: string | undefined;
            /**
                * <p>Determines how the shard iterator is used to start reading stream records from the shard:</p>
                *          <ul>
                *             <li>
                *                <p>
                *                   <code>AT_SEQUENCE_NUMBER</code> - Start reading exactly from the position denoted by a
                *           specific sequence number.</p>
                *             </li>
                *             <li>
                *                <p>
                *                   <code>AFTER_SEQUENCE_NUMBER</code> - Start reading right after the position denoted by a
                *           specific sequence number.</p>
                *             </li>
                *             <li>
                *                <p>
                *                   <code>TRIM_HORIZON</code> - Start reading at the last (untrimmed) stream record, which is
                *           the oldest record in the shard. In DynamoDB Streams, there is a 24 hour limit on data retention.
                *           Stream records whose age exceeds this limit are subject to removal (trimming) from the
                *           stream.</p>
                *             </li>
                *             <li>
                *                <p>
                *                   <code>LATEST</code> - Start reading just after the most recent stream record in the
                *           shard, so that you always read the most recent data in the shard.</p>
                *             </li>
                *          </ul>
                */
            ShardIteratorType: ShardIteratorType | string | undefined;
            /**
                * <p>The sequence number of a stream record in the shard from which to start reading.</p>
                */
            SequenceNumber?: string;
    }
    export namespace GetShardIteratorInput {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: GetShardIteratorInput) => any;
    }
    /**
        * <p>Represents the output of a <code>GetShardIterator</code> operation.</p>
        */
    export interface GetShardIteratorOutput {
            /**
                * <p>The position in the shard from which to start reading stream records sequentially. A shard iterator specifies this position using the sequence number of a stream record in a shard.</p>
                */
            ShardIterator?: string;
    }
    export namespace GetShardIteratorOutput {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: GetShardIteratorOutput) => any;
    }
    /**
        * <p>Represents the input of a <code>ListStreams</code> operation.</p>
        */
    export interface ListStreamsInput {
            /**
                * <p>If this parameter is provided, then only the streams associated with this table name are returned.</p>
                */
            TableName?: string;
            /**
                * <p>The maximum number of streams to return. The upper limit is 100.</p>
                */
            Limit?: number;
            /**
                * <p>The ARN (Amazon Resource Name) of the first item that this operation will evaluate. Use the
                *       value that was returned for <code>LastEvaluatedStreamArn</code> in the previous operation.
                *     </p>
                */
            ExclusiveStartStreamArn?: string;
    }
    export namespace ListStreamsInput {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: ListStreamsInput) => any;
    }
    /**
        * <p>Represents all of the data describing a particular stream.</p>
        */
    export interface _Stream {
            /**
                * <p>The Amazon Resource Name (ARN) for the stream.</p>
                */
            StreamArn?: string;
            /**
                * <p>The DynamoDB table with which the stream is associated.</p>
                */
            TableName?: string;
            /**
                * <p>A timestamp, in ISO 8601 format, for this stream.</p>
                *          <p>Note that <code>LatestStreamLabel</code> is not a unique identifier for the stream, because it is
                *       possible that a stream from another table might have the same timestamp. However, the
                *       combination of the following three elements is guaranteed to be unique:</p>
                *          <ul>
                *             <li>
                *                <p>the AWS customer ID.</p>
                *             </li>
                *             <li>
                *                <p>the table name</p>
                *             </li>
                *             <li>
                *                <p>the <code>StreamLabel</code>
                *                </p>
                *             </li>
                *          </ul>
                */
            StreamLabel?: string;
    }
    export namespace _Stream {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: _Stream) => any;
    }
    /**
        * <p>Represents the output of a <code>ListStreams</code> operation.</p>
        */
    export interface ListStreamsOutput {
            /**
                * <p>A list of stream descriptors associated with the current account and endpoint.</p>
                */
            Streams?: _Stream[];
            /**
                * <p>The stream ARN of the item where the operation stopped, inclusive of the previous result set. Use this value to start a new operation, excluding this value in the new request.</p>
                *          <p>If <code>LastEvaluatedStreamArn</code> is empty, then the "last page" of results has been
                *       processed and there is no more data to be retrieved.</p>
                *          <p>If <code>LastEvaluatedStreamArn</code> is not empty, it does not necessarily mean that there
                *       is more data in the result set. The only way to know when you have reached the end of the
                *       result set is when <code>LastEvaluatedStreamArn</code> is empty.</p>
                */
            LastEvaluatedStreamArn?: string;
    }
    export namespace ListStreamsOutput {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: ListStreamsOutput) => any;
    }
    /**
        * <p>Represents the data for an attribute.</p>
        *          <p>Each attribute value is described as a name-value pair.  The name is the data type, and the value is the data itself.</p>
        *          <p>For more information, see <a href="https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes">Data Types</a> in the
        *                              <i>Amazon DynamoDB Developer Guide</i>.</p>
        */
    export type AttributeValue = AttributeValue.BMember | AttributeValue.BOOLMember | AttributeValue.BSMember | AttributeValue.LMember | AttributeValue.MMember | AttributeValue.NMember | AttributeValue.NSMember | AttributeValue.NULLMember | AttributeValue.SMember | AttributeValue.SSMember | AttributeValue.$UnknownMember;
    export namespace AttributeValue {
            /**
                * <p>An attribute of type  String. For example:</p>
                *          <p>
                *             <code>"S": "Hello"</code>
                *          </p>
                */
            interface SMember {
                    S: string;
                    N?: never;
                    B?: never;
                    SS?: never;
                    NS?: never;
                    BS?: never;
                    M?: never;
                    L?: never;
                    NULL?: never;
                    BOOL?: never;
                    $unknown?: never;
            }
            /**
                * <p>An attribute of type Number. For example:</p>
                *          <p>
                *             <code>"N": "123.45"</code>
                *          </p>
                *          <p>Numbers are sent across the network to DynamoDB as strings, to maximize compatibility across languages and libraries. However, DynamoDB treats them as number type attributes for mathematical operations.</p>
                */
            interface NMember {
                    S?: never;
                    N: string;
                    B?: never;
                    SS?: never;
                    NS?: never;
                    BS?: never;
                    M?: never;
                    L?: never;
                    NULL?: never;
                    BOOL?: never;
                    $unknown?: never;
            }
            /**
                * <p>An attribute of type Binary.  For example:</p>
                *          <p>
                *             <code>"B": "dGhpcyB0ZXh0IGlzIGJhc2U2NC1lbmNvZGVk"</code>
                *          </p>
                */
            interface BMember {
                    S?: never;
                    N?: never;
                    B: Uint8Array;
                    SS?: never;
                    NS?: never;
                    BS?: never;
                    M?: never;
                    L?: never;
                    NULL?: never;
                    BOOL?: never;
                    $unknown?: never;
            }
            /**
                * <p>An attribute of type String Set.  For example:</p>
                *          <p>
                *             <code>"SS": ["Giraffe", "Hippo" ,"Zebra"]</code>
                *          </p>
                */
            interface SSMember {
                    S?: never;
                    N?: never;
                    B?: never;
                    SS: string[];
                    NS?: never;
                    BS?: never;
                    M?: never;
                    L?: never;
                    NULL?: never;
                    BOOL?: never;
                    $unknown?: never;
            }
            /**
                * <p>An attribute of type Number Set.  For example:</p>
                *          <p>
                *             <code>"NS": ["42.2", "-19", "7.5", "3.14"]</code>
                *          </p>
                *          <p>Numbers are sent across the network to DynamoDB as strings, to maximize compatibility across languages and libraries. However, DynamoDB treats them as number type attributes for mathematical operations.</p>
                */
            interface NSMember {
                    S?: never;
                    N?: never;
                    B?: never;
                    SS?: never;
                    NS: string[];
                    BS?: never;
                    M?: never;
                    L?: never;
                    NULL?: never;
                    BOOL?: never;
                    $unknown?: never;
            }
            /**
                * <p>An attribute of type Binary Set.  For example:</p>
                *          <p>
                *             <code>"BS": ["U3Vubnk=", "UmFpbnk=", "U25vd3k="]</code>
                *          </p>
                */
            interface BSMember {
                    S?: never;
                    N?: never;
                    B?: never;
                    SS?: never;
                    NS?: never;
                    BS: Uint8Array[];
                    M?: never;
                    L?: never;
                    NULL?: never;
                    BOOL?: never;
                    $unknown?: never;
            }
            /**
                * <p>An attribute of type Map.  For example:</p>
                *          <p>
                *             <code>"M": {"Name": {"S": "Joe"}, "Age": {"N": "35"}}</code>
                *          </p>
                */
            interface MMember {
                    S?: never;
                    N?: never;
                    B?: never;
                    SS?: never;
                    NS?: never;
                    BS?: never;
                    M: Record<string, AttributeValue>;
                    L?: never;
                    NULL?: never;
                    BOOL?: never;
                    $unknown?: never;
            }
            /**
                * <p>An attribute of type List.  For example:</p>
                *          <p>
                *             <code>"L": [ {"S": "Cookies"} , {"S": "Coffee"}, {"N": "3.14159"}]</code>
                *          </p>
                */
            interface LMember {
                    S?: never;
                    N?: never;
                    B?: never;
                    SS?: never;
                    NS?: never;
                    BS?: never;
                    M?: never;
                    L: AttributeValue[];
                    NULL?: never;
                    BOOL?: never;
                    $unknown?: never;
            }
            /**
                * <p>An attribute of type Null.  For example:</p>
                *          <p>
                *             <code>"NULL": true</code>
                *          </p>
                */
            interface NULLMember {
                    S?: never;
                    N?: never;
                    B?: never;
                    SS?: never;
                    NS?: never;
                    BS?: never;
                    M?: never;
                    L?: never;
                    NULL: boolean;
                    BOOL?: never;
                    $unknown?: never;
            }
            /**
                * <p>An attribute of type Boolean.  For example:</p>
                *          <p>
                *             <code>"BOOL": true</code>
                *          </p>
                */
            interface BOOLMember {
                    S?: never;
                    N?: never;
                    B?: never;
                    SS?: never;
                    NS?: never;
                    BS?: never;
                    M?: never;
                    L?: never;
                    NULL?: never;
                    BOOL: boolean;
                    $unknown?: never;
            }
            interface $UnknownMember {
                    S?: never;
                    N?: never;
                    B?: never;
                    SS?: never;
                    NS?: never;
                    BS?: never;
                    M?: never;
                    L?: never;
                    NULL?: never;
                    BOOL?: never;
                    $unknown: [string, any];
            }
            interface Visitor<T> {
                    S: (value: string) => T;
                    N: (value: string) => T;
                    B: (value: Uint8Array) => T;
                    SS: (value: string[]) => T;
                    NS: (value: string[]) => T;
                    BS: (value: Uint8Array[]) => T;
                    M: (value: Record<string, AttributeValue>) => T;
                    L: (value: AttributeValue[]) => T;
                    NULL: (value: boolean) => T;
                    BOOL: (value: boolean) => T;
                    _: (name: string, value: any) => T;
            }
            const visit: <T>(value: AttributeValue, visitor: Visitor<T>) => T;
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: AttributeValue) => any;
    }
    /**
        * <p>A description of a single data modification that was performed on an item in a DynamoDB table.</p>
        */
    export interface StreamRecord {
            /**
                * <p>The approximate date and time when the stream record was created, in <a href="http://www.epochconverter.com/">UNIX epoch time</a> format.</p>
                */
            ApproximateCreationDateTime?: Date;
            /**
                * <p>The primary key attribute(s) for the DynamoDB item that was modified.</p>
                */
            Keys?: Record<string, AttributeValue>;
            /**
                * <p>The item in the DynamoDB table as it appeared after it was modified.</p>
                */
            NewImage?: Record<string, AttributeValue>;
            /**
                * <p>The item in the DynamoDB table as it appeared before it was modified.</p>
                */
            OldImage?: Record<string, AttributeValue>;
            /**
                * <p>The sequence number of the stream record.</p>
                */
            SequenceNumber?: string;
            /**
                * <p>The size of the stream record, in bytes.</p>
                */
            SizeBytes?: number;
            /**
                * <p>The type of data from the modified DynamoDB item that was captured in this stream record:</p>
                *          <ul>
                *             <li>
                *                <p>
                *                   <code>KEYS_ONLY</code> - only the key attributes of the modified item.</p>
                *             </li>
                *             <li>
                *                <p>
                *                   <code>NEW_IMAGE</code> - the entire item, as it appeared after it was modified.</p>
                *             </li>
                *             <li>
                *                <p>
                *                   <code>OLD_IMAGE</code> - the entire item, as it appeared before it was modified.</p>
                *             </li>
                *             <li>
                *                <p>
                *                   <code>NEW_AND_OLD_IMAGES</code> - both the new and the old item images of the item.</p>
                *             </li>
                *          </ul>
                */
            StreamViewType?: StreamViewType | string;
    }
    export namespace StreamRecord {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: StreamRecord) => any;
    }
    /**
        * <p>A description of a unique event within a stream.</p>
        */
    export interface _Record {
            /**
                * <p>A globally unique identifier for the event that was recorded in this stream record.</p>
                */
            eventID?: string;
            /**
                * <p>The type of data modification that was performed on the DynamoDB table:</p>
                *          <ul>
                *             <li>
                *                <p>
                *                   <code>INSERT</code> - a new item was added to the table.</p>
                *             </li>
                *             <li>
                *                <p>
                *                   <code>MODIFY</code> - one or more of an existing item's attributes were modified.</p>
                *             </li>
                *             <li>
                *                <p>
                *                   <code>REMOVE</code> - the item was deleted from the table</p>
                *             </li>
                *          </ul>
                */
            eventName?: OperationType | string;
            /**
                * <p>The version number of the stream record format.  This number is updated whenever the structure of <code>Record</code> is modified.</p>
                *          <p>Client applications must not assume that <code>eventVersion</code> will remain at a particular
                *       value, as this number is subject to change at any time. In general, <code>eventVersion</code> will
                *       only increase as the low-level DynamoDB Streams API evolves.</p>
                */
            eventVersion?: string;
            /**
                * <p>The AWS service from which the stream record originated.  For DynamoDB Streams, this is <code>aws:dynamodb</code>.</p>
                */
            eventSource?: string;
            /**
                * <p>The region in which the <code>GetRecords</code> request was received.</p>
                */
            awsRegion?: string;
            /**
                * <p>The main body of the stream record, containing all of the DynamoDB-specific fields.</p>
                */
            dynamodb?: StreamRecord;
            /**
                * <p>Items that are deleted by the Time to Live process after expiration have the following fields: </p>
                *          <ul>
                *             <li>
                *                <p>Records[].userIdentity.type</p>
                *                <p>"Service"</p>
                *             </li>
                *             <li>
                *                <p>Records[].userIdentity.principalId</p>
                *                <p>"dynamodb.amazonaws.com"</p>
                *             </li>
                *          </ul>
                */
            userIdentity?: Identity;
    }
    export namespace _Record {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: _Record) => any;
    }
    /**
        * <p>Represents the output of a <code>GetRecords</code> operation.</p>
        */
    export interface GetRecordsOutput {
            /**
                * <p>The stream records from the shard, which were retrieved using the shard iterator.</p>
                */
            Records?: _Record[];
            /**
                * <p>The next position in the shard from which to start sequentially reading stream records. If
                *       set to <code>null</code>, the shard has been closed and the requested iterator will not return
                *       any more data.</p>
                */
            NextShardIterator?: string;
    }
    export namespace GetRecordsOutput {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: GetRecordsOutput) => any;
    }
}

declare module '@aws-sdk/client-dynamodb-streams/node_modules/@aws-sdk/client-dynamodb-streams/dist-types/models/DynamoDBStreamsServiceException' {
    import { ServiceException as __ServiceException, ServiceExceptionOptions as __ServiceExceptionOptions } from "@aws-sdk/smithy-client";
    /**
        * Base exception class for all service exceptions from DynamoDBStreams service.
        */
    export class DynamoDBStreamsServiceException extends __ServiceException {
            /**
                * @internal
                */
            constructor(options: __ServiceExceptionOptions);
    }
}

