// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   @aws-sdk/types
//   @aws-sdk/smithy-client
//   @aws-sdk/config-resolver
//   @aws-sdk/middleware-host-header
//   @aws-sdk/middleware-retry
//   @aws-sdk/middleware-signing
//   @aws-sdk/middleware-user-agent
//   @aws-sdk/protocol-http

declare module '@aws-sdk/client-macie' {
    import { HttpHandlerOptions as __HttpHandlerOptions } from "@aws-sdk/types";
    import { AssociateMemberAccountCommandInput, AssociateMemberAccountCommandOutput } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/AssociateMemberAccountCommand";
    import { AssociateS3ResourcesCommandInput, AssociateS3ResourcesCommandOutput } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/AssociateS3ResourcesCommand";
    import { DisassociateMemberAccountCommandInput, DisassociateMemberAccountCommandOutput } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/DisassociateMemberAccountCommand";
    import { DisassociateS3ResourcesCommandInput, DisassociateS3ResourcesCommandOutput } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/DisassociateS3ResourcesCommand";
    import { ListMemberAccountsCommandInput, ListMemberAccountsCommandOutput } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/ListMemberAccountsCommand";
    import { ListS3ResourcesCommandInput, ListS3ResourcesCommandOutput } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/ListS3ResourcesCommand";
    import { UpdateS3ResourcesCommandInput, UpdateS3ResourcesCommandOutput } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/UpdateS3ResourcesCommand";
    import { MacieClient } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/MacieClient";
    /**
        * <fullname>Amazon Macie Classic</fullname>
        *          <p>Amazon Macie Classic has been discontinued and is no longer available.</p>
        *
        *          <p>A new Amazon Macie is now available with significant design improvements and additional
        *       features, at a lower price and in most Amazon Web Services Regions. We encourage you to take advantage of the
        *       new and improved features, and benefit from the reduced cost. To learn about features and pricing for the new Macie, see <a href="http://aws.amazon.com/macie/">Amazon Macie</a>. To learn how to use the new Macie, see the <a href="https://docs.aws.amazon.com/macie/latest/user/what-is-macie.html">Amazon Macie User
        *         Guide</a>.</p>
        */
    export class Macie extends MacieClient {
            /**
                * <p>(Discontinued) Associates a specified Amazon Web Services account with Amazon Macie Classic as a member
                *       account.</p>
                */
            associateMemberAccount(args: AssociateMemberAccountCommandInput, options?: __HttpHandlerOptions): Promise<AssociateMemberAccountCommandOutput>;
            associateMemberAccount(args: AssociateMemberAccountCommandInput, cb: (err: any, data?: AssociateMemberAccountCommandOutput) => void): void;
            associateMemberAccount(args: AssociateMemberAccountCommandInput, options: __HttpHandlerOptions, cb: (err: any, data?: AssociateMemberAccountCommandOutput) => void): void;
            /**
                * <p>(Discontinued) Associates specified S3 resources with Amazon Macie Classic for
                *       monitoring and data classification. If <code>memberAccountId</code> isn't specified, the action associates
                *       specified S3 resources with Macie Classic for the current Macie Classic administrator account.
                *       If <code>memberAccountId</code> is specified, the action associates specified S3 resources with Macie
                *       Classic for the specified member account.</p>
                */
            associateS3Resources(args: AssociateS3ResourcesCommandInput, options?: __HttpHandlerOptions): Promise<AssociateS3ResourcesCommandOutput>;
            associateS3Resources(args: AssociateS3ResourcesCommandInput, cb: (err: any, data?: AssociateS3ResourcesCommandOutput) => void): void;
            associateS3Resources(args: AssociateS3ResourcesCommandInput, options: __HttpHandlerOptions, cb: (err: any, data?: AssociateS3ResourcesCommandOutput) => void): void;
            /**
                * <p>(Discontinued) Removes the specified member account from Amazon Macie
                *       Classic.</p>
                */
            disassociateMemberAccount(args: DisassociateMemberAccountCommandInput, options?: __HttpHandlerOptions): Promise<DisassociateMemberAccountCommandOutput>;
            disassociateMemberAccount(args: DisassociateMemberAccountCommandInput, cb: (err: any, data?: DisassociateMemberAccountCommandOutput) => void): void;
            disassociateMemberAccount(args: DisassociateMemberAccountCommandInput, options: __HttpHandlerOptions, cb: (err: any, data?: DisassociateMemberAccountCommandOutput) => void): void;
            /**
                * <p>(Discontinued) Removes specified S3 resources from being monitored by Amazon Macie
                *       Classic. If <code>memberAccountId</code> isn't specified, the action removes specified S3 resources from
                *       Macie Classic for the current Macie Classic administrator account. If <code>memberAccountId</code> is
                *       specified, the action removes specified S3 resources from Macie Classic for the specified
                *       member account.</p>
                */
            disassociateS3Resources(args: DisassociateS3ResourcesCommandInput, options?: __HttpHandlerOptions): Promise<DisassociateS3ResourcesCommandOutput>;
            disassociateS3Resources(args: DisassociateS3ResourcesCommandInput, cb: (err: any, data?: DisassociateS3ResourcesCommandOutput) => void): void;
            disassociateS3Resources(args: DisassociateS3ResourcesCommandInput, options: __HttpHandlerOptions, cb: (err: any, data?: DisassociateS3ResourcesCommandOutput) => void): void;
            /**
                * <p>(Discontinued) Lists all Amazon Macie Classic member accounts for the current Macie
                *       Classic administrator account.</p>
                */
            listMemberAccounts(args: ListMemberAccountsCommandInput, options?: __HttpHandlerOptions): Promise<ListMemberAccountsCommandOutput>;
            listMemberAccounts(args: ListMemberAccountsCommandInput, cb: (err: any, data?: ListMemberAccountsCommandOutput) => void): void;
            listMemberAccounts(args: ListMemberAccountsCommandInput, options: __HttpHandlerOptions, cb: (err: any, data?: ListMemberAccountsCommandOutput) => void): void;
            /**
                * <p>(Discontinued) Lists all the S3 resources associated with Amazon Macie Classic. If
                *       <code>memberAccountId</code> isn't specified, the action lists the S3 resources associated with Macie
                *       Classic for the current Macie Classic administrator account. If <code>memberAccountId</code> is specified,
                *       the action lists the S3 resources associated with Macie Classic for the specified member
                *       account. </p>
                */
            listS3Resources(args: ListS3ResourcesCommandInput, options?: __HttpHandlerOptions): Promise<ListS3ResourcesCommandOutput>;
            listS3Resources(args: ListS3ResourcesCommandInput, cb: (err: any, data?: ListS3ResourcesCommandOutput) => void): void;
            listS3Resources(args: ListS3ResourcesCommandInput, options: __HttpHandlerOptions, cb: (err: any, data?: ListS3ResourcesCommandOutput) => void): void;
            /**
                * <p>(Discontinued) Updates the classification types for the specified S3 resources. If
                *       <code>memberAccountId</code> isn't specified, the action updates the classification types of the S3
                *       resources associated with Amazon Macie Classic for the current Macie Classic administrator
                *       account. If <code>memberAccountId</code> is specified, the action updates the classification types of the
                *       S3 resources associated with Macie Classic for the specified member account.</p>
                */
            updateS3Resources(args: UpdateS3ResourcesCommandInput, options?: __HttpHandlerOptions): Promise<UpdateS3ResourcesCommandOutput>;
            updateS3Resources(args: UpdateS3ResourcesCommandInput, cb: (err: any, data?: UpdateS3ResourcesCommandOutput) => void): void;
            updateS3Resources(args: UpdateS3ResourcesCommandInput, options: __HttpHandlerOptions, cb: (err: any, data?: UpdateS3ResourcesCommandOutput) => void): void;
    }
}

declare module '@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/AssociateMemberAccountCommand' {
    import { Command as $Command } from "@aws-sdk/smithy-client";
    import { Handler, HttpHandlerOptions as __HttpHandlerOptions, MetadataBearer as __MetadataBearer, MiddlewareStack } from "@aws-sdk/types";
    import { MacieClientResolvedConfig, ServiceInputTypes, ServiceOutputTypes } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/MacieClient";
    import { AssociateMemberAccountRequest } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/models/models_0";
    export interface AssociateMemberAccountCommandInput extends AssociateMemberAccountRequest {
    }
    export interface AssociateMemberAccountCommandOutput extends __MetadataBearer {
    }
    /**
        * <p>(Discontinued) Associates a specified Amazon Web Services account with Amazon Macie Classic as a member
        *       account.</p>
        * @example
        * Use a bare-bones client and the command you need to make an API call.
        * ```javascript
        * import { MacieClient, AssociateMemberAccountCommand } from "@aws-sdk/client-macie"; // ES Modules import
        * // const { MacieClient, AssociateMemberAccountCommand } = require("@aws-sdk/client-macie"); // CommonJS import
        * const client = new MacieClient(config);
        * const command = new AssociateMemberAccountCommand(input);
        * const response = await client.send(command);
        * ```
        *
        * @see {@link AssociateMemberAccountCommandInput} for command's `input` shape.
        * @see {@link AssociateMemberAccountCommandOutput} for command's `response` shape.
        * @see {@link MacieClientResolvedConfig | config} for MacieClient's `config` shape.
        *
        */
    export class AssociateMemberAccountCommand extends $Command<AssociateMemberAccountCommandInput, AssociateMemberAccountCommandOutput, MacieClientResolvedConfig> {
            readonly input: AssociateMemberAccountCommandInput;
            constructor(input: AssociateMemberAccountCommandInput);
            /**
                * @internal
                */
            resolveMiddleware(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: MacieClientResolvedConfig, options?: __HttpHandlerOptions): Handler<AssociateMemberAccountCommandInput, AssociateMemberAccountCommandOutput>;
    }
}

declare module '@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/AssociateS3ResourcesCommand' {
    import { Command as $Command } from "@aws-sdk/smithy-client";
    import { Handler, HttpHandlerOptions as __HttpHandlerOptions, MetadataBearer as __MetadataBearer, MiddlewareStack } from "@aws-sdk/types";
    import { MacieClientResolvedConfig, ServiceInputTypes, ServiceOutputTypes } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/MacieClient";
    import { AssociateS3ResourcesRequest, AssociateS3ResourcesResult } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/models/models_0";
    export interface AssociateS3ResourcesCommandInput extends AssociateS3ResourcesRequest {
    }
    export interface AssociateS3ResourcesCommandOutput extends AssociateS3ResourcesResult, __MetadataBearer {
    }
    /**
        * <p>(Discontinued) Associates specified S3 resources with Amazon Macie Classic for
        *       monitoring and data classification. If <code>memberAccountId</code> isn't specified, the action associates
        *       specified S3 resources with Macie Classic for the current Macie Classic administrator account.
        *       If <code>memberAccountId</code> is specified, the action associates specified S3 resources with Macie
        *       Classic for the specified member account.</p>
        * @example
        * Use a bare-bones client and the command you need to make an API call.
        * ```javascript
        * import { MacieClient, AssociateS3ResourcesCommand } from "@aws-sdk/client-macie"; // ES Modules import
        * // const { MacieClient, AssociateS3ResourcesCommand } = require("@aws-sdk/client-macie"); // CommonJS import
        * const client = new MacieClient(config);
        * const command = new AssociateS3ResourcesCommand(input);
        * const response = await client.send(command);
        * ```
        *
        * @see {@link AssociateS3ResourcesCommandInput} for command's `input` shape.
        * @see {@link AssociateS3ResourcesCommandOutput} for command's `response` shape.
        * @see {@link MacieClientResolvedConfig | config} for MacieClient's `config` shape.
        *
        */
    export class AssociateS3ResourcesCommand extends $Command<AssociateS3ResourcesCommandInput, AssociateS3ResourcesCommandOutput, MacieClientResolvedConfig> {
            readonly input: AssociateS3ResourcesCommandInput;
            constructor(input: AssociateS3ResourcesCommandInput);
            /**
                * @internal
                */
            resolveMiddleware(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: MacieClientResolvedConfig, options?: __HttpHandlerOptions): Handler<AssociateS3ResourcesCommandInput, AssociateS3ResourcesCommandOutput>;
    }
}

declare module '@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/DisassociateMemberAccountCommand' {
    import { Command as $Command } from "@aws-sdk/smithy-client";
    import { Handler, HttpHandlerOptions as __HttpHandlerOptions, MetadataBearer as __MetadataBearer, MiddlewareStack } from "@aws-sdk/types";
    import { MacieClientResolvedConfig, ServiceInputTypes, ServiceOutputTypes } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/MacieClient";
    import { DisassociateMemberAccountRequest } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/models/models_0";
    export interface DisassociateMemberAccountCommandInput extends DisassociateMemberAccountRequest {
    }
    export interface DisassociateMemberAccountCommandOutput extends __MetadataBearer {
    }
    /**
        * <p>(Discontinued) Removes the specified member account from Amazon Macie
        *       Classic.</p>
        * @example
        * Use a bare-bones client and the command you need to make an API call.
        * ```javascript
        * import { MacieClient, DisassociateMemberAccountCommand } from "@aws-sdk/client-macie"; // ES Modules import
        * // const { MacieClient, DisassociateMemberAccountCommand } = require("@aws-sdk/client-macie"); // CommonJS import
        * const client = new MacieClient(config);
        * const command = new DisassociateMemberAccountCommand(input);
        * const response = await client.send(command);
        * ```
        *
        * @see {@link DisassociateMemberAccountCommandInput} for command's `input` shape.
        * @see {@link DisassociateMemberAccountCommandOutput} for command's `response` shape.
        * @see {@link MacieClientResolvedConfig | config} for MacieClient's `config` shape.
        *
        */
    export class DisassociateMemberAccountCommand extends $Command<DisassociateMemberAccountCommandInput, DisassociateMemberAccountCommandOutput, MacieClientResolvedConfig> {
            readonly input: DisassociateMemberAccountCommandInput;
            constructor(input: DisassociateMemberAccountCommandInput);
            /**
                * @internal
                */
            resolveMiddleware(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: MacieClientResolvedConfig, options?: __HttpHandlerOptions): Handler<DisassociateMemberAccountCommandInput, DisassociateMemberAccountCommandOutput>;
    }
}

declare module '@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/DisassociateS3ResourcesCommand' {
    import { Command as $Command } from "@aws-sdk/smithy-client";
    import { Handler, HttpHandlerOptions as __HttpHandlerOptions, MetadataBearer as __MetadataBearer, MiddlewareStack } from "@aws-sdk/types";
    import { MacieClientResolvedConfig, ServiceInputTypes, ServiceOutputTypes } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/MacieClient";
    import { DisassociateS3ResourcesRequest, DisassociateS3ResourcesResult } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/models/models_0";
    export interface DisassociateS3ResourcesCommandInput extends DisassociateS3ResourcesRequest {
    }
    export interface DisassociateS3ResourcesCommandOutput extends DisassociateS3ResourcesResult, __MetadataBearer {
    }
    /**
        * <p>(Discontinued) Removes specified S3 resources from being monitored by Amazon Macie
        *       Classic. If <code>memberAccountId</code> isn't specified, the action removes specified S3 resources from
        *       Macie Classic for the current Macie Classic administrator account. If <code>memberAccountId</code> is
        *       specified, the action removes specified S3 resources from Macie Classic for the specified
        *       member account.</p>
        * @example
        * Use a bare-bones client and the command you need to make an API call.
        * ```javascript
        * import { MacieClient, DisassociateS3ResourcesCommand } from "@aws-sdk/client-macie"; // ES Modules import
        * // const { MacieClient, DisassociateS3ResourcesCommand } = require("@aws-sdk/client-macie"); // CommonJS import
        * const client = new MacieClient(config);
        * const command = new DisassociateS3ResourcesCommand(input);
        * const response = await client.send(command);
        * ```
        *
        * @see {@link DisassociateS3ResourcesCommandInput} for command's `input` shape.
        * @see {@link DisassociateS3ResourcesCommandOutput} for command's `response` shape.
        * @see {@link MacieClientResolvedConfig | config} for MacieClient's `config` shape.
        *
        */
    export class DisassociateS3ResourcesCommand extends $Command<DisassociateS3ResourcesCommandInput, DisassociateS3ResourcesCommandOutput, MacieClientResolvedConfig> {
            readonly input: DisassociateS3ResourcesCommandInput;
            constructor(input: DisassociateS3ResourcesCommandInput);
            /**
                * @internal
                */
            resolveMiddleware(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: MacieClientResolvedConfig, options?: __HttpHandlerOptions): Handler<DisassociateS3ResourcesCommandInput, DisassociateS3ResourcesCommandOutput>;
    }
}

declare module '@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/ListMemberAccountsCommand' {
    import { Command as $Command } from "@aws-sdk/smithy-client";
    import { Handler, HttpHandlerOptions as __HttpHandlerOptions, MetadataBearer as __MetadataBearer, MiddlewareStack } from "@aws-sdk/types";
    import { MacieClientResolvedConfig, ServiceInputTypes, ServiceOutputTypes } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/MacieClient";
    import { ListMemberAccountsRequest, ListMemberAccountsResult } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/models/models_0";
    export interface ListMemberAccountsCommandInput extends ListMemberAccountsRequest {
    }
    export interface ListMemberAccountsCommandOutput extends ListMemberAccountsResult, __MetadataBearer {
    }
    /**
        * <p>(Discontinued) Lists all Amazon Macie Classic member accounts for the current Macie
        *       Classic administrator account.</p>
        * @example
        * Use a bare-bones client and the command you need to make an API call.
        * ```javascript
        * import { MacieClient, ListMemberAccountsCommand } from "@aws-sdk/client-macie"; // ES Modules import
        * // const { MacieClient, ListMemberAccountsCommand } = require("@aws-sdk/client-macie"); // CommonJS import
        * const client = new MacieClient(config);
        * const command = new ListMemberAccountsCommand(input);
        * const response = await client.send(command);
        * ```
        *
        * @see {@link ListMemberAccountsCommandInput} for command's `input` shape.
        * @see {@link ListMemberAccountsCommandOutput} for command's `response` shape.
        * @see {@link MacieClientResolvedConfig | config} for MacieClient's `config` shape.
        *
        */
    export class ListMemberAccountsCommand extends $Command<ListMemberAccountsCommandInput, ListMemberAccountsCommandOutput, MacieClientResolvedConfig> {
            readonly input: ListMemberAccountsCommandInput;
            constructor(input: ListMemberAccountsCommandInput);
            /**
                * @internal
                */
            resolveMiddleware(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: MacieClientResolvedConfig, options?: __HttpHandlerOptions): Handler<ListMemberAccountsCommandInput, ListMemberAccountsCommandOutput>;
    }
}

declare module '@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/ListS3ResourcesCommand' {
    import { Command as $Command } from "@aws-sdk/smithy-client";
    import { Handler, HttpHandlerOptions as __HttpHandlerOptions, MetadataBearer as __MetadataBearer, MiddlewareStack } from "@aws-sdk/types";
    import { MacieClientResolvedConfig, ServiceInputTypes, ServiceOutputTypes } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/MacieClient";
    import { ListS3ResourcesRequest, ListS3ResourcesResult } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/models/models_0";
    export interface ListS3ResourcesCommandInput extends ListS3ResourcesRequest {
    }
    export interface ListS3ResourcesCommandOutput extends ListS3ResourcesResult, __MetadataBearer {
    }
    /**
        * <p>(Discontinued) Lists all the S3 resources associated with Amazon Macie Classic. If
        *       <code>memberAccountId</code> isn't specified, the action lists the S3 resources associated with Macie
        *       Classic for the current Macie Classic administrator account. If <code>memberAccountId</code> is specified,
        *       the action lists the S3 resources associated with Macie Classic for the specified member
        *       account. </p>
        * @example
        * Use a bare-bones client and the command you need to make an API call.
        * ```javascript
        * import { MacieClient, ListS3ResourcesCommand } from "@aws-sdk/client-macie"; // ES Modules import
        * // const { MacieClient, ListS3ResourcesCommand } = require("@aws-sdk/client-macie"); // CommonJS import
        * const client = new MacieClient(config);
        * const command = new ListS3ResourcesCommand(input);
        * const response = await client.send(command);
        * ```
        *
        * @see {@link ListS3ResourcesCommandInput} for command's `input` shape.
        * @see {@link ListS3ResourcesCommandOutput} for command's `response` shape.
        * @see {@link MacieClientResolvedConfig | config} for MacieClient's `config` shape.
        *
        */
    export class ListS3ResourcesCommand extends $Command<ListS3ResourcesCommandInput, ListS3ResourcesCommandOutput, MacieClientResolvedConfig> {
            readonly input: ListS3ResourcesCommandInput;
            constructor(input: ListS3ResourcesCommandInput);
            /**
                * @internal
                */
            resolveMiddleware(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: MacieClientResolvedConfig, options?: __HttpHandlerOptions): Handler<ListS3ResourcesCommandInput, ListS3ResourcesCommandOutput>;
    }
}

declare module '@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/UpdateS3ResourcesCommand' {
    import { Command as $Command } from "@aws-sdk/smithy-client";
    import { Handler, HttpHandlerOptions as __HttpHandlerOptions, MetadataBearer as __MetadataBearer, MiddlewareStack } from "@aws-sdk/types";
    import { MacieClientResolvedConfig, ServiceInputTypes, ServiceOutputTypes } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/MacieClient";
    import { UpdateS3ResourcesRequest, UpdateS3ResourcesResult } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/models/models_0";
    export interface UpdateS3ResourcesCommandInput extends UpdateS3ResourcesRequest {
    }
    export interface UpdateS3ResourcesCommandOutput extends UpdateS3ResourcesResult, __MetadataBearer {
    }
    /**
        * <p>(Discontinued) Updates the classification types for the specified S3 resources. If
        *       <code>memberAccountId</code> isn't specified, the action updates the classification types of the S3
        *       resources associated with Amazon Macie Classic for the current Macie Classic administrator
        *       account. If <code>memberAccountId</code> is specified, the action updates the classification types of the
        *       S3 resources associated with Macie Classic for the specified member account.</p>
        * @example
        * Use a bare-bones client and the command you need to make an API call.
        * ```javascript
        * import { MacieClient, UpdateS3ResourcesCommand } from "@aws-sdk/client-macie"; // ES Modules import
        * // const { MacieClient, UpdateS3ResourcesCommand } = require("@aws-sdk/client-macie"); // CommonJS import
        * const client = new MacieClient(config);
        * const command = new UpdateS3ResourcesCommand(input);
        * const response = await client.send(command);
        * ```
        *
        * @see {@link UpdateS3ResourcesCommandInput} for command's `input` shape.
        * @see {@link UpdateS3ResourcesCommandOutput} for command's `response` shape.
        * @see {@link MacieClientResolvedConfig | config} for MacieClient's `config` shape.
        *
        */
    export class UpdateS3ResourcesCommand extends $Command<UpdateS3ResourcesCommandInput, UpdateS3ResourcesCommandOutput, MacieClientResolvedConfig> {
            readonly input: UpdateS3ResourcesCommandInput;
            constructor(input: UpdateS3ResourcesCommandInput);
            /**
                * @internal
                */
            resolveMiddleware(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: MacieClientResolvedConfig, options?: __HttpHandlerOptions): Handler<UpdateS3ResourcesCommandInput, UpdateS3ResourcesCommandOutput>;
    }
}

declare module '@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/MacieClient' {
    import { EndpointsInputConfig, EndpointsResolvedConfig, RegionInputConfig, RegionResolvedConfig } from "@aws-sdk/config-resolver";
    import { HostHeaderInputConfig, HostHeaderResolvedConfig } from "@aws-sdk/middleware-host-header";
    import { RetryInputConfig, RetryResolvedConfig } from "@aws-sdk/middleware-retry";
    import { AwsAuthInputConfig, AwsAuthResolvedConfig } from "@aws-sdk/middleware-signing";
    import { UserAgentInputConfig, UserAgentResolvedConfig } from "@aws-sdk/middleware-user-agent";
    import { HttpHandler as __HttpHandler } from "@aws-sdk/protocol-http";
    import { Client as __Client, DefaultsMode, SmithyConfiguration as __SmithyConfiguration, SmithyResolvedConfiguration as __SmithyResolvedConfiguration } from "@aws-sdk/smithy-client";
    import { BodyLengthCalculator as __BodyLengthCalculator, Credentials as __Credentials, Decoder as __Decoder, Encoder as __Encoder, HashConstructor as __HashConstructor, HttpHandlerOptions as __HttpHandlerOptions, Logger as __Logger, Provider as __Provider, Provider, RegionInfoProvider, StreamCollector as __StreamCollector, UrlParser as __UrlParser, UserAgent as __UserAgent } from "@aws-sdk/types";
    import { AssociateMemberAccountCommandInput, AssociateMemberAccountCommandOutput } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/AssociateMemberAccountCommand";
    import { AssociateS3ResourcesCommandInput, AssociateS3ResourcesCommandOutput } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/AssociateS3ResourcesCommand";
    import { DisassociateMemberAccountCommandInput, DisassociateMemberAccountCommandOutput } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/DisassociateMemberAccountCommand";
    import { DisassociateS3ResourcesCommandInput, DisassociateS3ResourcesCommandOutput } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/DisassociateS3ResourcesCommand";
    import { ListMemberAccountsCommandInput, ListMemberAccountsCommandOutput } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/ListMemberAccountsCommand";
    import { ListS3ResourcesCommandInput, ListS3ResourcesCommandOutput } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/ListS3ResourcesCommand";
    import { UpdateS3ResourcesCommandInput, UpdateS3ResourcesCommandOutput } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/commands/UpdateS3ResourcesCommand";
    export type ServiceInputTypes = AssociateMemberAccountCommandInput | AssociateS3ResourcesCommandInput | DisassociateMemberAccountCommandInput | DisassociateS3ResourcesCommandInput | ListMemberAccountsCommandInput | ListS3ResourcesCommandInput | UpdateS3ResourcesCommandInput;
    export type ServiceOutputTypes = AssociateMemberAccountCommandOutput | AssociateS3ResourcesCommandOutput | DisassociateMemberAccountCommandOutput | DisassociateS3ResourcesCommandOutput | ListMemberAccountsCommandOutput | ListS3ResourcesCommandOutput | UpdateS3ResourcesCommandOutput;
    export interface ClientDefaults extends Partial<__SmithyResolvedConfiguration<__HttpHandlerOptions>> {
            /**
                * The HTTP handler to use. Fetch in browser and Https in Nodejs.
                */
            requestHandler?: __HttpHandler;
            /**
                * A constructor for a class implementing the {@link __Hash} interface
                * that computes the SHA-256 HMAC or checksum of a string or binary buffer.
                * @internal
                */
            sha256?: __HashConstructor;
            /**
                * The function that will be used to convert strings into HTTP endpoints.
                * @internal
                */
            urlParser?: __UrlParser;
            /**
                * A function that can calculate the length of a request body.
                * @internal
                */
            bodyLengthChecker?: __BodyLengthCalculator;
            /**
                * A function that converts a stream into an array of bytes.
                * @internal
                */
            streamCollector?: __StreamCollector;
            /**
                * The function that will be used to convert a base64-encoded string to a byte array.
                * @internal
                */
            base64Decoder?: __Decoder;
            /**
                * The function that will be used to convert binary data to a base64-encoded string.
                * @internal
                */
            base64Encoder?: __Encoder;
            /**
                * The function that will be used to convert a UTF8-encoded string to a byte array.
                * @internal
                */
            utf8Decoder?: __Decoder;
            /**
                * The function that will be used to convert binary data to a UTF-8 encoded string.
                * @internal
                */
            utf8Encoder?: __Encoder;
            /**
                * The runtime environment.
                * @internal
                */
            runtime?: string;
            /**
                * Disable dyanamically changing the endpoint of the client based on the hostPrefix
                * trait of an operation.
                */
            disableHostPrefix?: boolean;
            /**
                * Value for how many times a request will be made at most in case of retry.
                */
            maxAttempts?: number | __Provider<number>;
            /**
                * Specifies which retry algorithm to use.
                */
            retryMode?: string | __Provider<string>;
            /**
                * Optional logger for logging debug/info/warn/error.
                */
            logger?: __Logger;
            /**
                * Enables IPv6/IPv4 dualstack endpoint.
                */
            useDualstackEndpoint?: boolean | __Provider<boolean>;
            /**
                * Enables FIPS compatible endpoints.
                */
            useFipsEndpoint?: boolean | __Provider<boolean>;
            /**
                * Unique service identifier.
                * @internal
                */
            serviceId?: string;
            /**
                * The AWS region to which this client will send requests
                */
            region?: string | __Provider<string>;
            /**
                * Default credentials provider; Not available in browser runtime.
                * @internal
                */
            credentialDefaultProvider?: (input: any) => __Provider<__Credentials>;
            /**
                * Fetch related hostname, signing name or signing region with given region.
                * @internal
                */
            regionInfoProvider?: RegionInfoProvider;
            /**
                * The provider populating default tracking information to be sent with `user-agent`, `x-amz-user-agent` header
                * @internal
                */
            defaultUserAgentProvider?: Provider<__UserAgent>;
            /**
                * The {@link DefaultsMode} that will be used to determine how certain default configuration options are resolved in the SDK.
                */
            defaultsMode?: DefaultsMode | Provider<DefaultsMode>;
    }
    type MacieClientConfigType = Partial<__SmithyConfiguration<__HttpHandlerOptions>> & ClientDefaults & RegionInputConfig & EndpointsInputConfig & RetryInputConfig & HostHeaderInputConfig & AwsAuthInputConfig & UserAgentInputConfig;
    /**
        * The configuration interface of MacieClient class constructor that set the region, credentials and other options.
        */
    export interface MacieClientConfig extends MacieClientConfigType {
    }
    type MacieClientResolvedConfigType = __SmithyResolvedConfiguration<__HttpHandlerOptions> & Required<ClientDefaults> & RegionResolvedConfig & EndpointsResolvedConfig & RetryResolvedConfig & HostHeaderResolvedConfig & AwsAuthResolvedConfig & UserAgentResolvedConfig;
    /**
        * The resolved configuration interface of MacieClient class. This is resolved and normalized from the {@link MacieClientConfig | constructor configuration interface}.
        */
    export interface MacieClientResolvedConfig extends MacieClientResolvedConfigType {
    }
    /**
        * <fullname>Amazon Macie Classic</fullname>
        *          <p>Amazon Macie Classic has been discontinued and is no longer available.</p>
        *
        *          <p>A new Amazon Macie is now available with significant design improvements and additional
        *       features, at a lower price and in most Amazon Web Services Regions. We encourage you to take advantage of the
        *       new and improved features, and benefit from the reduced cost. To learn about features and pricing for the new Macie, see <a href="http://aws.amazon.com/macie/">Amazon Macie</a>. To learn how to use the new Macie, see the <a href="https://docs.aws.amazon.com/macie/latest/user/what-is-macie.html">Amazon Macie User
        *         Guide</a>.</p>
        */
    export class MacieClient extends __Client<__HttpHandlerOptions, ServiceInputTypes, ServiceOutputTypes, MacieClientResolvedConfig> {
            /**
                * The resolved configuration of MacieClient class. This is resolved and normalized from the {@link MacieClientConfig | constructor configuration interface}.
                */
            readonly config: MacieClientResolvedConfig;
            constructor(configuration: MacieClientConfig);
            /**
                * Destroy underlying resources, like sockets. It's usually not necessary to do this.
                * However in Node.js, it's best to explicitly shut down the client's agent when it is no longer needed.
                * Otherwise, sockets might stay open for quite a long time before the server terminates them.
                */
            destroy(): void;
    }
    export {};
}

declare module '@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/models/models_0' {
    import { ExceptionOptionType as __ExceptionOptionType } from "@aws-sdk/smithy-client";
    import { MacieServiceException as __BaseException } from "@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/models/MacieServiceException";
    /**
        * <p>(Discontinued) You do not have required permissions to access the requested resource.</p>
        */
    export class AccessDeniedException extends __BaseException {
            readonly name: "AccessDeniedException";
            readonly $fault: "client";
            /**
                * Resource type that caused the exception
                */
            resourceType?: string;
            /**
                * @internal
                */
            constructor(opts: __ExceptionOptionType<AccessDeniedException, __BaseException>);
    }
    export interface AssociateMemberAccountRequest {
            /**
                * <p>(Discontinued) The ID of the Amazon Web Services account that you want to associate with Amazon Macie
                *       Classic as a member account.</p>
                */
            memberAccountId: string | undefined;
    }
    export namespace AssociateMemberAccountRequest {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: AssociateMemberAccountRequest) => any;
    }
    /**
        * <p>(Discontinued) Internal server error.</p>
        */
    export class InternalException extends __BaseException {
            readonly name: "InternalException";
            readonly $fault: "server";
            /**
                * Error code for the exception
                */
            errorCode?: string;
            /**
                * @internal
                */
            constructor(opts: __ExceptionOptionType<InternalException, __BaseException>);
    }
    /**
        * <p>(Discontinued) The request was rejected because an invalid or out-of-range value was supplied for an
        *       input parameter.</p>
        */
    export class InvalidInputException extends __BaseException {
            readonly name: "InvalidInputException";
            readonly $fault: "client";
            /**
                * Error code for the exception
                */
            errorCode?: string;
            /**
                * Field that has invalid input
                */
            fieldName?: string;
            /**
                * @internal
                */
            constructor(opts: __ExceptionOptionType<InvalidInputException, __BaseException>);
    }
    /**
        * <p>(Discontinued) The request was rejected because it attempted to create resources beyond the current
        *       Amazon Web Services account quotas. The error code describes the quota exceeded.</p>
        */
    export class LimitExceededException extends __BaseException {
            readonly name: "LimitExceededException";
            readonly $fault: "client";
            /**
                * Error code for the exception
                */
            errorCode?: string;
            /**
                * Resource type that caused the exception
                */
            resourceType?: string;
            /**
                * @internal
                */
            constructor(opts: __ExceptionOptionType<LimitExceededException, __BaseException>);
    }
    export enum S3ContinuousClassificationType {
            FULL = "FULL"
    }
    export enum S3OneTimeClassificationType {
            FULL = "FULL",
            NONE = "NONE"
    }
    /**
        * <p>(Discontinued) The classification type that Amazon Macie Classic applies to the
        *       associated S3 resources.</p>
        */
    export interface ClassificationType {
            /**
                * <p>(Discontinued) A one-time classification of all of the existing objects in a specified
                *       S3 bucket. </p>
                */
            oneTime: S3OneTimeClassificationType | string | undefined;
            /**
                * <p>(Discontinued) A continuous classification of the objects that are added to a specified
                *       S3 bucket. Amazon Macie Classic begins performing continuous classification after a bucket is
                *       successfully associated with Macie Classic.</p>
                */
            continuous: S3ContinuousClassificationType | string | undefined;
    }
    export namespace ClassificationType {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: ClassificationType) => any;
    }
    /**
        * <p>(Discontinued) The S3 resources that you want to associate with Amazon Macie Classic
        *       for monitoring and data classification. This data type is used as a request parameter in the
        *       <code>AssociateS3Resources</code> action and a response parameter in the <code>ListS3Resources</code> action. </p>
        */
    export interface S3ResourceClassification {
            /**
                * <p>(Discontinued) The name of the S3 bucket that you want to associate with Amazon Macie
                *       Classic.</p>
                */
            bucketName: string | undefined;
            /**
                * <p>(Discontinued) The prefix of the S3 bucket that you want to associate with Amazon Macie
                *       Classic.</p>
                */
            prefix?: string;
            /**
                * <p>(Discontinued) The classification type that you want to specify for the resource
                *       associated with Amazon Macie Classic. </p>
                */
            classificationType: ClassificationType | undefined;
    }
    export namespace S3ResourceClassification {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: S3ResourceClassification) => any;
    }
    export interface AssociateS3ResourcesRequest {
            /**
                * <p>(Discontinued) The ID of the Amazon Macie Classic member account whose resources you
                *       want to associate with Macie Classic.</p>
                */
            memberAccountId?: string;
            /**
                * <p>(Discontinued) The S3 resources that you want to associate with Amazon Macie Classic
                *       for monitoring and data classification.</p>
                */
            s3Resources: S3ResourceClassification[] | undefined;
    }
    export namespace AssociateS3ResourcesRequest {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: AssociateS3ResourcesRequest) => any;
    }
    /**
        * <p>(Discontinued) Contains information about the S3 resource. This data type is used as a
        *       request parameter in the <code>DisassociateS3Resources</code> action and can be used as a response
        *       parameter in the <code>AssociateS3Resources</code> and <code>UpdateS3Resources</code> actions. </p>
        */
    export interface S3Resource {
            /**
                * <p>(Discontinued) The name of the S3 bucket.</p>
                */
            bucketName: string | undefined;
            /**
                * <p>(Discontinued) The prefix of the S3 bucket.</p>
                */
            prefix?: string;
    }
    export namespace S3Resource {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: S3Resource) => any;
    }
    /**
        * <p>(Discontinued) Includes details about the failed S3 resources.</p>
        */
    export interface FailedS3Resource {
            /**
                * <p>(Discontinued) The failed S3 resources.</p>
                */
            failedItem?: S3Resource;
            /**
                * <p>(Discontinued) The status code of a failed item.</p>
                */
            errorCode?: string;
            /**
                * <p>(Discontinued) The error message of a failed item.</p>
                */
            errorMessage?: string;
    }
    export namespace FailedS3Resource {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: FailedS3Resource) => any;
    }
    export interface AssociateS3ResourcesResult {
            /**
                * <p>(Discontinued) S3 resources that couldn't be associated with Amazon Macie Classic. An
                *       error code and an error message are provided for each failed item.</p>
                */
            failedS3Resources?: FailedS3Resource[];
    }
    export namespace AssociateS3ResourcesResult {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: AssociateS3ResourcesResult) => any;
    }
    /**
        * <p>(Discontinued) The classification type that Amazon Macie Classic applies to the
        *       associated S3 resources. At least one of the classification types (<code>oneTime</code> or <code>continuous</code>) must
        *       be specified. </p>
        */
    export interface ClassificationTypeUpdate {
            /**
                * <p>(Discontinued) A one-time classification of all of the existing objects in a specified
                *       S3 bucket. </p>
                */
            oneTime?: S3OneTimeClassificationType | string;
            /**
                * <p>(Discontinued) A continuous classification of the objects that are added to a specified
                *       S3 bucket. Amazon Macie Classic begins performing continuous classification after a bucket is
                *       successfully associated with Macie Classic. </p>
                */
            continuous?: S3ContinuousClassificationType | string;
    }
    export namespace ClassificationTypeUpdate {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: ClassificationTypeUpdate) => any;
    }
    export interface DisassociateMemberAccountRequest {
            /**
                * <p>(Discontinued) The ID of the member account that you want to remove from Amazon Macie
                *       Classic.</p>
                */
            memberAccountId: string | undefined;
    }
    export namespace DisassociateMemberAccountRequest {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: DisassociateMemberAccountRequest) => any;
    }
    export interface DisassociateS3ResourcesRequest {
            /**
                * <p>(Discontinued) The ID of the Amazon Macie Classic member account whose resources you
                *       want to remove from being monitored by Macie Classic.</p>
                */
            memberAccountId?: string;
            /**
                * <p>(Discontinued) The S3 resources (buckets or prefixes) that you want to remove from
                *       being monitored and classified by Amazon Macie Classic.</p>
                */
            associatedS3Resources: S3Resource[] | undefined;
    }
    export namespace DisassociateS3ResourcesRequest {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: DisassociateS3ResourcesRequest) => any;
    }
    export interface DisassociateS3ResourcesResult {
            /**
                * <p>(Discontinued) S3 resources that couldn't be removed from being monitored and
                *       classified by Amazon Macie Classic. An error code and an error message are provided for each
                *       failed item. </p>
                */
            failedS3Resources?: FailedS3Resource[];
    }
    export namespace DisassociateS3ResourcesResult {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: DisassociateS3ResourcesResult) => any;
    }
    export interface ListMemberAccountsRequest {
            /**
                * <p>(Discontinued) Use this parameter when paginating results. Set the value of this
                *       parameter to null on your first call to the <code>ListMemberAccounts</code> action. Subsequent calls to the
                *       action fill <code>nextToken</code> in the request with the value of <code>nextToken</code> from the previous response to
                *       continue listing data.</p>
                */
            nextToken?: string;
            /**
                * <p>(Discontinued) Use this parameter to indicate the maximum number of items that you want
                *       in the response. The default value is 250.</p>
                */
            maxResults?: number;
    }
    export namespace ListMemberAccountsRequest {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: ListMemberAccountsRequest) => any;
    }
    /**
        * <p>(Discontinued) Contains information about the Amazon Macie Classic member
        *       account.</p>
        */
    export interface MemberAccount {
            /**
                * <p>(Discontinued) The Amazon Web Services account ID of the Amazon Macie Classic member account.</p>
                */
            accountId?: string;
    }
    export namespace MemberAccount {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: MemberAccount) => any;
    }
    export interface ListMemberAccountsResult {
            /**
                * <p>(Discontinued) A list of the Amazon Macie Classic member accounts returned by the
                *       action. The current Macie Classic administrator account is also included in this
                *       list.</p>
                */
            memberAccounts?: MemberAccount[];
            /**
                * <p>(Discontinued) When a response is generated, if there is more data to be listed, this
                *       parameter is present in the response and contains the value to use for the <code>nextToken</code> parameter
                *       in a subsequent pagination request. If there is no more data to be listed, this parameter is
                *       set to null. </p>
                */
            nextToken?: string;
    }
    export namespace ListMemberAccountsResult {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: ListMemberAccountsResult) => any;
    }
    export interface ListS3ResourcesRequest {
            /**
                * <p>(Discontinued) The Amazon Macie Classic member account ID whose associated S3 resources
                *       you want to list. </p>
                */
            memberAccountId?: string;
            /**
                * <p>(Discontinued) Use this parameter when paginating results. Set its value to null on
                *       your first call to the <code>ListS3Resources</code> action. Subsequent calls to the action fill <code>nextToken</code>
                *       in the request with the value of <code>nextToken</code> from the previous response to continue listing
                *       data. </p>
                */
            nextToken?: string;
            /**
                * <p>(Discontinued) Use this parameter to indicate the maximum number of items that you want
                *       in the response. The default value is 250. </p>
                */
            maxResults?: number;
    }
    export namespace ListS3ResourcesRequest {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: ListS3ResourcesRequest) => any;
    }
    export interface ListS3ResourcesResult {
            /**
                * <p>(Discontinued) A list of the associated S3 resources returned by the action.</p>
                */
            s3Resources?: S3ResourceClassification[];
            /**
                * <p>(Discontinued) When a response is generated, if there is more data to be listed, this
                *       parameter is present in the response and contains the value to use for the <code>nextToken</code> parameter
                *       in a subsequent pagination request. If there is no more data to be listed, this parameter is
                *       set to null. </p>
                */
            nextToken?: string;
    }
    export namespace ListS3ResourcesResult {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: ListS3ResourcesResult) => any;
    }
    /**
        * <p>(Discontinued) The S3 resources whose classification types you want to update. This
        *       data type is used as a request parameter in the <code>UpdateS3Resources</code> action. </p>
        */
    export interface S3ResourceClassificationUpdate {
            /**
                * <p>(Discontinued) The name of the S3 bucket whose classification types you want to
                *       update.</p>
                */
            bucketName: string | undefined;
            /**
                * <p>(Discontinued) The prefix of the S3 bucket whose classification types you want to
                *       update.</p>
                */
            prefix?: string;
            /**
                * <p>(Discontinued) The classification type that you want to update for the resource
                *       associated with Amazon Macie Classic. </p>
                */
            classificationTypeUpdate: ClassificationTypeUpdate | undefined;
    }
    export namespace S3ResourceClassificationUpdate {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: S3ResourceClassificationUpdate) => any;
    }
    export interface UpdateS3ResourcesRequest {
            /**
                * <p>(Discontinued) The Amazon Web Services account ID of the Amazon Macie Classic member account whose S3
                *       resources' classification types you want to update.</p>
                */
            memberAccountId?: string;
            /**
                * <p>(Discontinued) The S3 resources whose classification types you want to
                *       update.</p>
                */
            s3ResourcesUpdate: S3ResourceClassificationUpdate[] | undefined;
    }
    export namespace UpdateS3ResourcesRequest {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: UpdateS3ResourcesRequest) => any;
    }
    export interface UpdateS3ResourcesResult {
            /**
                * <p>(Discontinued) The S3 resources whose classification types can't be updated. An error
                *       code and an error message are provided for each failed item.</p>
                */
            failedS3Resources?: FailedS3Resource[];
    }
    export namespace UpdateS3ResourcesResult {
            /**
                * @internal
                */
            const filterSensitiveLog: (obj: UpdateS3ResourcesResult) => any;
    }
}

declare module '@aws-sdk/client-macie/node_modules/@aws-sdk/client-macie/dist-types/models/MacieServiceException' {
    import { ServiceException as __ServiceException, ServiceExceptionOptions as __ServiceExceptionOptions } from "@aws-sdk/smithy-client";
    /**
        * Base exception class for all service exceptions from Macie service.
        */
    export class MacieServiceException extends __ServiceException {
            /**
                * @internal
                */
            constructor(options: __ServiceExceptionOptions);
    }
}

