import { AddPermissionCommandInput, AddPermissionCommandOutput } from "@aws-sdk/client-sqs";
import { ChangeMessageVisibilityCommandInput, ChangeMessageVisibilityCommandOutput } from "@aws-sdk/client-sqs";
import { ChangeMessageVisibilityBatchCommandInput, ChangeMessageVisibilityBatchCommandOutput } from "@aws-sdk/client-sqs";
import { CreateQueueCommandInput, CreateQueueCommandOutput } from "@aws-sdk/client-sqs";
import { DeleteMessageCommandInput, DeleteMessageCommandOutput } from "@aws-sdk/client-sqs";
import { DeleteMessageBatchCommandInput, DeleteMessageBatchCommandOutput } from "@aws-sdk/client-sqs";
import { DeleteQueueCommandInput, DeleteQueueCommandOutput } from "@aws-sdk/client-sqs";
import { GetQueueAttributesCommandInput, GetQueueAttributesCommandOutput } from "@aws-sdk/client-sqs";
import { GetQueueUrlCommandInput, GetQueueUrlCommandOutput } from "@aws-sdk/client-sqs";
import { ListDeadLetterSourceQueuesCommandInput, ListDeadLetterSourceQueuesCommandOutput } from "@aws-sdk/client-sqs";
import { ListQueueTagsCommandInput, ListQueueTagsCommandOutput } from "@aws-sdk/client-sqs";
import { ListQueuesCommandInput, ListQueuesCommandOutput } from "@aws-sdk/client-sqs";
import { PurgeQueueCommandInput, PurgeQueueCommandOutput } from "@aws-sdk/client-sqs";
import { ReceiveMessageCommandInput, ReceiveMessageCommandOutput } from "@aws-sdk/client-sqs";
import { RemovePermissionCommandInput, RemovePermissionCommandOutput } from "@aws-sdk/client-sqs";
import { SendMessageCommandInput, SendMessageCommandOutput } from "@aws-sdk/client-sqs";
import { SendMessageBatchCommandInput, SendMessageBatchCommandOutput } from "@aws-sdk/client-sqs";
import { SetQueueAttributesCommandInput, SetQueueAttributesCommandOutput } from "@aws-sdk/client-sqs";
import { TagQueueCommandInput, TagQueueCommandOutput } from "@aws-sdk/client-sqs";
import { UntagQueueCommandInput, UntagQueueCommandOutput } from "@aws-sdk/client-sqs";
export declare namespace ASL {
    const nativeSQSAddPermission: (input: AddPermissionCommandInput) => Promise<AddPermissionCommandOutput>;
    const nativeSQSChangeMessageVisibility: (input: ChangeMessageVisibilityCommandInput) => Promise<ChangeMessageVisibilityCommandOutput>;
    const nativeSQSChangeMessageVisibilityBatch: (input: ChangeMessageVisibilityBatchCommandInput) => Promise<ChangeMessageVisibilityBatchCommandOutput>;
    const nativeSQSCreateQueue: (input: CreateQueueCommandInput) => Promise<CreateQueueCommandOutput>;
    const nativeSQSDeleteMessage: (input: DeleteMessageCommandInput) => Promise<DeleteMessageCommandOutput>;
    const nativeSQSDeleteMessageBatch: (input: DeleteMessageBatchCommandInput) => Promise<DeleteMessageBatchCommandOutput>;
    const nativeSQSDeleteQueue: (input: DeleteQueueCommandInput) => Promise<DeleteQueueCommandOutput>;
    const nativeSQSGetQueueAttributes: (input: GetQueueAttributesCommandInput) => Promise<GetQueueAttributesCommandOutput>;
    const nativeSQSGetQueueUrl: (input: GetQueueUrlCommandInput) => Promise<GetQueueUrlCommandOutput>;
    const nativeSQSListDeadLetterSourceQueues: (input: ListDeadLetterSourceQueuesCommandInput) => Promise<ListDeadLetterSourceQueuesCommandOutput>;
    const nativeSQSListQueueTags: (input: ListQueueTagsCommandInput) => Promise<ListQueueTagsCommandOutput>;
    const nativeSQSListQueues: (input: ListQueuesCommandInput) => Promise<ListQueuesCommandOutput>;
    const nativeSQSPurgeQueue: (input: PurgeQueueCommandInput) => Promise<PurgeQueueCommandOutput>;
    const nativeSQSReceiveMessage: (input: ReceiveMessageCommandInput) => Promise<ReceiveMessageCommandOutput>;
    const nativeSQSRemovePermission: (input: RemovePermissionCommandInput) => Promise<RemovePermissionCommandOutput>;
    const nativeSQSSendMessage: (input: SendMessageCommandInput) => Promise<SendMessageCommandOutput>;
    const nativeSQSSendMessageBatch: (input: SendMessageBatchCommandInput) => Promise<SendMessageBatchCommandOutput>;
    const nativeSQSSetQueueAttributes: (input: SetQueueAttributesCommandInput) => Promise<SetQueueAttributesCommandOutput>;
    const nativeSQSTagQueue: (input: TagQueueCommandInput) => Promise<TagQueueCommandOutput>;
    const nativeSQSUntagQueue: (input: UntagQueueCommandInput) => Promise<UntagQueueCommandOutput>;
}
