import { AbortMultipartUploadCommandInput, AbortMultipartUploadCommandOutput } from "@aws-sdk/client-s3";
import { CompleteMultipartUploadCommandInput, CompleteMultipartUploadCommandOutput } from "@aws-sdk/client-s3";
import { CopyObjectCommandInput, CopyObjectCommandOutput } from "@aws-sdk/client-s3";
import { CreateBucketCommandInput, CreateBucketCommandOutput } from "@aws-sdk/client-s3";
import { CreateMultipartUploadCommandInput, CreateMultipartUploadCommandOutput } from "@aws-sdk/client-s3";
import { DeleteBucketCommandInput, DeleteBucketCommandOutput } from "@aws-sdk/client-s3";
import { DeleteBucketAnalyticsConfigurationCommandInput, DeleteBucketAnalyticsConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { DeleteBucketCorsCommandInput, DeleteBucketCorsCommandOutput } from "@aws-sdk/client-s3";
import { DeleteBucketEncryptionCommandInput, DeleteBucketEncryptionCommandOutput } from "@aws-sdk/client-s3";
import { DeleteBucketIntelligentTieringConfigurationCommandInput, DeleteBucketIntelligentTieringConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { DeleteBucketInventoryConfigurationCommandInput, DeleteBucketInventoryConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { DeleteBucketLifecycleCommandInput, DeleteBucketLifecycleCommandOutput } from "@aws-sdk/client-s3";
import { DeleteBucketMetricsConfigurationCommandInput, DeleteBucketMetricsConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { DeleteBucketOwnershipControlsCommandInput, DeleteBucketOwnershipControlsCommandOutput } from "@aws-sdk/client-s3";
import { DeleteBucketPolicyCommandInput, DeleteBucketPolicyCommandOutput } from "@aws-sdk/client-s3";
import { DeleteBucketReplicationCommandInput, DeleteBucketReplicationCommandOutput } from "@aws-sdk/client-s3";
import { DeleteBucketTaggingCommandInput, DeleteBucketTaggingCommandOutput } from "@aws-sdk/client-s3";
import { DeleteBucketWebsiteCommandInput, DeleteBucketWebsiteCommandOutput } from "@aws-sdk/client-s3";
import { DeleteObjectCommandInput, DeleteObjectCommandOutput } from "@aws-sdk/client-s3";
import { DeleteObjectTaggingCommandInput, DeleteObjectTaggingCommandOutput } from "@aws-sdk/client-s3";
import { DeleteObjectsCommandInput, DeleteObjectsCommandOutput } from "@aws-sdk/client-s3";
import { DeletePublicAccessBlockCommandInput, DeletePublicAccessBlockCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketAccelerateConfigurationCommandInput, GetBucketAccelerateConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketAclCommandInput, GetBucketAclCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketAnalyticsConfigurationCommandInput, GetBucketAnalyticsConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketCorsCommandInput, GetBucketCorsCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketEncryptionCommandInput, GetBucketEncryptionCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketIntelligentTieringConfigurationCommandInput, GetBucketIntelligentTieringConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketInventoryConfigurationCommandInput, GetBucketInventoryConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketLifecycleConfigurationCommandInput, GetBucketLifecycleConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketLocationCommandInput, GetBucketLocationCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketLoggingCommandInput, GetBucketLoggingCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketMetricsConfigurationCommandInput, GetBucketMetricsConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketNotificationConfigurationCommandInput, GetBucketNotificationConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketOwnershipControlsCommandInput, GetBucketOwnershipControlsCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketPolicyCommandInput, GetBucketPolicyCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketPolicyStatusCommandInput, GetBucketPolicyStatusCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketReplicationCommandInput, GetBucketReplicationCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketRequestPaymentCommandInput, GetBucketRequestPaymentCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketTaggingCommandInput, GetBucketTaggingCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketVersioningCommandInput, GetBucketVersioningCommandOutput } from "@aws-sdk/client-s3";
import { GetBucketWebsiteCommandInput, GetBucketWebsiteCommandOutput } from "@aws-sdk/client-s3";
import { GetObjectCommandInput, GetObjectCommandOutput } from "@aws-sdk/client-s3";
import { GetObjectAclCommandInput, GetObjectAclCommandOutput } from "@aws-sdk/client-s3";
import { GetObjectLegalHoldCommandInput, GetObjectLegalHoldCommandOutput } from "@aws-sdk/client-s3";
import { GetObjectLockConfigurationCommandInput, GetObjectLockConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { GetObjectRetentionCommandInput, GetObjectRetentionCommandOutput } from "@aws-sdk/client-s3";
import { GetObjectTaggingCommandInput, GetObjectTaggingCommandOutput } from "@aws-sdk/client-s3";
import { GetObjectTorrentCommandInput, GetObjectTorrentCommandOutput } from "@aws-sdk/client-s3";
import { GetPublicAccessBlockCommandInput, GetPublicAccessBlockCommandOutput } from "@aws-sdk/client-s3";
import { HeadBucketCommandInput, HeadBucketCommandOutput } from "@aws-sdk/client-s3";
import { HeadObjectCommandInput, HeadObjectCommandOutput } from "@aws-sdk/client-s3";
import { ListBucketAnalyticsConfigurationsCommandInput, ListBucketAnalyticsConfigurationsCommandOutput } from "@aws-sdk/client-s3";
import { ListBucketIntelligentTieringConfigurationsCommandInput, ListBucketIntelligentTieringConfigurationsCommandOutput } from "@aws-sdk/client-s3";
import { ListBucketInventoryConfigurationsCommandInput, ListBucketInventoryConfigurationsCommandOutput } from "@aws-sdk/client-s3";
import { ListBucketMetricsConfigurationsCommandInput, ListBucketMetricsConfigurationsCommandOutput } from "@aws-sdk/client-s3";
import { ListBucketsCommandInput, ListBucketsCommandOutput } from "@aws-sdk/client-s3";
import { ListMultipartUploadsCommandInput, ListMultipartUploadsCommandOutput } from "@aws-sdk/client-s3";
import { ListObjectVersionsCommandInput, ListObjectVersionsCommandOutput } from "@aws-sdk/client-s3";
import { ListObjectsCommandInput, ListObjectsCommandOutput } from "@aws-sdk/client-s3";
import { ListObjectsV2CommandInput, ListObjectsV2CommandOutput } from "@aws-sdk/client-s3";
import { ListPartsCommandInput, ListPartsCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketAccelerateConfigurationCommandInput, PutBucketAccelerateConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketAclCommandInput, PutBucketAclCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketAnalyticsConfigurationCommandInput, PutBucketAnalyticsConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketCorsCommandInput, PutBucketCorsCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketEncryptionCommandInput, PutBucketEncryptionCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketIntelligentTieringConfigurationCommandInput, PutBucketIntelligentTieringConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketInventoryConfigurationCommandInput, PutBucketInventoryConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketLifecycleConfigurationCommandInput, PutBucketLifecycleConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketLoggingCommandInput, PutBucketLoggingCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketMetricsConfigurationCommandInput, PutBucketMetricsConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketNotificationConfigurationCommandInput, PutBucketNotificationConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketOwnershipControlsCommandInput, PutBucketOwnershipControlsCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketPolicyCommandInput, PutBucketPolicyCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketReplicationCommandInput, PutBucketReplicationCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketRequestPaymentCommandInput, PutBucketRequestPaymentCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketTaggingCommandInput, PutBucketTaggingCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketVersioningCommandInput, PutBucketVersioningCommandOutput } from "@aws-sdk/client-s3";
import { PutBucketWebsiteCommandInput, PutBucketWebsiteCommandOutput } from "@aws-sdk/client-s3";
import { PutObjectCommandInput, PutObjectCommandOutput } from "@aws-sdk/client-s3";
import { PutObjectAclCommandInput, PutObjectAclCommandOutput } from "@aws-sdk/client-s3";
import { PutObjectLegalHoldCommandInput, PutObjectLegalHoldCommandOutput } from "@aws-sdk/client-s3";
import { PutObjectLockConfigurationCommandInput, PutObjectLockConfigurationCommandOutput } from "@aws-sdk/client-s3";
import { PutObjectRetentionCommandInput, PutObjectRetentionCommandOutput } from "@aws-sdk/client-s3";
import { PutObjectTaggingCommandInput, PutObjectTaggingCommandOutput } from "@aws-sdk/client-s3";
import { PutPublicAccessBlockCommandInput, PutPublicAccessBlockCommandOutput } from "@aws-sdk/client-s3";
import { RestoreObjectCommandInput, RestoreObjectCommandOutput } from "@aws-sdk/client-s3";
import { UploadPartCommandInput, UploadPartCommandOutput } from "@aws-sdk/client-s3";
import { UploadPartCopyCommandInput, UploadPartCopyCommandOutput } from "@aws-sdk/client-s3";
import { WriteGetObjectResponseCommandInput, WriteGetObjectResponseCommandOutput } from "@aws-sdk/client-s3";
export declare namespace ASL {
    const nativeS3AbortMultipartUpload: (input: AbortMultipartUploadCommandInput) => Promise<AbortMultipartUploadCommandOutput>;
    const nativeS3CompleteMultipartUpload: (input: CompleteMultipartUploadCommandInput) => Promise<CompleteMultipartUploadCommandOutput>;
    const nativeS3CopyObject: (input: CopyObjectCommandInput) => Promise<CopyObjectCommandOutput>;
    const nativeS3CreateBucket: (input: CreateBucketCommandInput) => Promise<CreateBucketCommandOutput>;
    const nativeS3CreateMultipartUpload: (input: CreateMultipartUploadCommandInput) => Promise<CreateMultipartUploadCommandOutput>;
    const nativeS3DeleteBucket: (input: DeleteBucketCommandInput) => Promise<DeleteBucketCommandOutput>;
    const nativeS3DeleteBucketAnalyticsConfiguration: (input: DeleteBucketAnalyticsConfigurationCommandInput) => Promise<DeleteBucketAnalyticsConfigurationCommandOutput>;
    const nativeS3DeleteBucketCors: (input: DeleteBucketCorsCommandInput) => Promise<DeleteBucketCorsCommandOutput>;
    const nativeS3DeleteBucketEncryption: (input: DeleteBucketEncryptionCommandInput) => Promise<DeleteBucketEncryptionCommandOutput>;
    const nativeS3DeleteBucketIntelligentTieringConfiguration: (input: DeleteBucketIntelligentTieringConfigurationCommandInput) => Promise<DeleteBucketIntelligentTieringConfigurationCommandOutput>;
    const nativeS3DeleteBucketInventoryConfiguration: (input: DeleteBucketInventoryConfigurationCommandInput) => Promise<DeleteBucketInventoryConfigurationCommandOutput>;
    const nativeS3DeleteBucketLifecycle: (input: DeleteBucketLifecycleCommandInput) => Promise<DeleteBucketLifecycleCommandOutput>;
    const nativeS3DeleteBucketMetricsConfiguration: (input: DeleteBucketMetricsConfigurationCommandInput) => Promise<DeleteBucketMetricsConfigurationCommandOutput>;
    const nativeS3DeleteBucketOwnershipControls: (input: DeleteBucketOwnershipControlsCommandInput) => Promise<DeleteBucketOwnershipControlsCommandOutput>;
    const nativeS3DeleteBucketPolicy: (input: DeleteBucketPolicyCommandInput) => Promise<DeleteBucketPolicyCommandOutput>;
    const nativeS3DeleteBucketReplication: (input: DeleteBucketReplicationCommandInput) => Promise<DeleteBucketReplicationCommandOutput>;
    const nativeS3DeleteBucketTagging: (input: DeleteBucketTaggingCommandInput) => Promise<DeleteBucketTaggingCommandOutput>;
    const nativeS3DeleteBucketWebsite: (input: DeleteBucketWebsiteCommandInput) => Promise<DeleteBucketWebsiteCommandOutput>;
    const nativeS3DeleteObject: (input: DeleteObjectCommandInput) => Promise<DeleteObjectCommandOutput>;
    const nativeS3DeleteObjectTagging: (input: DeleteObjectTaggingCommandInput) => Promise<DeleteObjectTaggingCommandOutput>;
    const nativeS3DeleteObjects: (input: DeleteObjectsCommandInput) => Promise<DeleteObjectsCommandOutput>;
    const nativeS3DeletePublicAccessBlock: (input: DeletePublicAccessBlockCommandInput) => Promise<DeletePublicAccessBlockCommandOutput>;
    const nativeS3GetBucketAccelerateConfiguration: (input: GetBucketAccelerateConfigurationCommandInput) => Promise<GetBucketAccelerateConfigurationCommandOutput>;
    const nativeS3GetBucketAcl: (input: GetBucketAclCommandInput) => Promise<GetBucketAclCommandOutput>;
    const nativeS3GetBucketAnalyticsConfiguration: (input: GetBucketAnalyticsConfigurationCommandInput) => Promise<GetBucketAnalyticsConfigurationCommandOutput>;
    const nativeS3GetBucketCors: (input: GetBucketCorsCommandInput) => Promise<GetBucketCorsCommandOutput>;
    const nativeS3GetBucketEncryption: (input: GetBucketEncryptionCommandInput) => Promise<GetBucketEncryptionCommandOutput>;
    const nativeS3GetBucketIntelligentTieringConfiguration: (input: GetBucketIntelligentTieringConfigurationCommandInput) => Promise<GetBucketIntelligentTieringConfigurationCommandOutput>;
    const nativeS3GetBucketInventoryConfiguration: (input: GetBucketInventoryConfigurationCommandInput) => Promise<GetBucketInventoryConfigurationCommandOutput>;
    const nativeS3GetBucketLifecycleConfiguration: (input: GetBucketLifecycleConfigurationCommandInput) => Promise<GetBucketLifecycleConfigurationCommandOutput>;
    const nativeS3GetBucketLocation: (input: GetBucketLocationCommandInput) => Promise<GetBucketLocationCommandOutput>;
    const nativeS3GetBucketLogging: (input: GetBucketLoggingCommandInput) => Promise<GetBucketLoggingCommandOutput>;
    const nativeS3GetBucketMetricsConfiguration: (input: GetBucketMetricsConfigurationCommandInput) => Promise<GetBucketMetricsConfigurationCommandOutput>;
    const nativeS3GetBucketNotificationConfiguration: (input: GetBucketNotificationConfigurationCommandInput) => Promise<GetBucketNotificationConfigurationCommandOutput>;
    const nativeS3GetBucketOwnershipControls: (input: GetBucketOwnershipControlsCommandInput) => Promise<GetBucketOwnershipControlsCommandOutput>;
    const nativeS3GetBucketPolicy: (input: GetBucketPolicyCommandInput) => Promise<GetBucketPolicyCommandOutput>;
    const nativeS3GetBucketPolicyStatus: (input: GetBucketPolicyStatusCommandInput) => Promise<GetBucketPolicyStatusCommandOutput>;
    const nativeS3GetBucketReplication: (input: GetBucketReplicationCommandInput) => Promise<GetBucketReplicationCommandOutput>;
    const nativeS3GetBucketRequestPayment: (input: GetBucketRequestPaymentCommandInput) => Promise<GetBucketRequestPaymentCommandOutput>;
    const nativeS3GetBucketTagging: (input: GetBucketTaggingCommandInput) => Promise<GetBucketTaggingCommandOutput>;
    const nativeS3GetBucketVersioning: (input: GetBucketVersioningCommandInput) => Promise<GetBucketVersioningCommandOutput>;
    const nativeS3GetBucketWebsite: (input: GetBucketWebsiteCommandInput) => Promise<GetBucketWebsiteCommandOutput>;
    const nativeS3GetObject: (input: GetObjectCommandInput) => Promise<GetObjectCommandOutput>;
    const nativeS3GetObjectAcl: (input: GetObjectAclCommandInput) => Promise<GetObjectAclCommandOutput>;
    const nativeS3GetObjectLegalHold: (input: GetObjectLegalHoldCommandInput) => Promise<GetObjectLegalHoldCommandOutput>;
    const nativeS3GetObjectLockConfiguration: (input: GetObjectLockConfigurationCommandInput) => Promise<GetObjectLockConfigurationCommandOutput>;
    const nativeS3GetObjectRetention: (input: GetObjectRetentionCommandInput) => Promise<GetObjectRetentionCommandOutput>;
    const nativeS3GetObjectTagging: (input: GetObjectTaggingCommandInput) => Promise<GetObjectTaggingCommandOutput>;
    const nativeS3GetObjectTorrent: (input: GetObjectTorrentCommandInput) => Promise<GetObjectTorrentCommandOutput>;
    const nativeS3GetPublicAccessBlock: (input: GetPublicAccessBlockCommandInput) => Promise<GetPublicAccessBlockCommandOutput>;
    const nativeS3HeadBucket: (input: HeadBucketCommandInput) => Promise<HeadBucketCommandOutput>;
    const nativeS3HeadObject: (input: HeadObjectCommandInput) => Promise<HeadObjectCommandOutput>;
    const nativeS3ListBucketAnalyticsConfigurations: (input: ListBucketAnalyticsConfigurationsCommandInput) => Promise<ListBucketAnalyticsConfigurationsCommandOutput>;
    const nativeS3ListBucketIntelligentTieringConfigurations: (input: ListBucketIntelligentTieringConfigurationsCommandInput) => Promise<ListBucketIntelligentTieringConfigurationsCommandOutput>;
    const nativeS3ListBucketInventoryConfigurations: (input: ListBucketInventoryConfigurationsCommandInput) => Promise<ListBucketInventoryConfigurationsCommandOutput>;
    const nativeS3ListBucketMetricsConfigurations: (input: ListBucketMetricsConfigurationsCommandInput) => Promise<ListBucketMetricsConfigurationsCommandOutput>;
    const nativeS3ListBuckets: (input: ListBucketsCommandInput) => Promise<ListBucketsCommandOutput>;
    const nativeS3ListMultipartUploads: (input: ListMultipartUploadsCommandInput) => Promise<ListMultipartUploadsCommandOutput>;
    const nativeS3ListObjectVersions: (input: ListObjectVersionsCommandInput) => Promise<ListObjectVersionsCommandOutput>;
    const nativeS3ListObjects: (input: ListObjectsCommandInput) => Promise<ListObjectsCommandOutput>;
    const nativeS3ListObjectsV2: (input: ListObjectsV2CommandInput) => Promise<ListObjectsV2CommandOutput>;
    const nativeS3ListParts: (input: ListPartsCommandInput) => Promise<ListPartsCommandOutput>;
    const nativeS3PutBucketAccelerateConfiguration: (input: PutBucketAccelerateConfigurationCommandInput) => Promise<PutBucketAccelerateConfigurationCommandOutput>;
    const nativeS3PutBucketAcl: (input: PutBucketAclCommandInput) => Promise<PutBucketAclCommandOutput>;
    const nativeS3PutBucketAnalyticsConfiguration: (input: PutBucketAnalyticsConfigurationCommandInput) => Promise<PutBucketAnalyticsConfigurationCommandOutput>;
    const nativeS3PutBucketCors: (input: PutBucketCorsCommandInput) => Promise<PutBucketCorsCommandOutput>;
    const nativeS3PutBucketEncryption: (input: PutBucketEncryptionCommandInput) => Promise<PutBucketEncryptionCommandOutput>;
    const nativeS3PutBucketIntelligentTieringConfiguration: (input: PutBucketIntelligentTieringConfigurationCommandInput) => Promise<PutBucketIntelligentTieringConfigurationCommandOutput>;
    const nativeS3PutBucketInventoryConfiguration: (input: PutBucketInventoryConfigurationCommandInput) => Promise<PutBucketInventoryConfigurationCommandOutput>;
    const nativeS3PutBucketLifecycleConfiguration: (input: PutBucketLifecycleConfigurationCommandInput) => Promise<PutBucketLifecycleConfigurationCommandOutput>;
    const nativeS3PutBucketLogging: (input: PutBucketLoggingCommandInput) => Promise<PutBucketLoggingCommandOutput>;
    const nativeS3PutBucketMetricsConfiguration: (input: PutBucketMetricsConfigurationCommandInput) => Promise<PutBucketMetricsConfigurationCommandOutput>;
    const nativeS3PutBucketNotificationConfiguration: (input: PutBucketNotificationConfigurationCommandInput) => Promise<PutBucketNotificationConfigurationCommandOutput>;
    const nativeS3PutBucketOwnershipControls: (input: PutBucketOwnershipControlsCommandInput) => Promise<PutBucketOwnershipControlsCommandOutput>;
    const nativeS3PutBucketPolicy: (input: PutBucketPolicyCommandInput) => Promise<PutBucketPolicyCommandOutput>;
    const nativeS3PutBucketReplication: (input: PutBucketReplicationCommandInput) => Promise<PutBucketReplicationCommandOutput>;
    const nativeS3PutBucketRequestPayment: (input: PutBucketRequestPaymentCommandInput) => Promise<PutBucketRequestPaymentCommandOutput>;
    const nativeS3PutBucketTagging: (input: PutBucketTaggingCommandInput) => Promise<PutBucketTaggingCommandOutput>;
    const nativeS3PutBucketVersioning: (input: PutBucketVersioningCommandInput) => Promise<PutBucketVersioningCommandOutput>;
    const nativeS3PutBucketWebsite: (input: PutBucketWebsiteCommandInput) => Promise<PutBucketWebsiteCommandOutput>;
    const nativeS3PutObject: (input: PutObjectCommandInput) => Promise<PutObjectCommandOutput>;
    const nativeS3PutObjectAcl: (input: PutObjectAclCommandInput) => Promise<PutObjectAclCommandOutput>;
    const nativeS3PutObjectLegalHold: (input: PutObjectLegalHoldCommandInput) => Promise<PutObjectLegalHoldCommandOutput>;
    const nativeS3PutObjectLockConfiguration: (input: PutObjectLockConfigurationCommandInput) => Promise<PutObjectLockConfigurationCommandOutput>;
    const nativeS3PutObjectRetention: (input: PutObjectRetentionCommandInput) => Promise<PutObjectRetentionCommandOutput>;
    const nativeS3PutObjectTagging: (input: PutObjectTaggingCommandInput) => Promise<PutObjectTaggingCommandOutput>;
    const nativeS3PutPublicAccessBlock: (input: PutPublicAccessBlockCommandInput) => Promise<PutPublicAccessBlockCommandOutput>;
    const nativeS3RestoreObject: (input: RestoreObjectCommandInput) => Promise<RestoreObjectCommandOutput>;
    const nativeS3UploadPart: (input: UploadPartCommandInput) => Promise<UploadPartCommandOutput>;
    const nativeS3UploadPartCopy: (input: UploadPartCopyCommandInput) => Promise<UploadPartCopyCommandOutput>;
    const nativeS3WriteGetObjectResponse: (input: WriteGetObjectResponseCommandInput) => Promise<WriteGetObjectResponseCommandOutput>;
}
