import { AddTagsToResourceCommandInput, AddTagsToResourceCommandOutput } from "@aws-sdk/client-ssm";
import { AssociateOpsItemRelatedItemCommandInput, AssociateOpsItemRelatedItemCommandOutput } from "@aws-sdk/client-ssm";
import { CancelCommandCommandInput, CancelCommandCommandOutput } from "@aws-sdk/client-ssm";
import { CancelMaintenanceWindowExecutionCommandInput, CancelMaintenanceWindowExecutionCommandOutput } from "@aws-sdk/client-ssm";
import { CreateActivationCommandInput, CreateActivationCommandOutput } from "@aws-sdk/client-ssm";
import { CreateAssociationCommandInput, CreateAssociationCommandOutput } from "@aws-sdk/client-ssm";
import { CreateAssociationBatchCommandInput, CreateAssociationBatchCommandOutput } from "@aws-sdk/client-ssm";
import { CreateDocumentCommandInput, CreateDocumentCommandOutput } from "@aws-sdk/client-ssm";
import { CreateMaintenanceWindowCommandInput, CreateMaintenanceWindowCommandOutput } from "@aws-sdk/client-ssm";
import { CreateOpsItemCommandInput, CreateOpsItemCommandOutput } from "@aws-sdk/client-ssm";
import { CreateOpsMetadataCommandInput, CreateOpsMetadataCommandOutput } from "@aws-sdk/client-ssm";
import { CreatePatchBaselineCommandInput, CreatePatchBaselineCommandOutput } from "@aws-sdk/client-ssm";
import { CreateResourceDataSyncCommandInput, CreateResourceDataSyncCommandOutput } from "@aws-sdk/client-ssm";
import { DeleteActivationCommandInput, DeleteActivationCommandOutput } from "@aws-sdk/client-ssm";
import { DeleteAssociationCommandInput, DeleteAssociationCommandOutput } from "@aws-sdk/client-ssm";
import { DeleteDocumentCommandInput, DeleteDocumentCommandOutput } from "@aws-sdk/client-ssm";
import { DeleteInventoryCommandInput, DeleteInventoryCommandOutput } from "@aws-sdk/client-ssm";
import { DeleteMaintenanceWindowCommandInput, DeleteMaintenanceWindowCommandOutput } from "@aws-sdk/client-ssm";
import { DeleteOpsMetadataCommandInput, DeleteOpsMetadataCommandOutput } from "@aws-sdk/client-ssm";
import { DeleteParameterCommandInput, DeleteParameterCommandOutput } from "@aws-sdk/client-ssm";
import { DeleteParametersCommandInput, DeleteParametersCommandOutput } from "@aws-sdk/client-ssm";
import { DeletePatchBaselineCommandInput, DeletePatchBaselineCommandOutput } from "@aws-sdk/client-ssm";
import { DeleteResourceDataSyncCommandInput, DeleteResourceDataSyncCommandOutput } from "@aws-sdk/client-ssm";
import { DeregisterManagedInstanceCommandInput, DeregisterManagedInstanceCommandOutput } from "@aws-sdk/client-ssm";
import { DeregisterPatchBaselineForPatchGroupCommandInput, DeregisterPatchBaselineForPatchGroupCommandOutput } from "@aws-sdk/client-ssm";
import { DeregisterTargetFromMaintenanceWindowCommandInput, DeregisterTargetFromMaintenanceWindowCommandOutput } from "@aws-sdk/client-ssm";
import { DeregisterTaskFromMaintenanceWindowCommandInput, DeregisterTaskFromMaintenanceWindowCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeActivationsCommandInput, DescribeActivationsCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeAssociationCommandInput, DescribeAssociationCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeAssociationExecutionTargetsCommandInput, DescribeAssociationExecutionTargetsCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeAssociationExecutionsCommandInput, DescribeAssociationExecutionsCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeAutomationExecutionsCommandInput, DescribeAutomationExecutionsCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeAutomationStepExecutionsCommandInput, DescribeAutomationStepExecutionsCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeAvailablePatchesCommandInput, DescribeAvailablePatchesCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeDocumentCommandInput, DescribeDocumentCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeDocumentPermissionCommandInput, DescribeDocumentPermissionCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeEffectiveInstanceAssociationsCommandInput, DescribeEffectiveInstanceAssociationsCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeEffectivePatchesForPatchBaselineCommandInput, DescribeEffectivePatchesForPatchBaselineCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeInstanceAssociationsStatusCommandInput, DescribeInstanceAssociationsStatusCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeInstanceInformationCommandInput, DescribeInstanceInformationCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeInstancePatchStatesCommandInput, DescribeInstancePatchStatesCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeInstancePatchStatesForPatchGroupCommandInput, DescribeInstancePatchStatesForPatchGroupCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeInstancePatchesCommandInput, DescribeInstancePatchesCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeInventoryDeletionsCommandInput, DescribeInventoryDeletionsCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeMaintenanceWindowExecutionTaskInvocationsCommandInput, DescribeMaintenanceWindowExecutionTaskInvocationsCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeMaintenanceWindowExecutionTasksCommandInput, DescribeMaintenanceWindowExecutionTasksCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeMaintenanceWindowExecutionsCommandInput, DescribeMaintenanceWindowExecutionsCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeMaintenanceWindowScheduleCommandInput, DescribeMaintenanceWindowScheduleCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeMaintenanceWindowTargetsCommandInput, DescribeMaintenanceWindowTargetsCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeMaintenanceWindowTasksCommandInput, DescribeMaintenanceWindowTasksCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeMaintenanceWindowsCommandInput, DescribeMaintenanceWindowsCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeMaintenanceWindowsForTargetCommandInput, DescribeMaintenanceWindowsForTargetCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeOpsItemsCommandInput, DescribeOpsItemsCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeParametersCommandInput, DescribeParametersCommandOutput } from "@aws-sdk/client-ssm";
import { DescribePatchBaselinesCommandInput, DescribePatchBaselinesCommandOutput } from "@aws-sdk/client-ssm";
import { DescribePatchGroupStateCommandInput, DescribePatchGroupStateCommandOutput } from "@aws-sdk/client-ssm";
import { DescribePatchGroupsCommandInput, DescribePatchGroupsCommandOutput } from "@aws-sdk/client-ssm";
import { DescribePatchPropertiesCommandInput, DescribePatchPropertiesCommandOutput } from "@aws-sdk/client-ssm";
import { DescribeSessionsCommandInput, DescribeSessionsCommandOutput } from "@aws-sdk/client-ssm";
import { DisassociateOpsItemRelatedItemCommandInput, DisassociateOpsItemRelatedItemCommandOutput } from "@aws-sdk/client-ssm";
import { GetAutomationExecutionCommandInput, GetAutomationExecutionCommandOutput } from "@aws-sdk/client-ssm";
import { GetCalendarStateCommandInput, GetCalendarStateCommandOutput } from "@aws-sdk/client-ssm";
import { GetCommandInvocationCommandInput, GetCommandInvocationCommandOutput } from "@aws-sdk/client-ssm";
import { GetConnectionStatusCommandInput, GetConnectionStatusCommandOutput } from "@aws-sdk/client-ssm";
import { GetDefaultPatchBaselineCommandInput, GetDefaultPatchBaselineCommandOutput } from "@aws-sdk/client-ssm";
import { GetDeployablePatchSnapshotForInstanceCommandInput, GetDeployablePatchSnapshotForInstanceCommandOutput } from "@aws-sdk/client-ssm";
import { GetDocumentCommandInput, GetDocumentCommandOutput } from "@aws-sdk/client-ssm";
import { GetInventoryCommandInput, GetInventoryCommandOutput } from "@aws-sdk/client-ssm";
import { GetInventorySchemaCommandInput, GetInventorySchemaCommandOutput } from "@aws-sdk/client-ssm";
import { GetMaintenanceWindowCommandInput, GetMaintenanceWindowCommandOutput } from "@aws-sdk/client-ssm";
import { GetMaintenanceWindowExecutionCommandInput, GetMaintenanceWindowExecutionCommandOutput } from "@aws-sdk/client-ssm";
import { GetMaintenanceWindowExecutionTaskCommandInput, GetMaintenanceWindowExecutionTaskCommandOutput } from "@aws-sdk/client-ssm";
import { GetMaintenanceWindowExecutionTaskInvocationCommandInput, GetMaintenanceWindowExecutionTaskInvocationCommandOutput } from "@aws-sdk/client-ssm";
import { GetMaintenanceWindowTaskCommandInput, GetMaintenanceWindowTaskCommandOutput } from "@aws-sdk/client-ssm";
import { GetOpsItemCommandInput, GetOpsItemCommandOutput } from "@aws-sdk/client-ssm";
import { GetOpsMetadataCommandInput, GetOpsMetadataCommandOutput } from "@aws-sdk/client-ssm";
import { GetOpsSummaryCommandInput, GetOpsSummaryCommandOutput } from "@aws-sdk/client-ssm";
import { GetParameterCommandInput, GetParameterCommandOutput } from "@aws-sdk/client-ssm";
import { GetParameterHistoryCommandInput, GetParameterHistoryCommandOutput } from "@aws-sdk/client-ssm";
import { GetParametersCommandInput, GetParametersCommandOutput } from "@aws-sdk/client-ssm";
import { GetParametersByPathCommandInput, GetParametersByPathCommandOutput } from "@aws-sdk/client-ssm";
import { GetPatchBaselineCommandInput, GetPatchBaselineCommandOutput } from "@aws-sdk/client-ssm";
import { GetPatchBaselineForPatchGroupCommandInput, GetPatchBaselineForPatchGroupCommandOutput } from "@aws-sdk/client-ssm";
import { GetServiceSettingCommandInput, GetServiceSettingCommandOutput } from "@aws-sdk/client-ssm";
import { LabelParameterVersionCommandInput, LabelParameterVersionCommandOutput } from "@aws-sdk/client-ssm";
import { ListAssociationVersionsCommandInput, ListAssociationVersionsCommandOutput } from "@aws-sdk/client-ssm";
import { ListAssociationsCommandInput, ListAssociationsCommandOutput } from "@aws-sdk/client-ssm";
import { ListCommandInvocationsCommandInput, ListCommandInvocationsCommandOutput } from "@aws-sdk/client-ssm";
import { ListCommandsCommandInput, ListCommandsCommandOutput } from "@aws-sdk/client-ssm";
import { ListComplianceItemsCommandInput, ListComplianceItemsCommandOutput } from "@aws-sdk/client-ssm";
import { ListComplianceSummariesCommandInput, ListComplianceSummariesCommandOutput } from "@aws-sdk/client-ssm";
import { ListDocumentMetadataHistoryCommandInput, ListDocumentMetadataHistoryCommandOutput } from "@aws-sdk/client-ssm";
import { ListDocumentVersionsCommandInput, ListDocumentVersionsCommandOutput } from "@aws-sdk/client-ssm";
import { ListDocumentsCommandInput, ListDocumentsCommandOutput } from "@aws-sdk/client-ssm";
import { ListInventoryEntriesCommandInput, ListInventoryEntriesCommandOutput } from "@aws-sdk/client-ssm";
import { ListOpsItemEventsCommandInput, ListOpsItemEventsCommandOutput } from "@aws-sdk/client-ssm";
import { ListOpsItemRelatedItemsCommandInput, ListOpsItemRelatedItemsCommandOutput } from "@aws-sdk/client-ssm";
import { ListOpsMetadataCommandInput, ListOpsMetadataCommandOutput } from "@aws-sdk/client-ssm";
import { ListResourceComplianceSummariesCommandInput, ListResourceComplianceSummariesCommandOutput } from "@aws-sdk/client-ssm";
import { ListResourceDataSyncCommandInput, ListResourceDataSyncCommandOutput } from "@aws-sdk/client-ssm";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "@aws-sdk/client-ssm";
import { ModifyDocumentPermissionCommandInput, ModifyDocumentPermissionCommandOutput } from "@aws-sdk/client-ssm";
import { PutComplianceItemsCommandInput, PutComplianceItemsCommandOutput } from "@aws-sdk/client-ssm";
import { PutInventoryCommandInput, PutInventoryCommandOutput } from "@aws-sdk/client-ssm";
import { PutParameterCommandInput, PutParameterCommandOutput } from "@aws-sdk/client-ssm";
import { RegisterDefaultPatchBaselineCommandInput, RegisterDefaultPatchBaselineCommandOutput } from "@aws-sdk/client-ssm";
import { RegisterPatchBaselineForPatchGroupCommandInput, RegisterPatchBaselineForPatchGroupCommandOutput } from "@aws-sdk/client-ssm";
import { RegisterTargetWithMaintenanceWindowCommandInput, RegisterTargetWithMaintenanceWindowCommandOutput } from "@aws-sdk/client-ssm";
import { RegisterTaskWithMaintenanceWindowCommandInput, RegisterTaskWithMaintenanceWindowCommandOutput } from "@aws-sdk/client-ssm";
import { RemoveTagsFromResourceCommandInput, RemoveTagsFromResourceCommandOutput } from "@aws-sdk/client-ssm";
import { ResetServiceSettingCommandInput, ResetServiceSettingCommandOutput } from "@aws-sdk/client-ssm";
import { ResumeSessionCommandInput, ResumeSessionCommandOutput } from "@aws-sdk/client-ssm";
import { SendAutomationSignalCommandInput, SendAutomationSignalCommandOutput } from "@aws-sdk/client-ssm";
import { SendCommandCommandInput, SendCommandCommandOutput } from "@aws-sdk/client-ssm";
import { StartAssociationsOnceCommandInput, StartAssociationsOnceCommandOutput } from "@aws-sdk/client-ssm";
import { StartAutomationExecutionCommandInput, StartAutomationExecutionCommandOutput } from "@aws-sdk/client-ssm";
import { StartChangeRequestExecutionCommandInput, StartChangeRequestExecutionCommandOutput } from "@aws-sdk/client-ssm";
import { StartSessionCommandInput, StartSessionCommandOutput } from "@aws-sdk/client-ssm";
import { StopAutomationExecutionCommandInput, StopAutomationExecutionCommandOutput } from "@aws-sdk/client-ssm";
import { TerminateSessionCommandInput, TerminateSessionCommandOutput } from "@aws-sdk/client-ssm";
import { UnlabelParameterVersionCommandInput, UnlabelParameterVersionCommandOutput } from "@aws-sdk/client-ssm";
import { UpdateAssociationCommandInput, UpdateAssociationCommandOutput } from "@aws-sdk/client-ssm";
import { UpdateAssociationStatusCommandInput, UpdateAssociationStatusCommandOutput } from "@aws-sdk/client-ssm";
import { UpdateDocumentCommandInput, UpdateDocumentCommandOutput } from "@aws-sdk/client-ssm";
import { UpdateDocumentDefaultVersionCommandInput, UpdateDocumentDefaultVersionCommandOutput } from "@aws-sdk/client-ssm";
import { UpdateDocumentMetadataCommandInput, UpdateDocumentMetadataCommandOutput } from "@aws-sdk/client-ssm";
import { UpdateMaintenanceWindowCommandInput, UpdateMaintenanceWindowCommandOutput } from "@aws-sdk/client-ssm";
import { UpdateMaintenanceWindowTargetCommandInput, UpdateMaintenanceWindowTargetCommandOutput } from "@aws-sdk/client-ssm";
import { UpdateMaintenanceWindowTaskCommandInput, UpdateMaintenanceWindowTaskCommandOutput } from "@aws-sdk/client-ssm";
import { UpdateManagedInstanceRoleCommandInput, UpdateManagedInstanceRoleCommandOutput } from "@aws-sdk/client-ssm";
import { UpdateOpsItemCommandInput, UpdateOpsItemCommandOutput } from "@aws-sdk/client-ssm";
import { UpdateOpsMetadataCommandInput, UpdateOpsMetadataCommandOutput } from "@aws-sdk/client-ssm";
import { UpdatePatchBaselineCommandInput, UpdatePatchBaselineCommandOutput } from "@aws-sdk/client-ssm";
import { UpdateResourceDataSyncCommandInput, UpdateResourceDataSyncCommandOutput } from "@aws-sdk/client-ssm";
import { UpdateServiceSettingCommandInput, UpdateServiceSettingCommandOutput } from "@aws-sdk/client-ssm";
export declare namespace ASL {
    const nativeSSMAddTagsToResource: (input: AddTagsToResourceCommandInput) => Promise<AddTagsToResourceCommandOutput>;
    const nativeSSMAssociateOpsItemRelatedItem: (input: AssociateOpsItemRelatedItemCommandInput) => Promise<AssociateOpsItemRelatedItemCommandOutput>;
    const nativeSSMCancelCommand: (input: CancelCommandCommandInput) => Promise<CancelCommandCommandOutput>;
    const nativeSSMCancelMaintenanceWindowExecution: (input: CancelMaintenanceWindowExecutionCommandInput) => Promise<CancelMaintenanceWindowExecutionCommandOutput>;
    const nativeSSMCreateActivation: (input: CreateActivationCommandInput) => Promise<CreateActivationCommandOutput>;
    const nativeSSMCreateAssociation: (input: CreateAssociationCommandInput) => Promise<CreateAssociationCommandOutput>;
    const nativeSSMCreateAssociationBatch: (input: CreateAssociationBatchCommandInput) => Promise<CreateAssociationBatchCommandOutput>;
    const nativeSSMCreateDocument: (input: CreateDocumentCommandInput) => Promise<CreateDocumentCommandOutput>;
    const nativeSSMCreateMaintenanceWindow: (input: CreateMaintenanceWindowCommandInput) => Promise<CreateMaintenanceWindowCommandOutput>;
    const nativeSSMCreateOpsItem: (input: CreateOpsItemCommandInput) => Promise<CreateOpsItemCommandOutput>;
    const nativeSSMCreateOpsMetadata: (input: CreateOpsMetadataCommandInput) => Promise<CreateOpsMetadataCommandOutput>;
    const nativeSSMCreatePatchBaseline: (input: CreatePatchBaselineCommandInput) => Promise<CreatePatchBaselineCommandOutput>;
    const nativeSSMCreateResourceDataSync: (input: CreateResourceDataSyncCommandInput) => Promise<CreateResourceDataSyncCommandOutput>;
    const nativeSSMDeleteActivation: (input: DeleteActivationCommandInput) => Promise<DeleteActivationCommandOutput>;
    const nativeSSMDeleteAssociation: (input: DeleteAssociationCommandInput) => Promise<DeleteAssociationCommandOutput>;
    const nativeSSMDeleteDocument: (input: DeleteDocumentCommandInput) => Promise<DeleteDocumentCommandOutput>;
    const nativeSSMDeleteInventory: (input: DeleteInventoryCommandInput) => Promise<DeleteInventoryCommandOutput>;
    const nativeSSMDeleteMaintenanceWindow: (input: DeleteMaintenanceWindowCommandInput) => Promise<DeleteMaintenanceWindowCommandOutput>;
    const nativeSSMDeleteOpsMetadata: (input: DeleteOpsMetadataCommandInput) => Promise<DeleteOpsMetadataCommandOutput>;
    const nativeSSMDeleteParameter: (input: DeleteParameterCommandInput) => Promise<DeleteParameterCommandOutput>;
    const nativeSSMDeleteParameters: (input: DeleteParametersCommandInput) => Promise<DeleteParametersCommandOutput>;
    const nativeSSMDeletePatchBaseline: (input: DeletePatchBaselineCommandInput) => Promise<DeletePatchBaselineCommandOutput>;
    const nativeSSMDeleteResourceDataSync: (input: DeleteResourceDataSyncCommandInput) => Promise<DeleteResourceDataSyncCommandOutput>;
    const nativeSSMDeregisterManagedInstance: (input: DeregisterManagedInstanceCommandInput) => Promise<DeregisterManagedInstanceCommandOutput>;
    const nativeSSMDeregisterPatchBaselineForPatchGroup: (input: DeregisterPatchBaselineForPatchGroupCommandInput) => Promise<DeregisterPatchBaselineForPatchGroupCommandOutput>;
    const nativeSSMDeregisterTargetFromMaintenanceWindow: (input: DeregisterTargetFromMaintenanceWindowCommandInput) => Promise<DeregisterTargetFromMaintenanceWindowCommandOutput>;
    const nativeSSMDeregisterTaskFromMaintenanceWindow: (input: DeregisterTaskFromMaintenanceWindowCommandInput) => Promise<DeregisterTaskFromMaintenanceWindowCommandOutput>;
    const nativeSSMDescribeActivations: (input: DescribeActivationsCommandInput) => Promise<DescribeActivationsCommandOutput>;
    const nativeSSMDescribeAssociation: (input: DescribeAssociationCommandInput) => Promise<DescribeAssociationCommandOutput>;
    const nativeSSMDescribeAssociationExecutionTargets: (input: DescribeAssociationExecutionTargetsCommandInput) => Promise<DescribeAssociationExecutionTargetsCommandOutput>;
    const nativeSSMDescribeAssociationExecutions: (input: DescribeAssociationExecutionsCommandInput) => Promise<DescribeAssociationExecutionsCommandOutput>;
    const nativeSSMDescribeAutomationExecutions: (input: DescribeAutomationExecutionsCommandInput) => Promise<DescribeAutomationExecutionsCommandOutput>;
    const nativeSSMDescribeAutomationStepExecutions: (input: DescribeAutomationStepExecutionsCommandInput) => Promise<DescribeAutomationStepExecutionsCommandOutput>;
    const nativeSSMDescribeAvailablePatches: (input: DescribeAvailablePatchesCommandInput) => Promise<DescribeAvailablePatchesCommandOutput>;
    const nativeSSMDescribeDocument: (input: DescribeDocumentCommandInput) => Promise<DescribeDocumentCommandOutput>;
    const nativeSSMDescribeDocumentPermission: (input: DescribeDocumentPermissionCommandInput) => Promise<DescribeDocumentPermissionCommandOutput>;
    const nativeSSMDescribeEffectiveInstanceAssociations: (input: DescribeEffectiveInstanceAssociationsCommandInput) => Promise<DescribeEffectiveInstanceAssociationsCommandOutput>;
    const nativeSSMDescribeEffectivePatchesForPatchBaseline: (input: DescribeEffectivePatchesForPatchBaselineCommandInput) => Promise<DescribeEffectivePatchesForPatchBaselineCommandOutput>;
    const nativeSSMDescribeInstanceAssociationsStatus: (input: DescribeInstanceAssociationsStatusCommandInput) => Promise<DescribeInstanceAssociationsStatusCommandOutput>;
    const nativeSSMDescribeInstanceInformation: (input: DescribeInstanceInformationCommandInput) => Promise<DescribeInstanceInformationCommandOutput>;
    const nativeSSMDescribeInstancePatchStates: (input: DescribeInstancePatchStatesCommandInput) => Promise<DescribeInstancePatchStatesCommandOutput>;
    const nativeSSMDescribeInstancePatchStatesForPatchGroup: (input: DescribeInstancePatchStatesForPatchGroupCommandInput) => Promise<DescribeInstancePatchStatesForPatchGroupCommandOutput>;
    const nativeSSMDescribeInstancePatches: (input: DescribeInstancePatchesCommandInput) => Promise<DescribeInstancePatchesCommandOutput>;
    const nativeSSMDescribeInventoryDeletions: (input: DescribeInventoryDeletionsCommandInput) => Promise<DescribeInventoryDeletionsCommandOutput>;
    const nativeSSMDescribeMaintenanceWindowExecutionTaskInvocations: (input: DescribeMaintenanceWindowExecutionTaskInvocationsCommandInput) => Promise<DescribeMaintenanceWindowExecutionTaskInvocationsCommandOutput>;
    const nativeSSMDescribeMaintenanceWindowExecutionTasks: (input: DescribeMaintenanceWindowExecutionTasksCommandInput) => Promise<DescribeMaintenanceWindowExecutionTasksCommandOutput>;
    const nativeSSMDescribeMaintenanceWindowExecutions: (input: DescribeMaintenanceWindowExecutionsCommandInput) => Promise<DescribeMaintenanceWindowExecutionsCommandOutput>;
    const nativeSSMDescribeMaintenanceWindowSchedule: (input: DescribeMaintenanceWindowScheduleCommandInput) => Promise<DescribeMaintenanceWindowScheduleCommandOutput>;
    const nativeSSMDescribeMaintenanceWindowTargets: (input: DescribeMaintenanceWindowTargetsCommandInput) => Promise<DescribeMaintenanceWindowTargetsCommandOutput>;
    const nativeSSMDescribeMaintenanceWindowTasks: (input: DescribeMaintenanceWindowTasksCommandInput) => Promise<DescribeMaintenanceWindowTasksCommandOutput>;
    const nativeSSMDescribeMaintenanceWindows: (input: DescribeMaintenanceWindowsCommandInput) => Promise<DescribeMaintenanceWindowsCommandOutput>;
    const nativeSSMDescribeMaintenanceWindowsForTarget: (input: DescribeMaintenanceWindowsForTargetCommandInput) => Promise<DescribeMaintenanceWindowsForTargetCommandOutput>;
    const nativeSSMDescribeOpsItems: (input: DescribeOpsItemsCommandInput) => Promise<DescribeOpsItemsCommandOutput>;
    const nativeSSMDescribeParameters: (input: DescribeParametersCommandInput) => Promise<DescribeParametersCommandOutput>;
    const nativeSSMDescribePatchBaselines: (input: DescribePatchBaselinesCommandInput) => Promise<DescribePatchBaselinesCommandOutput>;
    const nativeSSMDescribePatchGroupState: (input: DescribePatchGroupStateCommandInput) => Promise<DescribePatchGroupStateCommandOutput>;
    const nativeSSMDescribePatchGroups: (input: DescribePatchGroupsCommandInput) => Promise<DescribePatchGroupsCommandOutput>;
    const nativeSSMDescribePatchProperties: (input: DescribePatchPropertiesCommandInput) => Promise<DescribePatchPropertiesCommandOutput>;
    const nativeSSMDescribeSessions: (input: DescribeSessionsCommandInput) => Promise<DescribeSessionsCommandOutput>;
    const nativeSSMDisassociateOpsItemRelatedItem: (input: DisassociateOpsItemRelatedItemCommandInput) => Promise<DisassociateOpsItemRelatedItemCommandOutput>;
    const nativeSSMGetAutomationExecution: (input: GetAutomationExecutionCommandInput) => Promise<GetAutomationExecutionCommandOutput>;
    const nativeSSMGetCalendarState: (input: GetCalendarStateCommandInput) => Promise<GetCalendarStateCommandOutput>;
    const nativeSSMGetCommandInvocation: (input: GetCommandInvocationCommandInput) => Promise<GetCommandInvocationCommandOutput>;
    const nativeSSMGetConnectionStatus: (input: GetConnectionStatusCommandInput) => Promise<GetConnectionStatusCommandOutput>;
    const nativeSSMGetDefaultPatchBaseline: (input: GetDefaultPatchBaselineCommandInput) => Promise<GetDefaultPatchBaselineCommandOutput>;
    const nativeSSMGetDeployablePatchSnapshotForInstance: (input: GetDeployablePatchSnapshotForInstanceCommandInput) => Promise<GetDeployablePatchSnapshotForInstanceCommandOutput>;
    const nativeSSMGetDocument: (input: GetDocumentCommandInput) => Promise<GetDocumentCommandOutput>;
    const nativeSSMGetInventory: (input: GetInventoryCommandInput) => Promise<GetInventoryCommandOutput>;
    const nativeSSMGetInventorySchema: (input: GetInventorySchemaCommandInput) => Promise<GetInventorySchemaCommandOutput>;
    const nativeSSMGetMaintenanceWindow: (input: GetMaintenanceWindowCommandInput) => Promise<GetMaintenanceWindowCommandOutput>;
    const nativeSSMGetMaintenanceWindowExecution: (input: GetMaintenanceWindowExecutionCommandInput) => Promise<GetMaintenanceWindowExecutionCommandOutput>;
    const nativeSSMGetMaintenanceWindowExecutionTask: (input: GetMaintenanceWindowExecutionTaskCommandInput) => Promise<GetMaintenanceWindowExecutionTaskCommandOutput>;
    const nativeSSMGetMaintenanceWindowExecutionTaskInvocation: (input: GetMaintenanceWindowExecutionTaskInvocationCommandInput) => Promise<GetMaintenanceWindowExecutionTaskInvocationCommandOutput>;
    const nativeSSMGetMaintenanceWindowTask: (input: GetMaintenanceWindowTaskCommandInput) => Promise<GetMaintenanceWindowTaskCommandOutput>;
    const nativeSSMGetOpsItem: (input: GetOpsItemCommandInput) => Promise<GetOpsItemCommandOutput>;
    const nativeSSMGetOpsMetadata: (input: GetOpsMetadataCommandInput) => Promise<GetOpsMetadataCommandOutput>;
    const nativeSSMGetOpsSummary: (input: GetOpsSummaryCommandInput) => Promise<GetOpsSummaryCommandOutput>;
    const nativeSSMGetParameter: (input: GetParameterCommandInput) => Promise<GetParameterCommandOutput>;
    const nativeSSMGetParameterHistory: (input: GetParameterHistoryCommandInput) => Promise<GetParameterHistoryCommandOutput>;
    const nativeSSMGetParameters: (input: GetParametersCommandInput) => Promise<GetParametersCommandOutput>;
    const nativeSSMGetParametersByPath: (input: GetParametersByPathCommandInput) => Promise<GetParametersByPathCommandOutput>;
    const nativeSSMGetPatchBaseline: (input: GetPatchBaselineCommandInput) => Promise<GetPatchBaselineCommandOutput>;
    const nativeSSMGetPatchBaselineForPatchGroup: (input: GetPatchBaselineForPatchGroupCommandInput) => Promise<GetPatchBaselineForPatchGroupCommandOutput>;
    const nativeSSMGetServiceSetting: (input: GetServiceSettingCommandInput) => Promise<GetServiceSettingCommandOutput>;
    const nativeSSMLabelParameterVersion: (input: LabelParameterVersionCommandInput) => Promise<LabelParameterVersionCommandOutput>;
    const nativeSSMListAssociationVersions: (input: ListAssociationVersionsCommandInput) => Promise<ListAssociationVersionsCommandOutput>;
    const nativeSSMListAssociations: (input: ListAssociationsCommandInput) => Promise<ListAssociationsCommandOutput>;
    const nativeSSMListCommandInvocations: (input: ListCommandInvocationsCommandInput) => Promise<ListCommandInvocationsCommandOutput>;
    const nativeSSMListCommands: (input: ListCommandsCommandInput) => Promise<ListCommandsCommandOutput>;
    const nativeSSMListComplianceItems: (input: ListComplianceItemsCommandInput) => Promise<ListComplianceItemsCommandOutput>;
    const nativeSSMListComplianceSummaries: (input: ListComplianceSummariesCommandInput) => Promise<ListComplianceSummariesCommandOutput>;
    const nativeSSMListDocumentMetadataHistory: (input: ListDocumentMetadataHistoryCommandInput) => Promise<ListDocumentMetadataHistoryCommandOutput>;
    const nativeSSMListDocumentVersions: (input: ListDocumentVersionsCommandInput) => Promise<ListDocumentVersionsCommandOutput>;
    const nativeSSMListDocuments: (input: ListDocumentsCommandInput) => Promise<ListDocumentsCommandOutput>;
    const nativeSSMListInventoryEntries: (input: ListInventoryEntriesCommandInput) => Promise<ListInventoryEntriesCommandOutput>;
    const nativeSSMListOpsItemEvents: (input: ListOpsItemEventsCommandInput) => Promise<ListOpsItemEventsCommandOutput>;
    const nativeSSMListOpsItemRelatedItems: (input: ListOpsItemRelatedItemsCommandInput) => Promise<ListOpsItemRelatedItemsCommandOutput>;
    const nativeSSMListOpsMetadata: (input: ListOpsMetadataCommandInput) => Promise<ListOpsMetadataCommandOutput>;
    const nativeSSMListResourceComplianceSummaries: (input: ListResourceComplianceSummariesCommandInput) => Promise<ListResourceComplianceSummariesCommandOutput>;
    const nativeSSMListResourceDataSync: (input: ListResourceDataSyncCommandInput) => Promise<ListResourceDataSyncCommandOutput>;
    const nativeSSMListTagsForResource: (input: ListTagsForResourceCommandInput) => Promise<ListTagsForResourceCommandOutput>;
    const nativeSSMModifyDocumentPermission: (input: ModifyDocumentPermissionCommandInput) => Promise<ModifyDocumentPermissionCommandOutput>;
    const nativeSSMPutComplianceItems: (input: PutComplianceItemsCommandInput) => Promise<PutComplianceItemsCommandOutput>;
    const nativeSSMPutInventory: (input: PutInventoryCommandInput) => Promise<PutInventoryCommandOutput>;
    const nativeSSMPutParameter: (input: PutParameterCommandInput) => Promise<PutParameterCommandOutput>;
    const nativeSSMRegisterDefaultPatchBaseline: (input: RegisterDefaultPatchBaselineCommandInput) => Promise<RegisterDefaultPatchBaselineCommandOutput>;
    const nativeSSMRegisterPatchBaselineForPatchGroup: (input: RegisterPatchBaselineForPatchGroupCommandInput) => Promise<RegisterPatchBaselineForPatchGroupCommandOutput>;
    const nativeSSMRegisterTargetWithMaintenanceWindow: (input: RegisterTargetWithMaintenanceWindowCommandInput) => Promise<RegisterTargetWithMaintenanceWindowCommandOutput>;
    const nativeSSMRegisterTaskWithMaintenanceWindow: (input: RegisterTaskWithMaintenanceWindowCommandInput) => Promise<RegisterTaskWithMaintenanceWindowCommandOutput>;
    const nativeSSMRemoveTagsFromResource: (input: RemoveTagsFromResourceCommandInput) => Promise<RemoveTagsFromResourceCommandOutput>;
    const nativeSSMResetServiceSetting: (input: ResetServiceSettingCommandInput) => Promise<ResetServiceSettingCommandOutput>;
    const nativeSSMResumeSession: (input: ResumeSessionCommandInput) => Promise<ResumeSessionCommandOutput>;
    const nativeSSMSendAutomationSignal: (input: SendAutomationSignalCommandInput) => Promise<SendAutomationSignalCommandOutput>;
    const nativeSSMSendCommand: (input: SendCommandCommandInput) => Promise<SendCommandCommandOutput>;
    const nativeSSMStartAssociationsOnce: (input: StartAssociationsOnceCommandInput) => Promise<StartAssociationsOnceCommandOutput>;
    const nativeSSMStartAutomationExecution: (input: StartAutomationExecutionCommandInput) => Promise<StartAutomationExecutionCommandOutput>;
    const nativeSSMStartChangeRequestExecution: (input: StartChangeRequestExecutionCommandInput) => Promise<StartChangeRequestExecutionCommandOutput>;
    const nativeSSMStartSession: (input: StartSessionCommandInput) => Promise<StartSessionCommandOutput>;
    const nativeSSMStopAutomationExecution: (input: StopAutomationExecutionCommandInput) => Promise<StopAutomationExecutionCommandOutput>;
    const nativeSSMTerminateSession: (input: TerminateSessionCommandInput) => Promise<TerminateSessionCommandOutput>;
    const nativeSSMUnlabelParameterVersion: (input: UnlabelParameterVersionCommandInput) => Promise<UnlabelParameterVersionCommandOutput>;
    const nativeSSMUpdateAssociation: (input: UpdateAssociationCommandInput) => Promise<UpdateAssociationCommandOutput>;
    const nativeSSMUpdateAssociationStatus: (input: UpdateAssociationStatusCommandInput) => Promise<UpdateAssociationStatusCommandOutput>;
    const nativeSSMUpdateDocument: (input: UpdateDocumentCommandInput) => Promise<UpdateDocumentCommandOutput>;
    const nativeSSMUpdateDocumentDefaultVersion: (input: UpdateDocumentDefaultVersionCommandInput) => Promise<UpdateDocumentDefaultVersionCommandOutput>;
    const nativeSSMUpdateDocumentMetadata: (input: UpdateDocumentMetadataCommandInput) => Promise<UpdateDocumentMetadataCommandOutput>;
    const nativeSSMUpdateMaintenanceWindow: (input: UpdateMaintenanceWindowCommandInput) => Promise<UpdateMaintenanceWindowCommandOutput>;
    const nativeSSMUpdateMaintenanceWindowTarget: (input: UpdateMaintenanceWindowTargetCommandInput) => Promise<UpdateMaintenanceWindowTargetCommandOutput>;
    const nativeSSMUpdateMaintenanceWindowTask: (input: UpdateMaintenanceWindowTaskCommandInput) => Promise<UpdateMaintenanceWindowTaskCommandOutput>;
    const nativeSSMUpdateManagedInstanceRole: (input: UpdateManagedInstanceRoleCommandInput) => Promise<UpdateManagedInstanceRoleCommandOutput>;
    const nativeSSMUpdateOpsItem: (input: UpdateOpsItemCommandInput) => Promise<UpdateOpsItemCommandOutput>;
    const nativeSSMUpdateOpsMetadata: (input: UpdateOpsMetadataCommandInput) => Promise<UpdateOpsMetadataCommandOutput>;
    const nativeSSMUpdatePatchBaseline: (input: UpdatePatchBaselineCommandInput) => Promise<UpdatePatchBaselineCommandOutput>;
    const nativeSSMUpdateResourceDataSync: (input: UpdateResourceDataSyncCommandInput) => Promise<UpdateResourceDataSyncCommandOutput>;
    const nativeSSMUpdateServiceSetting: (input: UpdateServiceSettingCommandInput) => Promise<UpdateServiceSettingCommandOutput>;
}
