import { AddLayerVersionPermissionCommandInput, AddLayerVersionPermissionCommandOutput } from "@aws-sdk/client-lambda";
import { AddPermissionCommandInput, AddPermissionCommandOutput } from "@aws-sdk/client-lambda";
import { CreateAliasCommandInput, CreateAliasCommandOutput } from "@aws-sdk/client-lambda";
import { CreateCodeSigningConfigCommandInput, CreateCodeSigningConfigCommandOutput } from "@aws-sdk/client-lambda";
import { CreateEventSourceMappingCommandInput, CreateEventSourceMappingCommandOutput } from "@aws-sdk/client-lambda";
import { CreateFunctionCommandInput, CreateFunctionCommandOutput } from "@aws-sdk/client-lambda";
import { DeleteAliasCommandInput, DeleteAliasCommandOutput } from "@aws-sdk/client-lambda";
import { DeleteCodeSigningConfigCommandInput, DeleteCodeSigningConfigCommandOutput } from "@aws-sdk/client-lambda";
import { DeleteEventSourceMappingCommandInput, DeleteEventSourceMappingCommandOutput } from "@aws-sdk/client-lambda";
import { DeleteFunctionCommandInput, DeleteFunctionCommandOutput } from "@aws-sdk/client-lambda";
import { DeleteFunctionCodeSigningConfigCommandInput, DeleteFunctionCodeSigningConfigCommandOutput } from "@aws-sdk/client-lambda";
import { DeleteFunctionConcurrencyCommandInput, DeleteFunctionConcurrencyCommandOutput } from "@aws-sdk/client-lambda";
import { DeleteFunctionEventInvokeConfigCommandInput, DeleteFunctionEventInvokeConfigCommandOutput } from "@aws-sdk/client-lambda";
import { DeleteLayerVersionCommandInput, DeleteLayerVersionCommandOutput } from "@aws-sdk/client-lambda";
import { DeleteProvisionedConcurrencyConfigCommandInput, DeleteProvisionedConcurrencyConfigCommandOutput } from "@aws-sdk/client-lambda";
import { GetAccountSettingsCommandInput, GetAccountSettingsCommandOutput } from "@aws-sdk/client-lambda";
import { GetAliasCommandInput, GetAliasCommandOutput } from "@aws-sdk/client-lambda";
import { GetCodeSigningConfigCommandInput, GetCodeSigningConfigCommandOutput } from "@aws-sdk/client-lambda";
import { GetEventSourceMappingCommandInput, GetEventSourceMappingCommandOutput } from "@aws-sdk/client-lambda";
import { GetFunctionCommandInput, GetFunctionCommandOutput } from "@aws-sdk/client-lambda";
import { GetFunctionCodeSigningConfigCommandInput, GetFunctionCodeSigningConfigCommandOutput } from "@aws-sdk/client-lambda";
import { GetFunctionConcurrencyCommandInput, GetFunctionConcurrencyCommandOutput } from "@aws-sdk/client-lambda";
import { GetFunctionConfigurationCommandInput, GetFunctionConfigurationCommandOutput } from "@aws-sdk/client-lambda";
import { GetFunctionEventInvokeConfigCommandInput, GetFunctionEventInvokeConfigCommandOutput } from "@aws-sdk/client-lambda";
import { GetLayerVersionCommandInput, GetLayerVersionCommandOutput } from "@aws-sdk/client-lambda";
import { GetLayerVersionByArnCommandInput, GetLayerVersionByArnCommandOutput } from "@aws-sdk/client-lambda";
import { GetLayerVersionPolicyCommandInput, GetLayerVersionPolicyCommandOutput } from "@aws-sdk/client-lambda";
import { GetPolicyCommandInput, GetPolicyCommandOutput } from "@aws-sdk/client-lambda";
import { GetProvisionedConcurrencyConfigCommandInput, GetProvisionedConcurrencyConfigCommandOutput } from "@aws-sdk/client-lambda";
import { InvokeCommandInput, InvokeCommandOutput } from "@aws-sdk/client-lambda";
import { ListAliasesCommandInput, ListAliasesCommandOutput } from "@aws-sdk/client-lambda";
import { ListCodeSigningConfigsCommandInput, ListCodeSigningConfigsCommandOutput } from "@aws-sdk/client-lambda";
import { ListEventSourceMappingsCommandInput, ListEventSourceMappingsCommandOutput } from "@aws-sdk/client-lambda";
import { ListFunctionEventInvokeConfigsCommandInput, ListFunctionEventInvokeConfigsCommandOutput } from "@aws-sdk/client-lambda";
import { ListFunctionsCommandInput, ListFunctionsCommandOutput } from "@aws-sdk/client-lambda";
import { ListFunctionsByCodeSigningConfigCommandInput, ListFunctionsByCodeSigningConfigCommandOutput } from "@aws-sdk/client-lambda";
import { ListLayerVersionsCommandInput, ListLayerVersionsCommandOutput } from "@aws-sdk/client-lambda";
import { ListLayersCommandInput, ListLayersCommandOutput } from "@aws-sdk/client-lambda";
import { ListProvisionedConcurrencyConfigsCommandInput, ListProvisionedConcurrencyConfigsCommandOutput } from "@aws-sdk/client-lambda";
import { ListTagsCommandInput, ListTagsCommandOutput } from "@aws-sdk/client-lambda";
import { ListVersionsByFunctionCommandInput, ListVersionsByFunctionCommandOutput } from "@aws-sdk/client-lambda";
import { PublishLayerVersionCommandInput, PublishLayerVersionCommandOutput } from "@aws-sdk/client-lambda";
import { PublishVersionCommandInput, PublishVersionCommandOutput } from "@aws-sdk/client-lambda";
import { PutFunctionCodeSigningConfigCommandInput, PutFunctionCodeSigningConfigCommandOutput } from "@aws-sdk/client-lambda";
import { PutFunctionConcurrencyCommandInput, PutFunctionConcurrencyCommandOutput } from "@aws-sdk/client-lambda";
import { PutFunctionEventInvokeConfigCommandInput, PutFunctionEventInvokeConfigCommandOutput } from "@aws-sdk/client-lambda";
import { PutProvisionedConcurrencyConfigCommandInput, PutProvisionedConcurrencyConfigCommandOutput } from "@aws-sdk/client-lambda";
import { RemoveLayerVersionPermissionCommandInput, RemoveLayerVersionPermissionCommandOutput } from "@aws-sdk/client-lambda";
import { RemovePermissionCommandInput, RemovePermissionCommandOutput } from "@aws-sdk/client-lambda";
import { TagResourceCommandInput, TagResourceCommandOutput } from "@aws-sdk/client-lambda";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "@aws-sdk/client-lambda";
import { UpdateAliasCommandInput, UpdateAliasCommandOutput } from "@aws-sdk/client-lambda";
import { UpdateCodeSigningConfigCommandInput, UpdateCodeSigningConfigCommandOutput } from "@aws-sdk/client-lambda";
import { UpdateEventSourceMappingCommandInput, UpdateEventSourceMappingCommandOutput } from "@aws-sdk/client-lambda";
import { UpdateFunctionCodeCommandInput, UpdateFunctionCodeCommandOutput } from "@aws-sdk/client-lambda";
import { UpdateFunctionConfigurationCommandInput, UpdateFunctionConfigurationCommandOutput } from "@aws-sdk/client-lambda";
import { UpdateFunctionEventInvokeConfigCommandInput, UpdateFunctionEventInvokeConfigCommandOutput } from "@aws-sdk/client-lambda";
export declare namespace ASL {
    const nativeLambdaAddLayerVersionPermission: (input: AddLayerVersionPermissionCommandInput) => Promise<AddLayerVersionPermissionCommandOutput>;
    const nativeLambdaAddPermission: (input: AddPermissionCommandInput) => Promise<AddPermissionCommandOutput>;
    const nativeLambdaCreateAlias: (input: CreateAliasCommandInput) => Promise<CreateAliasCommandOutput>;
    const nativeLambdaCreateCodeSigningConfig: (input: CreateCodeSigningConfigCommandInput) => Promise<CreateCodeSigningConfigCommandOutput>;
    const nativeLambdaCreateEventSourceMapping: (input: CreateEventSourceMappingCommandInput) => Promise<CreateEventSourceMappingCommandOutput>;
    const nativeLambdaCreateFunction: (input: CreateFunctionCommandInput) => Promise<CreateFunctionCommandOutput>;
    const nativeLambdaDeleteAlias: (input: DeleteAliasCommandInput) => Promise<DeleteAliasCommandOutput>;
    const nativeLambdaDeleteCodeSigningConfig: (input: DeleteCodeSigningConfigCommandInput) => Promise<DeleteCodeSigningConfigCommandOutput>;
    const nativeLambdaDeleteEventSourceMapping: (input: DeleteEventSourceMappingCommandInput) => Promise<DeleteEventSourceMappingCommandOutput>;
    const nativeLambdaDeleteFunction: (input: DeleteFunctionCommandInput) => Promise<DeleteFunctionCommandOutput>;
    const nativeLambdaDeleteFunctionCodeSigningConfig: (input: DeleteFunctionCodeSigningConfigCommandInput) => Promise<DeleteFunctionCodeSigningConfigCommandOutput>;
    const nativeLambdaDeleteFunctionConcurrency: (input: DeleteFunctionConcurrencyCommandInput) => Promise<DeleteFunctionConcurrencyCommandOutput>;
    const nativeLambdaDeleteFunctionEventInvokeConfig: (input: DeleteFunctionEventInvokeConfigCommandInput) => Promise<DeleteFunctionEventInvokeConfigCommandOutput>;
    const nativeLambdaDeleteLayerVersion: (input: DeleteLayerVersionCommandInput) => Promise<DeleteLayerVersionCommandOutput>;
    const nativeLambdaDeleteProvisionedConcurrencyConfig: (input: DeleteProvisionedConcurrencyConfigCommandInput) => Promise<DeleteProvisionedConcurrencyConfigCommandOutput>;
    const nativeLambdaGetAccountSettings: (input: GetAccountSettingsCommandInput) => Promise<GetAccountSettingsCommandOutput>;
    const nativeLambdaGetAlias: (input: GetAliasCommandInput) => Promise<GetAliasCommandOutput>;
    const nativeLambdaGetCodeSigningConfig: (input: GetCodeSigningConfigCommandInput) => Promise<GetCodeSigningConfigCommandOutput>;
    const nativeLambdaGetEventSourceMapping: (input: GetEventSourceMappingCommandInput) => Promise<GetEventSourceMappingCommandOutput>;
    const nativeLambdaGetFunction: (input: GetFunctionCommandInput) => Promise<GetFunctionCommandOutput>;
    const nativeLambdaGetFunctionCodeSigningConfig: (input: GetFunctionCodeSigningConfigCommandInput) => Promise<GetFunctionCodeSigningConfigCommandOutput>;
    const nativeLambdaGetFunctionConcurrency: (input: GetFunctionConcurrencyCommandInput) => Promise<GetFunctionConcurrencyCommandOutput>;
    const nativeLambdaGetFunctionConfiguration: (input: GetFunctionConfigurationCommandInput) => Promise<GetFunctionConfigurationCommandOutput>;
    const nativeLambdaGetFunctionEventInvokeConfig: (input: GetFunctionEventInvokeConfigCommandInput) => Promise<GetFunctionEventInvokeConfigCommandOutput>;
    const nativeLambdaGetLayerVersion: (input: GetLayerVersionCommandInput) => Promise<GetLayerVersionCommandOutput>;
    const nativeLambdaGetLayerVersionByArn: (input: GetLayerVersionByArnCommandInput) => Promise<GetLayerVersionByArnCommandOutput>;
    const nativeLambdaGetLayerVersionPolicy: (input: GetLayerVersionPolicyCommandInput) => Promise<GetLayerVersionPolicyCommandOutput>;
    const nativeLambdaGetPolicy: (input: GetPolicyCommandInput) => Promise<GetPolicyCommandOutput>;
    const nativeLambdaGetProvisionedConcurrencyConfig: (input: GetProvisionedConcurrencyConfigCommandInput) => Promise<GetProvisionedConcurrencyConfigCommandOutput>;
    const nativeLambdaInvoke: (input: InvokeCommandInput) => Promise<InvokeCommandOutput>;
    const nativeLambdaListAliases: (input: ListAliasesCommandInput) => Promise<ListAliasesCommandOutput>;
    const nativeLambdaListCodeSigningConfigs: (input: ListCodeSigningConfigsCommandInput) => Promise<ListCodeSigningConfigsCommandOutput>;
    const nativeLambdaListEventSourceMappings: (input: ListEventSourceMappingsCommandInput) => Promise<ListEventSourceMappingsCommandOutput>;
    const nativeLambdaListFunctionEventInvokeConfigs: (input: ListFunctionEventInvokeConfigsCommandInput) => Promise<ListFunctionEventInvokeConfigsCommandOutput>;
    const nativeLambdaListFunctions: (input: ListFunctionsCommandInput) => Promise<ListFunctionsCommandOutput>;
    const nativeLambdaListFunctionsByCodeSigningConfig: (input: ListFunctionsByCodeSigningConfigCommandInput) => Promise<ListFunctionsByCodeSigningConfigCommandOutput>;
    const nativeLambdaListLayerVersions: (input: ListLayerVersionsCommandInput) => Promise<ListLayerVersionsCommandOutput>;
    const nativeLambdaListLayers: (input: ListLayersCommandInput) => Promise<ListLayersCommandOutput>;
    const nativeLambdaListProvisionedConcurrencyConfigs: (input: ListProvisionedConcurrencyConfigsCommandInput) => Promise<ListProvisionedConcurrencyConfigsCommandOutput>;
    const nativeLambdaListTags: (input: ListTagsCommandInput) => Promise<ListTagsCommandOutput>;
    const nativeLambdaListVersionsByFunction: (input: ListVersionsByFunctionCommandInput) => Promise<ListVersionsByFunctionCommandOutput>;
    const nativeLambdaPublishLayerVersion: (input: PublishLayerVersionCommandInput) => Promise<PublishLayerVersionCommandOutput>;
    const nativeLambdaPublishVersion: (input: PublishVersionCommandInput) => Promise<PublishVersionCommandOutput>;
    const nativeLambdaPutFunctionCodeSigningConfig: (input: PutFunctionCodeSigningConfigCommandInput) => Promise<PutFunctionCodeSigningConfigCommandOutput>;
    const nativeLambdaPutFunctionConcurrency: (input: PutFunctionConcurrencyCommandInput) => Promise<PutFunctionConcurrencyCommandOutput>;
    const nativeLambdaPutFunctionEventInvokeConfig: (input: PutFunctionEventInvokeConfigCommandInput) => Promise<PutFunctionEventInvokeConfigCommandOutput>;
    const nativeLambdaPutProvisionedConcurrencyConfig: (input: PutProvisionedConcurrencyConfigCommandInput) => Promise<PutProvisionedConcurrencyConfigCommandOutput>;
    const nativeLambdaRemoveLayerVersionPermission: (input: RemoveLayerVersionPermissionCommandInput) => Promise<RemoveLayerVersionPermissionCommandOutput>;
    const nativeLambdaRemovePermission: (input: RemovePermissionCommandInput) => Promise<RemovePermissionCommandOutput>;
    const nativeLambdaTagResource: (input: TagResourceCommandInput) => Promise<TagResourceCommandOutput>;
    const nativeLambdaUntagResource: (input: UntagResourceCommandInput) => Promise<UntagResourceCommandOutput>;
    const nativeLambdaUpdateAlias: (input: UpdateAliasCommandInput) => Promise<UpdateAliasCommandOutput>;
    const nativeLambdaUpdateCodeSigningConfig: (input: UpdateCodeSigningConfigCommandInput) => Promise<UpdateCodeSigningConfigCommandOutput>;
    const nativeLambdaUpdateEventSourceMapping: (input: UpdateEventSourceMappingCommandInput) => Promise<UpdateEventSourceMappingCommandOutput>;
    const nativeLambdaUpdateFunctionCode: (input: UpdateFunctionCodeCommandInput) => Promise<UpdateFunctionCodeCommandOutput>;
    const nativeLambdaUpdateFunctionConfiguration: (input: UpdateFunctionConfigurationCommandInput) => Promise<UpdateFunctionConfigurationCommandOutput>;
    const nativeLambdaUpdateFunctionEventInvokeConfig: (input: UpdateFunctionEventInvokeConfigCommandInput) => Promise<UpdateFunctionEventInvokeConfigCommandOutput>;
}
