import { CreateCapacityProviderCommandInput, CreateCapacityProviderCommandOutput } from "@aws-sdk/client-ecs";
import { CreateServiceCommandInput, CreateServiceCommandOutput } from "@aws-sdk/client-ecs";
import { CreateTaskSetCommandInput, CreateTaskSetCommandOutput } from "@aws-sdk/client-ecs";
import { DeleteAccountSettingCommandInput, DeleteAccountSettingCommandOutput } from "@aws-sdk/client-ecs";
import { DeleteAttributesCommandInput, DeleteAttributesCommandOutput } from "@aws-sdk/client-ecs";
import { DeleteCapacityProviderCommandInput, DeleteCapacityProviderCommandOutput } from "@aws-sdk/client-ecs";
import { DeleteClusterCommandInput, DeleteClusterCommandOutput } from "@aws-sdk/client-ecs";
import { DeleteServiceCommandInput, DeleteServiceCommandOutput } from "@aws-sdk/client-ecs";
import { DeleteTaskSetCommandInput, DeleteTaskSetCommandOutput } from "@aws-sdk/client-ecs";
import { DeregisterContainerInstanceCommandInput, DeregisterContainerInstanceCommandOutput } from "@aws-sdk/client-ecs";
import { DeregisterTaskDefinitionCommandInput, DeregisterTaskDefinitionCommandOutput } from "@aws-sdk/client-ecs";
import { DescribeCapacityProvidersCommandInput, DescribeCapacityProvidersCommandOutput } from "@aws-sdk/client-ecs";
import { DescribeClustersCommandInput, DescribeClustersCommandOutput } from "@aws-sdk/client-ecs";
import { DescribeContainerInstancesCommandInput, DescribeContainerInstancesCommandOutput } from "@aws-sdk/client-ecs";
import { DescribeServicesCommandInput, DescribeServicesCommandOutput } from "@aws-sdk/client-ecs";
import { DescribeTaskDefinitionCommandInput, DescribeTaskDefinitionCommandOutput } from "@aws-sdk/client-ecs";
import { DescribeTaskSetsCommandInput, DescribeTaskSetsCommandOutput } from "@aws-sdk/client-ecs";
import { DescribeTasksCommandInput, DescribeTasksCommandOutput } from "@aws-sdk/client-ecs";
import { DiscoverPollEndpointCommandInput, DiscoverPollEndpointCommandOutput } from "@aws-sdk/client-ecs";
import { ExecuteCommandCommandInput, ExecuteCommandCommandOutput } from "@aws-sdk/client-ecs";
import { ListAccountSettingsCommandInput, ListAccountSettingsCommandOutput } from "@aws-sdk/client-ecs";
import { ListAttributesCommandInput, ListAttributesCommandOutput } from "@aws-sdk/client-ecs";
import { ListClustersCommandInput, ListClustersCommandOutput } from "@aws-sdk/client-ecs";
import { ListContainerInstancesCommandInput, ListContainerInstancesCommandOutput } from "@aws-sdk/client-ecs";
import { ListServicesCommandInput, ListServicesCommandOutput } from "@aws-sdk/client-ecs";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "@aws-sdk/client-ecs";
import { ListTaskDefinitionFamiliesCommandInput, ListTaskDefinitionFamiliesCommandOutput } from "@aws-sdk/client-ecs";
import { ListTaskDefinitionsCommandInput, ListTaskDefinitionsCommandOutput } from "@aws-sdk/client-ecs";
import { ListTasksCommandInput, ListTasksCommandOutput } from "@aws-sdk/client-ecs";
import { PutAccountSettingCommandInput, PutAccountSettingCommandOutput } from "@aws-sdk/client-ecs";
import { PutAccountSettingDefaultCommandInput, PutAccountSettingDefaultCommandOutput } from "@aws-sdk/client-ecs";
import { PutAttributesCommandInput, PutAttributesCommandOutput } from "@aws-sdk/client-ecs";
import { PutClusterCapacityProvidersCommandInput, PutClusterCapacityProvidersCommandOutput } from "@aws-sdk/client-ecs";
import { RegisterContainerInstanceCommandInput, RegisterContainerInstanceCommandOutput } from "@aws-sdk/client-ecs";
import { RegisterTaskDefinitionCommandInput, RegisterTaskDefinitionCommandOutput } from "@aws-sdk/client-ecs";
import { RunTaskCommandInput, RunTaskCommandOutput } from "@aws-sdk/client-ecs";
import { StartTaskCommandInput, StartTaskCommandOutput } from "@aws-sdk/client-ecs";
import { StopTaskCommandInput, StopTaskCommandOutput } from "@aws-sdk/client-ecs";
import { SubmitAttachmentStateChangesCommandInput, SubmitAttachmentStateChangesCommandOutput } from "@aws-sdk/client-ecs";
import { SubmitContainerStateChangeCommandInput, SubmitContainerStateChangeCommandOutput } from "@aws-sdk/client-ecs";
import { SubmitTaskStateChangeCommandInput, SubmitTaskStateChangeCommandOutput } from "@aws-sdk/client-ecs";
import { TagResourceCommandInput, TagResourceCommandOutput } from "@aws-sdk/client-ecs";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "@aws-sdk/client-ecs";
import { UpdateCapacityProviderCommandInput, UpdateCapacityProviderCommandOutput } from "@aws-sdk/client-ecs";
import { UpdateContainerAgentCommandInput, UpdateContainerAgentCommandOutput } from "@aws-sdk/client-ecs";
import { UpdateContainerInstancesStateCommandInput, UpdateContainerInstancesStateCommandOutput } from "@aws-sdk/client-ecs";
import { UpdateServiceCommandInput, UpdateServiceCommandOutput } from "@aws-sdk/client-ecs";
import { UpdateServicePrimaryTaskSetCommandInput, UpdateServicePrimaryTaskSetCommandOutput } from "@aws-sdk/client-ecs";
import { UpdateTaskSetCommandInput, UpdateTaskSetCommandOutput } from "@aws-sdk/client-ecs";
export declare namespace ASL {
    const nativeECSCreateCapacityProvider: (input: CreateCapacityProviderCommandInput) => Promise<CreateCapacityProviderCommandOutput>;
    const nativeECSCreateService: (input: CreateServiceCommandInput) => Promise<CreateServiceCommandOutput>;
    const nativeECSCreateTaskSet: (input: CreateTaskSetCommandInput) => Promise<CreateTaskSetCommandOutput>;
    const nativeECSDeleteAccountSetting: (input: DeleteAccountSettingCommandInput) => Promise<DeleteAccountSettingCommandOutput>;
    const nativeECSDeleteAttributes: (input: DeleteAttributesCommandInput) => Promise<DeleteAttributesCommandOutput>;
    const nativeECSDeleteCapacityProvider: (input: DeleteCapacityProviderCommandInput) => Promise<DeleteCapacityProviderCommandOutput>;
    const nativeECSDeleteCluster: (input: DeleteClusterCommandInput) => Promise<DeleteClusterCommandOutput>;
    const nativeECSDeleteService: (input: DeleteServiceCommandInput) => Promise<DeleteServiceCommandOutput>;
    const nativeECSDeleteTaskSet: (input: DeleteTaskSetCommandInput) => Promise<DeleteTaskSetCommandOutput>;
    const nativeECSDeregisterContainerInstance: (input: DeregisterContainerInstanceCommandInput) => Promise<DeregisterContainerInstanceCommandOutput>;
    const nativeECSDeregisterTaskDefinition: (input: DeregisterTaskDefinitionCommandInput) => Promise<DeregisterTaskDefinitionCommandOutput>;
    const nativeECSDescribeCapacityProviders: (input: DescribeCapacityProvidersCommandInput) => Promise<DescribeCapacityProvidersCommandOutput>;
    const nativeECSDescribeClusters: (input: DescribeClustersCommandInput) => Promise<DescribeClustersCommandOutput>;
    const nativeECSDescribeContainerInstances: (input: DescribeContainerInstancesCommandInput) => Promise<DescribeContainerInstancesCommandOutput>;
    const nativeECSDescribeServices: (input: DescribeServicesCommandInput) => Promise<DescribeServicesCommandOutput>;
    const nativeECSDescribeTaskDefinition: (input: DescribeTaskDefinitionCommandInput) => Promise<DescribeTaskDefinitionCommandOutput>;
    const nativeECSDescribeTaskSets: (input: DescribeTaskSetsCommandInput) => Promise<DescribeTaskSetsCommandOutput>;
    const nativeECSDescribeTasks: (input: DescribeTasksCommandInput) => Promise<DescribeTasksCommandOutput>;
    const nativeECSDiscoverPollEndpoint: (input: DiscoverPollEndpointCommandInput) => Promise<DiscoverPollEndpointCommandOutput>;
    const nativeECSExecuteCommand: (input: ExecuteCommandCommandInput) => Promise<ExecuteCommandCommandOutput>;
    const nativeECSListAccountSettings: (input: ListAccountSettingsCommandInput) => Promise<ListAccountSettingsCommandOutput>;
    const nativeECSListAttributes: (input: ListAttributesCommandInput) => Promise<ListAttributesCommandOutput>;
    const nativeECSListClusters: (input: ListClustersCommandInput) => Promise<ListClustersCommandOutput>;
    const nativeECSListContainerInstances: (input: ListContainerInstancesCommandInput) => Promise<ListContainerInstancesCommandOutput>;
    const nativeECSListServices: (input: ListServicesCommandInput) => Promise<ListServicesCommandOutput>;
    const nativeECSListTagsForResource: (input: ListTagsForResourceCommandInput) => Promise<ListTagsForResourceCommandOutput>;
    const nativeECSListTaskDefinitionFamilies: (input: ListTaskDefinitionFamiliesCommandInput) => Promise<ListTaskDefinitionFamiliesCommandOutput>;
    const nativeECSListTaskDefinitions: (input: ListTaskDefinitionsCommandInput) => Promise<ListTaskDefinitionsCommandOutput>;
    const nativeECSListTasks: (input: ListTasksCommandInput) => Promise<ListTasksCommandOutput>;
    const nativeECSPutAccountSetting: (input: PutAccountSettingCommandInput) => Promise<PutAccountSettingCommandOutput>;
    const nativeECSPutAccountSettingDefault: (input: PutAccountSettingDefaultCommandInput) => Promise<PutAccountSettingDefaultCommandOutput>;
    const nativeECSPutAttributes: (input: PutAttributesCommandInput) => Promise<PutAttributesCommandOutput>;
    const nativeECSPutClusterCapacityProviders: (input: PutClusterCapacityProvidersCommandInput) => Promise<PutClusterCapacityProvidersCommandOutput>;
    const nativeECSRegisterContainerInstance: (input: RegisterContainerInstanceCommandInput) => Promise<RegisterContainerInstanceCommandOutput>;
    const nativeECSRegisterTaskDefinition: (input: RegisterTaskDefinitionCommandInput) => Promise<RegisterTaskDefinitionCommandOutput>;
    const nativeECSRunTask: (input: RunTaskCommandInput) => Promise<RunTaskCommandOutput>;
    const nativeECSStartTask: (input: StartTaskCommandInput) => Promise<StartTaskCommandOutput>;
    const nativeECSStopTask: (input: StopTaskCommandInput) => Promise<StopTaskCommandOutput>;
    const nativeECSSubmitAttachmentStateChanges: (input: SubmitAttachmentStateChangesCommandInput) => Promise<SubmitAttachmentStateChangesCommandOutput>;
    const nativeECSSubmitContainerStateChange: (input: SubmitContainerStateChangeCommandInput) => Promise<SubmitContainerStateChangeCommandOutput>;
    const nativeECSSubmitTaskStateChange: (input: SubmitTaskStateChangeCommandInput) => Promise<SubmitTaskStateChangeCommandOutput>;
    const nativeECSTagResource: (input: TagResourceCommandInput) => Promise<TagResourceCommandOutput>;
    const nativeECSUntagResource: (input: UntagResourceCommandInput) => Promise<UntagResourceCommandOutput>;
    const nativeECSUpdateCapacityProvider: (input: UpdateCapacityProviderCommandInput) => Promise<UpdateCapacityProviderCommandOutput>;
    const nativeECSUpdateContainerAgent: (input: UpdateContainerAgentCommandInput) => Promise<UpdateContainerAgentCommandOutput>;
    const nativeECSUpdateContainerInstancesState: (input: UpdateContainerInstancesStateCommandInput) => Promise<UpdateContainerInstancesStateCommandOutput>;
    const nativeECSUpdateService: (input: UpdateServiceCommandInput) => Promise<UpdateServiceCommandOutput>;
    const nativeECSUpdateServicePrimaryTaskSet: (input: UpdateServicePrimaryTaskSetCommandInput) => Promise<UpdateServicePrimaryTaskSetCommandOutput>;
    const nativeECSUpdateTaskSet: (input: UpdateTaskSetCommandInput) => Promise<UpdateTaskSetCommandOutput>;
}
