import { CloneReceiptRuleSetCommandInput, CloneReceiptRuleSetCommandOutput } from "@aws-sdk/client-ses";
import { CreateConfigurationSetCommandInput, CreateConfigurationSetCommandOutput } from "@aws-sdk/client-ses";
import { CreateConfigurationSetEventDestinationCommandInput, CreateConfigurationSetEventDestinationCommandOutput } from "@aws-sdk/client-ses";
import { CreateConfigurationSetTrackingOptionsCommandInput, CreateConfigurationSetTrackingOptionsCommandOutput } from "@aws-sdk/client-ses";
import { CreateCustomVerificationEmailTemplateCommandInput, CreateCustomVerificationEmailTemplateCommandOutput } from "@aws-sdk/client-ses";
import { CreateReceiptFilterCommandInput, CreateReceiptFilterCommandOutput } from "@aws-sdk/client-ses";
import { CreateReceiptRuleCommandInput, CreateReceiptRuleCommandOutput } from "@aws-sdk/client-ses";
import { CreateReceiptRuleSetCommandInput, CreateReceiptRuleSetCommandOutput } from "@aws-sdk/client-ses";
import { CreateTemplateCommandInput, CreateTemplateCommandOutput } from "@aws-sdk/client-ses";
import { DeleteConfigurationSetCommandInput, DeleteConfigurationSetCommandOutput } from "@aws-sdk/client-ses";
import { DeleteConfigurationSetEventDestinationCommandInput, DeleteConfigurationSetEventDestinationCommandOutput } from "@aws-sdk/client-ses";
import { DeleteConfigurationSetTrackingOptionsCommandInput, DeleteConfigurationSetTrackingOptionsCommandOutput } from "@aws-sdk/client-ses";
import { DeleteCustomVerificationEmailTemplateCommandInput, DeleteCustomVerificationEmailTemplateCommandOutput } from "@aws-sdk/client-ses";
import { DeleteIdentityCommandInput, DeleteIdentityCommandOutput } from "@aws-sdk/client-ses";
import { DeleteIdentityPolicyCommandInput, DeleteIdentityPolicyCommandOutput } from "@aws-sdk/client-ses";
import { DeleteReceiptFilterCommandInput, DeleteReceiptFilterCommandOutput } from "@aws-sdk/client-ses";
import { DeleteReceiptRuleCommandInput, DeleteReceiptRuleCommandOutput } from "@aws-sdk/client-ses";
import { DeleteReceiptRuleSetCommandInput, DeleteReceiptRuleSetCommandOutput } from "@aws-sdk/client-ses";
import { DeleteTemplateCommandInput, DeleteTemplateCommandOutput } from "@aws-sdk/client-ses";
import { DeleteVerifiedEmailAddressCommandInput, DeleteVerifiedEmailAddressCommandOutput } from "@aws-sdk/client-ses";
import { DescribeActiveReceiptRuleSetCommandInput, DescribeActiveReceiptRuleSetCommandOutput } from "@aws-sdk/client-ses";
import { DescribeConfigurationSetCommandInput, DescribeConfigurationSetCommandOutput } from "@aws-sdk/client-ses";
import { DescribeReceiptRuleCommandInput, DescribeReceiptRuleCommandOutput } from "@aws-sdk/client-ses";
import { DescribeReceiptRuleSetCommandInput, DescribeReceiptRuleSetCommandOutput } from "@aws-sdk/client-ses";
import { GetAccountSendingEnabledCommandInput, GetAccountSendingEnabledCommandOutput } from "@aws-sdk/client-ses";
import { GetCustomVerificationEmailTemplateCommandInput, GetCustomVerificationEmailTemplateCommandOutput } from "@aws-sdk/client-ses";
import { GetIdentityDkimAttributesCommandInput, GetIdentityDkimAttributesCommandOutput } from "@aws-sdk/client-ses";
import { GetIdentityMailFromDomainAttributesCommandInput, GetIdentityMailFromDomainAttributesCommandOutput } from "@aws-sdk/client-ses";
import { GetIdentityNotificationAttributesCommandInput, GetIdentityNotificationAttributesCommandOutput } from "@aws-sdk/client-ses";
import { GetIdentityPoliciesCommandInput, GetIdentityPoliciesCommandOutput } from "@aws-sdk/client-ses";
import { GetIdentityVerificationAttributesCommandInput, GetIdentityVerificationAttributesCommandOutput } from "@aws-sdk/client-ses";
import { GetSendQuotaCommandInput, GetSendQuotaCommandOutput } from "@aws-sdk/client-ses";
import { GetSendStatisticsCommandInput, GetSendStatisticsCommandOutput } from "@aws-sdk/client-ses";
import { GetTemplateCommandInput, GetTemplateCommandOutput } from "@aws-sdk/client-ses";
import { ListConfigurationSetsCommandInput, ListConfigurationSetsCommandOutput } from "@aws-sdk/client-ses";
import { ListCustomVerificationEmailTemplatesCommandInput, ListCustomVerificationEmailTemplatesCommandOutput } from "@aws-sdk/client-ses";
import { ListIdentitiesCommandInput, ListIdentitiesCommandOutput } from "@aws-sdk/client-ses";
import { ListIdentityPoliciesCommandInput, ListIdentityPoliciesCommandOutput } from "@aws-sdk/client-ses";
import { ListReceiptFiltersCommandInput, ListReceiptFiltersCommandOutput } from "@aws-sdk/client-ses";
import { ListReceiptRuleSetsCommandInput, ListReceiptRuleSetsCommandOutput } from "@aws-sdk/client-ses";
import { ListTemplatesCommandInput, ListTemplatesCommandOutput } from "@aws-sdk/client-ses";
import { ListVerifiedEmailAddressesCommandInput, ListVerifiedEmailAddressesCommandOutput } from "@aws-sdk/client-ses";
import { PutConfigurationSetDeliveryOptionsCommandInput, PutConfigurationSetDeliveryOptionsCommandOutput } from "@aws-sdk/client-ses";
import { PutIdentityPolicyCommandInput, PutIdentityPolicyCommandOutput } from "@aws-sdk/client-ses";
import { ReorderReceiptRuleSetCommandInput, ReorderReceiptRuleSetCommandOutput } from "@aws-sdk/client-ses";
import { SendBounceCommandInput, SendBounceCommandOutput } from "@aws-sdk/client-ses";
import { SendBulkTemplatedEmailCommandInput, SendBulkTemplatedEmailCommandOutput } from "@aws-sdk/client-ses";
import { SendCustomVerificationEmailCommandInput, SendCustomVerificationEmailCommandOutput } from "@aws-sdk/client-ses";
import { SendEmailCommandInput, SendEmailCommandOutput } from "@aws-sdk/client-ses";
import { SendRawEmailCommandInput, SendRawEmailCommandOutput } from "@aws-sdk/client-ses";
import { SendTemplatedEmailCommandInput, SendTemplatedEmailCommandOutput } from "@aws-sdk/client-ses";
import { SetActiveReceiptRuleSetCommandInput, SetActiveReceiptRuleSetCommandOutput } from "@aws-sdk/client-ses";
import { SetIdentityDkimEnabledCommandInput, SetIdentityDkimEnabledCommandOutput } from "@aws-sdk/client-ses";
import { SetIdentityFeedbackForwardingEnabledCommandInput, SetIdentityFeedbackForwardingEnabledCommandOutput } from "@aws-sdk/client-ses";
import { SetIdentityHeadersInNotificationsEnabledCommandInput, SetIdentityHeadersInNotificationsEnabledCommandOutput } from "@aws-sdk/client-ses";
import { SetIdentityMailFromDomainCommandInput, SetIdentityMailFromDomainCommandOutput } from "@aws-sdk/client-ses";
import { SetIdentityNotificationTopicCommandInput, SetIdentityNotificationTopicCommandOutput } from "@aws-sdk/client-ses";
import { SetReceiptRulePositionCommandInput, SetReceiptRulePositionCommandOutput } from "@aws-sdk/client-ses";
import { TestRenderTemplateCommandInput, TestRenderTemplateCommandOutput } from "@aws-sdk/client-ses";
import { UpdateAccountSendingEnabledCommandInput, UpdateAccountSendingEnabledCommandOutput } from "@aws-sdk/client-ses";
import { UpdateConfigurationSetEventDestinationCommandInput, UpdateConfigurationSetEventDestinationCommandOutput } from "@aws-sdk/client-ses";
import { UpdateConfigurationSetReputationMetricsEnabledCommandInput, UpdateConfigurationSetReputationMetricsEnabledCommandOutput } from "@aws-sdk/client-ses";
import { UpdateConfigurationSetSendingEnabledCommandInput, UpdateConfigurationSetSendingEnabledCommandOutput } from "@aws-sdk/client-ses";
import { UpdateConfigurationSetTrackingOptionsCommandInput, UpdateConfigurationSetTrackingOptionsCommandOutput } from "@aws-sdk/client-ses";
import { UpdateCustomVerificationEmailTemplateCommandInput, UpdateCustomVerificationEmailTemplateCommandOutput } from "@aws-sdk/client-ses";
import { UpdateReceiptRuleCommandInput, UpdateReceiptRuleCommandOutput } from "@aws-sdk/client-ses";
import { UpdateTemplateCommandInput, UpdateTemplateCommandOutput } from "@aws-sdk/client-ses";
import { VerifyDomainDkimCommandInput, VerifyDomainDkimCommandOutput } from "@aws-sdk/client-ses";
import { VerifyDomainIdentityCommandInput, VerifyDomainIdentityCommandOutput } from "@aws-sdk/client-ses";
import { VerifyEmailAddressCommandInput, VerifyEmailAddressCommandOutput } from "@aws-sdk/client-ses";
import { VerifyEmailIdentityCommandInput, VerifyEmailIdentityCommandOutput } from "@aws-sdk/client-ses";
export declare namespace ASL {
    const nativeSESCloneReceiptRuleSet: (input: CloneReceiptRuleSetCommandInput) => Promise<CloneReceiptRuleSetCommandOutput>;
    const nativeSESCreateConfigurationSet: (input: CreateConfigurationSetCommandInput) => Promise<CreateConfigurationSetCommandOutput>;
    const nativeSESCreateConfigurationSetEventDestination: (input: CreateConfigurationSetEventDestinationCommandInput) => Promise<CreateConfigurationSetEventDestinationCommandOutput>;
    const nativeSESCreateConfigurationSetTrackingOptions: (input: CreateConfigurationSetTrackingOptionsCommandInput) => Promise<CreateConfigurationSetTrackingOptionsCommandOutput>;
    const nativeSESCreateCustomVerificationEmailTemplate: (input: CreateCustomVerificationEmailTemplateCommandInput) => Promise<CreateCustomVerificationEmailTemplateCommandOutput>;
    const nativeSESCreateReceiptFilter: (input: CreateReceiptFilterCommandInput) => Promise<CreateReceiptFilterCommandOutput>;
    const nativeSESCreateReceiptRule: (input: CreateReceiptRuleCommandInput) => Promise<CreateReceiptRuleCommandOutput>;
    const nativeSESCreateReceiptRuleSet: (input: CreateReceiptRuleSetCommandInput) => Promise<CreateReceiptRuleSetCommandOutput>;
    const nativeSESCreateTemplate: (input: CreateTemplateCommandInput) => Promise<CreateTemplateCommandOutput>;
    const nativeSESDeleteConfigurationSet: (input: DeleteConfigurationSetCommandInput) => Promise<DeleteConfigurationSetCommandOutput>;
    const nativeSESDeleteConfigurationSetEventDestination: (input: DeleteConfigurationSetEventDestinationCommandInput) => Promise<DeleteConfigurationSetEventDestinationCommandOutput>;
    const nativeSESDeleteConfigurationSetTrackingOptions: (input: DeleteConfigurationSetTrackingOptionsCommandInput) => Promise<DeleteConfigurationSetTrackingOptionsCommandOutput>;
    const nativeSESDeleteCustomVerificationEmailTemplate: (input: DeleteCustomVerificationEmailTemplateCommandInput) => Promise<DeleteCustomVerificationEmailTemplateCommandOutput>;
    const nativeSESDeleteIdentity: (input: DeleteIdentityCommandInput) => Promise<DeleteIdentityCommandOutput>;
    const nativeSESDeleteIdentityPolicy: (input: DeleteIdentityPolicyCommandInput) => Promise<DeleteIdentityPolicyCommandOutput>;
    const nativeSESDeleteReceiptFilter: (input: DeleteReceiptFilterCommandInput) => Promise<DeleteReceiptFilterCommandOutput>;
    const nativeSESDeleteReceiptRule: (input: DeleteReceiptRuleCommandInput) => Promise<DeleteReceiptRuleCommandOutput>;
    const nativeSESDeleteReceiptRuleSet: (input: DeleteReceiptRuleSetCommandInput) => Promise<DeleteReceiptRuleSetCommandOutput>;
    const nativeSESDeleteTemplate: (input: DeleteTemplateCommandInput) => Promise<DeleteTemplateCommandOutput>;
    const nativeSESDeleteVerifiedEmailAddress: (input: DeleteVerifiedEmailAddressCommandInput) => Promise<DeleteVerifiedEmailAddressCommandOutput>;
    const nativeSESDescribeActiveReceiptRuleSet: (input: DescribeActiveReceiptRuleSetCommandInput) => Promise<DescribeActiveReceiptRuleSetCommandOutput>;
    const nativeSESDescribeConfigurationSet: (input: DescribeConfigurationSetCommandInput) => Promise<DescribeConfigurationSetCommandOutput>;
    const nativeSESDescribeReceiptRule: (input: DescribeReceiptRuleCommandInput) => Promise<DescribeReceiptRuleCommandOutput>;
    const nativeSESDescribeReceiptRuleSet: (input: DescribeReceiptRuleSetCommandInput) => Promise<DescribeReceiptRuleSetCommandOutput>;
    const nativeSESGetAccountSendingEnabled: (input: GetAccountSendingEnabledCommandInput) => Promise<GetAccountSendingEnabledCommandOutput>;
    const nativeSESGetCustomVerificationEmailTemplate: (input: GetCustomVerificationEmailTemplateCommandInput) => Promise<GetCustomVerificationEmailTemplateCommandOutput>;
    const nativeSESGetIdentityDkimAttributes: (input: GetIdentityDkimAttributesCommandInput) => Promise<GetIdentityDkimAttributesCommandOutput>;
    const nativeSESGetIdentityMailFromDomainAttributes: (input: GetIdentityMailFromDomainAttributesCommandInput) => Promise<GetIdentityMailFromDomainAttributesCommandOutput>;
    const nativeSESGetIdentityNotificationAttributes: (input: GetIdentityNotificationAttributesCommandInput) => Promise<GetIdentityNotificationAttributesCommandOutput>;
    const nativeSESGetIdentityPolicies: (input: GetIdentityPoliciesCommandInput) => Promise<GetIdentityPoliciesCommandOutput>;
    const nativeSESGetIdentityVerificationAttributes: (input: GetIdentityVerificationAttributesCommandInput) => Promise<GetIdentityVerificationAttributesCommandOutput>;
    const nativeSESGetSendQuota: (input: GetSendQuotaCommandInput) => Promise<GetSendQuotaCommandOutput>;
    const nativeSESGetSendStatistics: (input: GetSendStatisticsCommandInput) => Promise<GetSendStatisticsCommandOutput>;
    const nativeSESGetTemplate: (input: GetTemplateCommandInput) => Promise<GetTemplateCommandOutput>;
    const nativeSESListConfigurationSets: (input: ListConfigurationSetsCommandInput) => Promise<ListConfigurationSetsCommandOutput>;
    const nativeSESListCustomVerificationEmailTemplates: (input: ListCustomVerificationEmailTemplatesCommandInput) => Promise<ListCustomVerificationEmailTemplatesCommandOutput>;
    const nativeSESListIdentities: (input: ListIdentitiesCommandInput) => Promise<ListIdentitiesCommandOutput>;
    const nativeSESListIdentityPolicies: (input: ListIdentityPoliciesCommandInput) => Promise<ListIdentityPoliciesCommandOutput>;
    const nativeSESListReceiptFilters: (input: ListReceiptFiltersCommandInput) => Promise<ListReceiptFiltersCommandOutput>;
    const nativeSESListReceiptRuleSets: (input: ListReceiptRuleSetsCommandInput) => Promise<ListReceiptRuleSetsCommandOutput>;
    const nativeSESListTemplates: (input: ListTemplatesCommandInput) => Promise<ListTemplatesCommandOutput>;
    const nativeSESListVerifiedEmailAddresses: (input: ListVerifiedEmailAddressesCommandInput) => Promise<ListVerifiedEmailAddressesCommandOutput>;
    const nativeSESPutConfigurationSetDeliveryOptions: (input: PutConfigurationSetDeliveryOptionsCommandInput) => Promise<PutConfigurationSetDeliveryOptionsCommandOutput>;
    const nativeSESPutIdentityPolicy: (input: PutIdentityPolicyCommandInput) => Promise<PutIdentityPolicyCommandOutput>;
    const nativeSESReorderReceiptRuleSet: (input: ReorderReceiptRuleSetCommandInput) => Promise<ReorderReceiptRuleSetCommandOutput>;
    const nativeSESSendBounce: (input: SendBounceCommandInput) => Promise<SendBounceCommandOutput>;
    const nativeSESSendBulkTemplatedEmail: (input: SendBulkTemplatedEmailCommandInput) => Promise<SendBulkTemplatedEmailCommandOutput>;
    const nativeSESSendCustomVerificationEmail: (input: SendCustomVerificationEmailCommandInput) => Promise<SendCustomVerificationEmailCommandOutput>;
    const nativeSESSendEmail: (input: SendEmailCommandInput) => Promise<SendEmailCommandOutput>;
    const nativeSESSendRawEmail: (input: SendRawEmailCommandInput) => Promise<SendRawEmailCommandOutput>;
    const nativeSESSendTemplatedEmail: (input: SendTemplatedEmailCommandInput) => Promise<SendTemplatedEmailCommandOutput>;
    const nativeSESSetActiveReceiptRuleSet: (input: SetActiveReceiptRuleSetCommandInput) => Promise<SetActiveReceiptRuleSetCommandOutput>;
    const nativeSESSetIdentityDkimEnabled: (input: SetIdentityDkimEnabledCommandInput) => Promise<SetIdentityDkimEnabledCommandOutput>;
    const nativeSESSetIdentityFeedbackForwardingEnabled: (input: SetIdentityFeedbackForwardingEnabledCommandInput) => Promise<SetIdentityFeedbackForwardingEnabledCommandOutput>;
    const nativeSESSetIdentityHeadersInNotificationsEnabled: (input: SetIdentityHeadersInNotificationsEnabledCommandInput) => Promise<SetIdentityHeadersInNotificationsEnabledCommandOutput>;
    const nativeSESSetIdentityMailFromDomain: (input: SetIdentityMailFromDomainCommandInput) => Promise<SetIdentityMailFromDomainCommandOutput>;
    const nativeSESSetIdentityNotificationTopic: (input: SetIdentityNotificationTopicCommandInput) => Promise<SetIdentityNotificationTopicCommandOutput>;
    const nativeSESSetReceiptRulePosition: (input: SetReceiptRulePositionCommandInput) => Promise<SetReceiptRulePositionCommandOutput>;
    const nativeSESTestRenderTemplate: (input: TestRenderTemplateCommandInput) => Promise<TestRenderTemplateCommandOutput>;
    const nativeSESUpdateAccountSendingEnabled: (input: UpdateAccountSendingEnabledCommandInput) => Promise<UpdateAccountSendingEnabledCommandOutput>;
    const nativeSESUpdateConfigurationSetEventDestination: (input: UpdateConfigurationSetEventDestinationCommandInput) => Promise<UpdateConfigurationSetEventDestinationCommandOutput>;
    const nativeSESUpdateConfigurationSetReputationMetricsEnabled: (input: UpdateConfigurationSetReputationMetricsEnabledCommandInput) => Promise<UpdateConfigurationSetReputationMetricsEnabledCommandOutput>;
    const nativeSESUpdateConfigurationSetSendingEnabled: (input: UpdateConfigurationSetSendingEnabledCommandInput) => Promise<UpdateConfigurationSetSendingEnabledCommandOutput>;
    const nativeSESUpdateConfigurationSetTrackingOptions: (input: UpdateConfigurationSetTrackingOptionsCommandInput) => Promise<UpdateConfigurationSetTrackingOptionsCommandOutput>;
    const nativeSESUpdateCustomVerificationEmailTemplate: (input: UpdateCustomVerificationEmailTemplateCommandInput) => Promise<UpdateCustomVerificationEmailTemplateCommandOutput>;
    const nativeSESUpdateReceiptRule: (input: UpdateReceiptRuleCommandInput) => Promise<UpdateReceiptRuleCommandOutput>;
    const nativeSESUpdateTemplate: (input: UpdateTemplateCommandInput) => Promise<UpdateTemplateCommandOutput>;
    const nativeSESVerifyDomainDkim: (input: VerifyDomainDkimCommandInput) => Promise<VerifyDomainDkimCommandOutput>;
    const nativeSESVerifyDomainIdentity: (input: VerifyDomainIdentityCommandInput) => Promise<VerifyDomainIdentityCommandOutput>;
    const nativeSESVerifyEmailAddress: (input: VerifyEmailAddressCommandInput) => Promise<VerifyEmailAddressCommandOutput>;
    const nativeSESVerifyEmailIdentity: (input: VerifyEmailIdentityCommandInput) => Promise<VerifyEmailIdentityCommandOutput>;
}
