import { AddPermissionCommandInput, AddPermissionCommandOutput } from "@aws-sdk/client-sns";
import { CheckIfPhoneNumberIsOptedOutCommandInput, CheckIfPhoneNumberIsOptedOutCommandOutput } from "@aws-sdk/client-sns";
import { ConfirmSubscriptionCommandInput, ConfirmSubscriptionCommandOutput } from "@aws-sdk/client-sns";
import { CreatePlatformApplicationCommandInput, CreatePlatformApplicationCommandOutput } from "@aws-sdk/client-sns";
import { CreatePlatformEndpointCommandInput, CreatePlatformEndpointCommandOutput } from "@aws-sdk/client-sns";
import { CreateSMSSandboxPhoneNumberCommandInput, CreateSMSSandboxPhoneNumberCommandOutput } from "@aws-sdk/client-sns";
import { CreateTopicCommandInput, CreateTopicCommandOutput } from "@aws-sdk/client-sns";
import { DeleteEndpointCommandInput, DeleteEndpointCommandOutput } from "@aws-sdk/client-sns";
import { DeletePlatformApplicationCommandInput, DeletePlatformApplicationCommandOutput } from "@aws-sdk/client-sns";
import { DeleteSMSSandboxPhoneNumberCommandInput, DeleteSMSSandboxPhoneNumberCommandOutput } from "@aws-sdk/client-sns";
import { DeleteTopicCommandInput, DeleteTopicCommandOutput } from "@aws-sdk/client-sns";
import { GetEndpointAttributesCommandInput, GetEndpointAttributesCommandOutput } from "@aws-sdk/client-sns";
import { GetPlatformApplicationAttributesCommandInput, GetPlatformApplicationAttributesCommandOutput } from "@aws-sdk/client-sns";
import { GetSMSAttributesCommandInput, GetSMSAttributesCommandOutput } from "@aws-sdk/client-sns";
import { GetSMSSandboxAccountStatusCommandInput, GetSMSSandboxAccountStatusCommandOutput } from "@aws-sdk/client-sns";
import { GetSubscriptionAttributesCommandInput, GetSubscriptionAttributesCommandOutput } from "@aws-sdk/client-sns";
import { GetTopicAttributesCommandInput, GetTopicAttributesCommandOutput } from "@aws-sdk/client-sns";
import { ListEndpointsByPlatformApplicationCommandInput, ListEndpointsByPlatformApplicationCommandOutput } from "@aws-sdk/client-sns";
import { ListOriginationNumbersCommandInput, ListOriginationNumbersCommandOutput } from "@aws-sdk/client-sns";
import { ListPhoneNumbersOptedOutCommandInput, ListPhoneNumbersOptedOutCommandOutput } from "@aws-sdk/client-sns";
import { ListPlatformApplicationsCommandInput, ListPlatformApplicationsCommandOutput } from "@aws-sdk/client-sns";
import { ListSMSSandboxPhoneNumbersCommandInput, ListSMSSandboxPhoneNumbersCommandOutput } from "@aws-sdk/client-sns";
import { ListSubscriptionsCommandInput, ListSubscriptionsCommandOutput } from "@aws-sdk/client-sns";
import { ListSubscriptionsByTopicCommandInput, ListSubscriptionsByTopicCommandOutput } from "@aws-sdk/client-sns";
import { ListTagsForResourceCommandInput, ListTagsForResourceCommandOutput } from "@aws-sdk/client-sns";
import { ListTopicsCommandInput, ListTopicsCommandOutput } from "@aws-sdk/client-sns";
import { OptInPhoneNumberCommandInput, OptInPhoneNumberCommandOutput } from "@aws-sdk/client-sns";
import { PublishCommandInput, PublishCommandOutput } from "@aws-sdk/client-sns";
import { RemovePermissionCommandInput, RemovePermissionCommandOutput } from "@aws-sdk/client-sns";
import { SetEndpointAttributesCommandInput, SetEndpointAttributesCommandOutput } from "@aws-sdk/client-sns";
import { SetPlatformApplicationAttributesCommandInput, SetPlatformApplicationAttributesCommandOutput } from "@aws-sdk/client-sns";
import { SetSMSAttributesCommandInput, SetSMSAttributesCommandOutput } from "@aws-sdk/client-sns";
import { SetSubscriptionAttributesCommandInput, SetSubscriptionAttributesCommandOutput } from "@aws-sdk/client-sns";
import { SetTopicAttributesCommandInput, SetTopicAttributesCommandOutput } from "@aws-sdk/client-sns";
import { SubscribeCommandInput, SubscribeCommandOutput } from "@aws-sdk/client-sns";
import { TagResourceCommandInput, TagResourceCommandOutput } from "@aws-sdk/client-sns";
import { UnsubscribeCommandInput, UnsubscribeCommandOutput } from "@aws-sdk/client-sns";
import { UntagResourceCommandInput, UntagResourceCommandOutput } from "@aws-sdk/client-sns";
import { VerifySMSSandboxPhoneNumberCommandInput, VerifySMSSandboxPhoneNumberCommandOutput } from "@aws-sdk/client-sns";
export declare namespace ASL {
    const nativeSNSAddPermission: (input: AddPermissionCommandInput) => Promise<AddPermissionCommandOutput>;
    const nativeSNSCheckIfPhoneNumberIsOptedOut: (input: CheckIfPhoneNumberIsOptedOutCommandInput) => Promise<CheckIfPhoneNumberIsOptedOutCommandOutput>;
    const nativeSNSConfirmSubscription: (input: ConfirmSubscriptionCommandInput) => Promise<ConfirmSubscriptionCommandOutput>;
    const nativeSNSCreatePlatformApplication: (input: CreatePlatformApplicationCommandInput) => Promise<CreatePlatformApplicationCommandOutput>;
    const nativeSNSCreatePlatformEndpoint: (input: CreatePlatformEndpointCommandInput) => Promise<CreatePlatformEndpointCommandOutput>;
    const nativeSNSCreateSMSSandboxPhoneNumber: (input: CreateSMSSandboxPhoneNumberCommandInput) => Promise<CreateSMSSandboxPhoneNumberCommandOutput>;
    const nativeSNSCreateTopic: (input: CreateTopicCommandInput) => Promise<CreateTopicCommandOutput>;
    const nativeSNSDeleteEndpoint: (input: DeleteEndpointCommandInput) => Promise<DeleteEndpointCommandOutput>;
    const nativeSNSDeletePlatformApplication: (input: DeletePlatformApplicationCommandInput) => Promise<DeletePlatformApplicationCommandOutput>;
    const nativeSNSDeleteSMSSandboxPhoneNumber: (input: DeleteSMSSandboxPhoneNumberCommandInput) => Promise<DeleteSMSSandboxPhoneNumberCommandOutput>;
    const nativeSNSDeleteTopic: (input: DeleteTopicCommandInput) => Promise<DeleteTopicCommandOutput>;
    const nativeSNSGetEndpointAttributes: (input: GetEndpointAttributesCommandInput) => Promise<GetEndpointAttributesCommandOutput>;
    const nativeSNSGetPlatformApplicationAttributes: (input: GetPlatformApplicationAttributesCommandInput) => Promise<GetPlatformApplicationAttributesCommandOutput>;
    const nativeSNSGetSMSAttributes: (input: GetSMSAttributesCommandInput) => Promise<GetSMSAttributesCommandOutput>;
    const nativeSNSGetSMSSandboxAccountStatus: (input: GetSMSSandboxAccountStatusCommandInput) => Promise<GetSMSSandboxAccountStatusCommandOutput>;
    const nativeSNSGetSubscriptionAttributes: (input: GetSubscriptionAttributesCommandInput) => Promise<GetSubscriptionAttributesCommandOutput>;
    const nativeSNSGetTopicAttributes: (input: GetTopicAttributesCommandInput) => Promise<GetTopicAttributesCommandOutput>;
    const nativeSNSListEndpointsByPlatformApplication: (input: ListEndpointsByPlatformApplicationCommandInput) => Promise<ListEndpointsByPlatformApplicationCommandOutput>;
    const nativeSNSListOriginationNumbers: (input: ListOriginationNumbersCommandInput) => Promise<ListOriginationNumbersCommandOutput>;
    const nativeSNSListPhoneNumbersOptedOut: (input: ListPhoneNumbersOptedOutCommandInput) => Promise<ListPhoneNumbersOptedOutCommandOutput>;
    const nativeSNSListPlatformApplications: (input: ListPlatformApplicationsCommandInput) => Promise<ListPlatformApplicationsCommandOutput>;
    const nativeSNSListSMSSandboxPhoneNumbers: (input: ListSMSSandboxPhoneNumbersCommandInput) => Promise<ListSMSSandboxPhoneNumbersCommandOutput>;
    const nativeSNSListSubscriptions: (input: ListSubscriptionsCommandInput) => Promise<ListSubscriptionsCommandOutput>;
    const nativeSNSListSubscriptionsByTopic: (input: ListSubscriptionsByTopicCommandInput) => Promise<ListSubscriptionsByTopicCommandOutput>;
    const nativeSNSListTagsForResource: (input: ListTagsForResourceCommandInput) => Promise<ListTagsForResourceCommandOutput>;
    const nativeSNSListTopics: (input: ListTopicsCommandInput) => Promise<ListTopicsCommandOutput>;
    const nativeSNSOptInPhoneNumber: (input: OptInPhoneNumberCommandInput) => Promise<OptInPhoneNumberCommandOutput>;
    const nativeSNSPublish: (input: PublishCommandInput) => Promise<PublishCommandOutput>;
    const nativeSNSRemovePermission: (input: RemovePermissionCommandInput) => Promise<RemovePermissionCommandOutput>;
    const nativeSNSSetEndpointAttributes: (input: SetEndpointAttributesCommandInput) => Promise<SetEndpointAttributesCommandOutput>;
    const nativeSNSSetPlatformApplicationAttributes: (input: SetPlatformApplicationAttributesCommandInput) => Promise<SetPlatformApplicationAttributesCommandOutput>;
    const nativeSNSSetSMSAttributes: (input: SetSMSAttributesCommandInput) => Promise<SetSMSAttributesCommandOutput>;
    const nativeSNSSetSubscriptionAttributes: (input: SetSubscriptionAttributesCommandInput) => Promise<SetSubscriptionAttributesCommandOutput>;
    const nativeSNSSetTopicAttributes: (input: SetTopicAttributesCommandInput) => Promise<SetTopicAttributesCommandOutput>;
    const nativeSNSSubscribe: (input: SubscribeCommandInput) => Promise<SubscribeCommandOutput>;
    const nativeSNSTagResource: (input: TagResourceCommandInput) => Promise<TagResourceCommandOutput>;
    const nativeSNSUnsubscribe: (input: UnsubscribeCommandInput) => Promise<UnsubscribeCommandOutput>;
    const nativeSNSUntagResource: (input: UntagResourceCommandInput) => Promise<UntagResourceCommandOutput>;
    const nativeSNSVerifySMSSandboxPhoneNumber: (input: VerifySMSSandboxPhoneNumberCommandInput) => Promise<VerifySMSSandboxPhoneNumberCommandOutput>;
}
